### ISSUE TITLE
Tooling as a NuGet packages

### ISSUE THREAD

**Issue by lurumad** [Azure/azure-api-management-devops-resource-kit#126]
Hi folks,

It should be great to publish the tolling as a NuGet packages. For example, NSwag provides several NuGet packages for example a MsBuild integration to generate OpenApi specs from your ApiControllers https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-nswag?view=aspnetcore-2.2&tabs=visual-studio%2Cvisual-studio-xml#code-generation.

Regards!

**Comment by miaojiang** [comment]
Triaged. Added to the backlog.
