### ISSUE TITLE
[Extractor] Retrieve and link to policy and Open API files

### ISSUE THREAD

**Issue by ChristopherEquinor** [Azure/azure-api-management-devops-resource-kit#127]
Possibility for the extractor to retrieve, create and link to open API and policy files. This is useful for APIM repositories tracking open API files. This in combination with linking to a policy file, gives a more human readable repository.

**Comment by miaojiang** [comment]
This is currently not possible with how we store data in API Management. We will keep it in the backlog.

**Comment by lucashuet93** [comment]
Closing as this is now a duplicate issue and has been implemented.
