### ISSUE TITLE
Small typo in readme

### ISSUE THREAD

**Issue by alistairl** [Azure/azure-api-management-devops-resource-kit#129]
Typo of the word templates:

"The key in this proposed approach is to keep all API Management configurations in Azure Resource Manager templates. These templates should be kept in a source control system. We will use GIT throughout this example. As illustrated in the picture, there is a Publisher repository that contains all configurations of the Production API Management instance in a collection of **tempaltes**."

**Comment by miaojiang** [comment]
Fixed. Thanks.
