### ISSUE TITLE
[Extractor] azureEventHub logger causes NullReferenceException in Extract.GenerateLoggerTemplate

### ISSUE THREAD

**Issue by nilshedstrom** [Azure/azure-api-management-devops-resource-kit#132]
In my API Management instance I have an azureEventHub logger and when I run extract on that service I get a NullReferenceException on the line loggerResource.properties.credentials.connectionString = propertyResources.Find(p => p.properties.displayName == hiddenKey).properties.value;
because propertyResources.Find returns null.

This is my loggerResource:
new LoggerTemplateResource
{
    properties = new LoggerResourceProperties
    {
        loggerType = "azureEventHub",
        description = "BPST Template Logger",
        credentials = new LoggerCredentials
        {
            name = "bpst-apim-*",
            connectionString = "Endpoint=sb://bpst-apim-*.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/xxxxxxxMM=",
            instrumentationKey = null
        },
        isBuffered = true,
        resourceId = null
    },
    name = "[concat(parameters('ApimServiceName'), '/bpst-apim-*')]",
    type = "Microsoft.ApiManagement/service/loggers",
    apiVersion = "2018-06-01-preview",
    scale = null,
    dependsOn = null
}

The variable hiddenKey is evaluated to
"dpoint=sb://bpst-apim-*.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/xxxxxxxM";

And that key is not present in my propertyResources

I was able to fix the problem by replacing the row which threw the exception with
var propertyResource = propertyResources.Find(p => p.properties.displayName == hiddenKey);
if(propertyResource != null)
   loggerResource.properties.credentials.connectionString = propertyResource.properties.value;

**Comment by odaibert** [comment]
We are fixing this on next PR in a few days. You can find it on /lucashh-templateupdates branch.

**Comment by miaojiang** [comment]
Thanks @nilshedstrom! This is a known issue and we will fix in the next PR.
