### ISSUE TITLE
Fix Extractor README steps

### ISSUE THREAD

**Issue by rabrahamOpti** [Azure/azure-api-management-devops-resource-kit#139]
Quibble: The ReadMe says to run `dotnet restore` before navigating to the directory where the `.sln` file lives. `dotnet restore` will fail, because the `.sln` file isn't in the current directory. It's not hard to find, but it'll save users time if the steps are technically accurate:

## Running the Extractor
Below are the steps to run the Extractor from the source code:
- Clone this repository and navigate to {path_to_folder}/src/APIM_ARMTemplate/apimtemplate 
- Restore its packages using ```dotnet restore```
- Make sure you have signed in using Azure CLI and have switched to the subscription containing the API Management instance from which the configurations will be extracted.

**Comment by miaojiang** [comment]
@rabrahamOpti  thanks for the feedback. Feel free to submit a PR :)

**Comment by rabrahamOpti** [comment]
Done: https://github.com/Azure/azure-api-management-devops-resource-kit/pull/140
