### ISSUE TITLE
As part of CI/CD for API Managment how do I create/update swagger definition

### ISSUE THREAD

**Issue by tkumark** [Azure/azure-api-management-devops-resource-kit#143]
As part of azure API Managment DevOps resource kit could you please explain how to create/update swagger definition. If an api has added a new operation and a new swagger is generated as part of the API deployment. Then how will the new operation get updated in APIM as part of CI/CD.

**Comment by MichalKosowski** [comment]
This is how I am doing it (but note, I am fresh to Azure DevOps and the APIM services also)
I have a repo which has a master template written by me and has the config.yml defined for api services. It also includes swagger.json for every api. So it looks like that:

- **Root**
-- _master.template.json_
-- _config.yml_
-- **ApisConfiguration**
---- **Api1**
------ _api.policy.xml_
------ _api.operationX.policy.xml_
------ _[other opration specific policies]_
------ _swagger.json_
---- **Api2**
---- **Api3**
-- **tool** 
---- _src code of a tool_

When doing updates, someone needs to update swagger or other file in this repo and commit. Then the magic is happening.

Then in CI/CD pipeline I am:
1. Executing the tool to create ARM for each apis
2. Deploy to Azure

NOTE: I have my own master.template.json so I need to insert the links to APIxx arm templates to it before those are generated in Azure. That is oneoff thing anyway.

**Comment by tkumark** [comment]
@MichalKosowski Could you please elaborate on config.yml and the master template does is contain Arm defintion of just APIM or full infrastructure?

**Comment by MichalKosowski** [comment]
Hi,

As soon as I will be back from the holidays, I am planning to write some blog post about how we achieved this and also create a PR for that (but need to clean up code ;) )

Currently our config.yml is used only for APIM. Originally we were keeping the swagger files in the repo, but that is problematic, as you need to copy it over every time backend updates. So I have extended the creator tool with an ability to download the remote file during build.
When you have the file locally in your repo, you can manipulate it and fix some of the Azure issues etc. Still, for other resources (like storage account etc) we keep a separate templates or add them manually to master template (don't like this, but it is not changing frequently)

**Comment by miaojiang** [comment]
Closing for now. Please reopen if further assistance is required. 

@MichalKosowski  would love to see the blog post.

**Comment by levimatheri** [comment]
@MichalKosowski do you have a link to the blog post?
