### ISSUE TITLE
How do I work with different environments?

### ISSUE THREAD

**Issue by JoachimDheedene** [Azure/azure-api-management-devops-resource-kit#146]
I have different environments (dev, test,...) with Api Management. I also have different openapispecification files, one for each environment. The only difference in my different specification files are the backend url's.
Is there a possibility to parameterize these environment specific url's? (Not manually of course, but using the creator tool).

**Comment by mvandevy** [comment]
This would be awesome as we're running into the same issue. Any progress on this?

**Comment by miaojiang** [comment]
You can override the backend URL using the serviceUrl parameter in the YAML config file.
