### ISSUE TITLE
[Documentation] Add extract and create examples of use in Azure DevOps Pipelines

### ISSUE THREAD

**Issue by cs2ea** [Azure/azure-api-management-devops-resource-kit#148]
It would be very helpful to add a step by step description on how to use the extractor and the creator within an Azure DevOps build pipeline. 

This would help "close the loop" for using the these promising tools in a full CI/CD context

**Comment by wsilveiranz** [comment]
On that note, it would be great to have better information on what are the pre-requisites, but also minimum Azure permissions to run the extract tool, both at the resource group and the APIM instance level. Contributor is a safe bet, but I wonder if we there is something more restrictive (reader or something similar).
