### ISSUE TITLE
[Extractor] Parametrize serviceUrl to help configuration management.

### ISSUE THREAD

**Issue by bremnes** [Azure/azure-api-management-devops-resource-kit#158]
Currently the extractor hard codes the url used for the API into the ARM template in the field properties.serviceUrl.

Feature request: In a scenario where one has multiple environments, eg. prod and dev, this url will probably be different and therefore warrant a parameter in the template file.

For other environment variables, I imagine using named values and using those from for instance policies. But it seems it's not possible to use named values in serviceUrl so that must be set at deployment time directly in the api using an arm template.

**Comment by miaojiang** [comment]
Triaged.

**Comment by gc464** [comment]
Hi, is there any update on this feature?
