### ISSUE TITLE
[Extractor] ValidationError: Policy size exceeds allowed limit of 16 KB

### ISSUE THREAD

**Issue by bremnes** [Azure/azure-api-management-devops-resource-kit#159]
Bug summary: when having larger policies the ARM template generated by extractor fails on deployment.

We are using the liquid language in the policy to do some transformation/mapping of request going through API management. The ARM template generated by the extractor embeds this into policyContent as escaped xml.

However, the ARM template only seems to support 16KB of policy when doing it with "contentFormat": "xml" and thus give the validation error `Policy size exceeds allowed limit of 16 KB`.

If the policy is referred to as a an external resource, using `rawxml-link`, then it works.

I am not sure what's the best way to approach this. Perhaps the extractor could have an argument defining if one wants all the policies to be external and then generates separate xml files? But then of course you need to have some kind of logic and parameter(s) to handle where the policy file(s) themselves should reside.

Thoughts or ideas?

**Comment by miaojiang** [comment]
This functionality has been added.
