### ISSUE TITLE
Creator not generating a deployable ARM template from openapi 3.0.1 file

### ISSUE THREAD

**Issue by pvm30** [Azure/azure-api-management-devops-resource-kit#166]
Hi there, and first of all thanks indeed for starting this very promising project  ;-)

I'm having a little bit of trouble when invoking Creator using a simple YAML file like this one ...
  
<img width="530" alt="YAML-FILE-USE-BY-CREATOR" src="https://user-images.githubusercontent.com/2522390/57030820-443efd00-6c46-11e9-830e-81228418f74a.png">

... that references a JSON openapi 3.0.1 version file:

<img width="523" alt="OPEN-3 0 1-JSON" src="https://user-images.githubusercontent.com/2522390/57031929-50788980-6c49-11e9-900b-8f42481e8048.png">

I get a couple of ARM templates and the corresponding parameters file generated without problems :

<img width="395" alt="GeneratedFiles" src="https://user-images.githubusercontent.com/2522390/57031153-3047cb00-6c47-11e9-8cba-4b255b62a4ab.png">

and I can deploy the first template file  _master1.template.jon_ successfully by doing this from Azure CLI:

<img width="814" alt="FIRST-TEMPLATE-DEPLOYED-OK" src="https://user-images.githubusercontent.com/2522390/57031322-bcf28900-6c47-11e9-946f-a8ff6c962741.png">

but when I try to do the same with the second one _master2.template.jon_ I'm getting this error:

<img width="802" alt="SECOND-TEMPLATE-DEPLOYED-KO" src="https://user-images.githubusercontent.com/2522390/57031737-cb8d7000-6c48-11e9-9976-1899b2b2e384.png">

I'm starting to suspect that this has nothing to do with Creator but with Azure Resource Manager  not being able to accept API Management templates referencing "3.0.1" OpenApi files 

Am I right or this is somehow a bug/a lack of functionality in Creator? 

Thanks in advance and best regards

**Comment by miaojiang** [comment]
@pvm30 is it possible to share your OAS, YAML files as well as the templates generated?

**Comment by pvm30** [comment]
Yep no problem, after downloading this https://github.com/Azure/azure-api-management-devops-resource-kit/releases/download/v0.1-alpha/azure-api-management-devops-example-win-x64-v0.1-alpha.zip I executed this command:

_apimtemplate.exe create --configFile .\creator-asegurados-file.yml_+

Here is a zip [api-asegurados-imq-echo.zip](https://github.com/Azure/azure-api-management-devops-resource-kit/files/3135533/api-asegurados-imq-echo.zip) containing that yml file and the three policies and the OAS file _"IMQ_Asegurados.json"_ it references.

Here is another ZIP with the generated files [creatorGeneratedTemplates.zip](https://github.com/Azure/azure-api-management-devops-resource-kit/files/3135562/creatorGeneratedTemplates.zip)

Again thanks

**Comment by miaojiang** [comment]
Found the issue. Basically the content-format needs to be "openapi+json" instead of "swagger+json" if the OAS version is >= 3.0.0. We will fix it or feel free to submit a PR.

**Comment by pvm30** [comment]
@miaojiang  Working in parallel I found it as well.  After replacing the string 

_sed -i 's/swagger-json/openapi+json/g' master2.template.json_

in the generated template it worked like a charm. 

I think the problem could be in this part of the code 

<img width="886" alt="SOURCE-OF-THE-PROBLEM" src="https://user-images.githubusercontent.com/2522390/57046697-c395f600-6c71-11e9-834d-d9ed025bd403.png">

but my expertise in C# is very limited so I probably won't be submitting a PR any time soon

**Comment by miaojiang** [comment]
@pvm30  glad to hear it's working. We'll get it fixed.

**Comment by mradulmodi** [comment]
I am trying to generated the deployment templates and getting the same issue.
