### ISSUE TITLE
[Extractor] Extract releases and make revision current

### ISSUE THREAD

**Issue by lucashuet93** [Azure/azure-api-management-devops-resource-kit#186]

**Comment by miaojiang** [comment]
Added to the backlog.

**Comment by DeagleGross** [comment]
Hello @lucashuet93,
Thanks for your feature suggestion!

Moving this issue to the backlog due to lack of explanation. Please, provide more details for the feature (also you can try to checkout the latest resource-kit and provide logs). If you want - contact me in internal messenger :)

**Comment by adrianhall** [comment]
Since this is now > 2 years old, I am closing this request.
