### ISSUE TITLE
[Extractor] Do not create templates when there is no resource inside

### ISSUE THREAD

**Issue by miaojiang** [Azure/azure-api-management-devops-resource-kit#188]

**Comment by bremnes** [comment]
@miaojiang, this might lead to some old code just "laying around".

Let's say the developer is using the extractor to extract an API and the output path is set to a version controlled location. The first version of an API has a product and is checked in - api definition, product template and all other files.

If the next version (no api revisions or versions) has no products and therefore an empty product file which will not be generated, the extractor will update all files except the product template. Same goes for backend templates etc.

I assume those files wouldn't be linked to from the master template any more, and then needs manual cleanup, but just from glancing over the files in source control, it might give developers the impression that they are being used.

My two cents, just showing that there are some pros and cons here.
