### ISSUE TITLE
[Extractor] OpenAPI Definitions are not exported correctly

### ISSUE THREAD

**Issue by DSpirit** [Azure/azure-api-management-devops-resource-kit#190]

**Comment by DSpirit** [comment]
When using the extractor, the exported schema contains a leading
`{ "definitions": { ... } }`
tag.

After deploying the ARM template, my newly created API looks like this:
```
    "definitions": {
        "definitions": {
            ...
        }
```

**Comment by alenroki** [comment]
Is there any progress on this? It would be nice if it could get fixed.

**Comment by deploymentking** [comment]
I did have a trivial look through the code to see if I could see where this duplicate definitions key was being added and couldn't find anything obvious. Would be good to have this fixed as it means we have to add more steps post extract to make sure the ARM templates are correct before importing them elsewhere

**Comment by bremnes** [comment]
To try to summarize the issue.

The Azure rest api returns different Json structure based on what kind of schema is used (as shown in [SchemaContract](https://docs.microsoft.com/en-us/rest/api/apimanagement/2019-01-01/apischema/get#schemacontract) and I've tested through the API for different content types).

Currently the Extractor take these values and inserts them into the generated ARM template as is, which is currently not working.

The fix:
* `application/vnd.ms-azure-apim.swagger.definitions+json` is wrapped in an extra "definitions".
* `application/vnd.ms-azure-apim.xsd+xml` is wrapped in an extra "value" and doesn't need to be json serialized as it's already an xml escaped string.
* `application/vnd.oai.openapi.components+json` is not correct - **not sure of solution, tried multiple things to no avail.**
* `application/vnd.ms-azure-apim.wadl.grammars+xml` - **unknown**, haven't tried this

@DSpirit, when you mention OpenAPI, do you mean OpenAPI or Swagger? When I tried with OpenAPI the exported ARM template look similar to this and didn't contain multiple definitions (only Swagger did)
```
{
  "properties": {
	"contentType": "application/vnd.oai.openapi.components+json",
	"document": {
	  "value": "{\"components\":{\"schemas\":{\"Order\":{\"type\":\"object\",\"properties\":{\"id\":{\"type\":\"integer\",\"format\":\"int64\"},\"petId\":{\"type\":\"integer\",\"format\":\"int64\"},\"quantity\":{\"type\":\"integer\",\"format\":\"int32\"}
  ...
}
```

This is how a OpenAPI schema looks like through the Azure API when it's correct, but I am so far unable to recreate that when deploying an ARM template:
```
{
  "value": [
    {
      "id": "/subscriptions/[SUBSCRIPTION-ID]/resourceGroups/[RESOURCE-GROUP-NAME]/providers/Microsoft.ApiManagement/service/[APIM-INSTANCE-ID]/apis/[API-NAME]/schemas/5d7bd2b122ea5f19a4c52fa2",
      "type": "Microsoft.ApiManagement/service/apis/schemas",
      "name": "5d7bd2b122ea5f19a4c52fa2",
      "properties": {
        "contentType": "application/vnd.oai.openapi.components+json",
        "document": {
          "components": {
            "schemas": {
              "Order": {
                "type": "object",
                "properties": {
```

I've added a branch (#243) that so far fixes Swagger and WSDL, but OpenAPI is not fixed yet as I haven't figured out how. Feel free to try it out if you are using Swagger and/or WSDL.

**Comment by deploymentking** [comment]
@bremnes I can't speak for @DSpirit but I know that the duplicate definitions are from APIs that are imported from Swagger

**Comment by bremnes** [comment]
@deploymentking, in that case, feel free to test my branch to see if that solves your issue. Even though I don't have the solution for OpenAPI yet, that shouldn't be a blocker for solving Swagger and/or WSDL in the meanwhile.

**Comment by DSpirit** [comment]
> To try to summarize the issue.
> 
> The Azure rest api returns different Json structure based on what kind of schema is used (as shown in [SchemaContract](https://docs.microsoft.com/en-us/rest/api/apimanagement/2019-01-01/apischema/get#schemacontract) and I've tested through the API for different content types).
> 
> Currently the Extractor take these values and inserts them into the generated ARM template as is, which is currently not working.
> 
> The issues:
> 
> * `application/vnd.ms-azure-apim.swagger.definitions+json` is wrapped in an extra "definitions".
> * `application/vnd.ms-azure-apim.xsd+xml` is wrapped in an extra "value" and doesn't need to be json serialized as it's already an xml escaped string.
> * `application/vnd.oai.openapi.components+json` is not correct - **not sure of solution, tried multiple things to no avail.**
> * `application/vnd.ms-azure-apim.wadl.grammars+xml` - **unknown**, haven't tried this
> 
> @DSpirit, when you mention OpenAPI, do you mean OpenAPI or Swagger? When I tried with OpenAPI the exported ARM template look similar to this and didn't contain multiple definitions (only Swagger did)
> 
> ```
> {
>   "properties": {
> 	"contentType": "application/vnd.oai.openapi.components+json",
> 	"document": {
> 	  "value": "{\"components\":{\"schemas\":{\"Order\":{\"type\":\"object\",\"properties\":{\"id\":{\"type\":\"integer\",\"format\":\"int64\"},\"petId\":{\"type\":\"integer\",\"format\":\"int64\"},\"quantity\":{\"type\":\"integer\",\"format\":\"int32\"}
>   ...
> }
> ```
> 
> This is how a OpenAPI schema looks like through the Azure API when it's correct, but I am so far unable to recreate that when deploying an ARM template:
> 
> ```
> {
>   "value": [
>     {
>       "id": "/subscriptions/[SUBSCRIPTION-ID]/resourceGroups/[RESOURCE-GROUP-NAME]/providers/Microsoft.ApiManagement/service/[APIM-INSTANCE-ID]/apis/[API-NAME]/schemas/5d7bd2b122ea5f19a4c52fa2",
>       "type": "Microsoft.ApiManagement/service/apis/schemas",
>       "name": "5d7bd2b122ea5f19a4c52fa2",
>       "properties": {
>         "contentType": "application/vnd.oai.openapi.components+json",
>         "document": {
>           "components": {
>             "schemas": {
>               "Order": {
>                 "type": "object",
>                 "properties": {
> ```
> 
> I've added a branch (#243) that so far fixes Swagger and WSDL, but OpenAPI is not fixed yet as I haven't figured out how. Feel free to try it out if you are using Swagger and/or WSDL.

Hi, in my case your workaround worked (we also use Swagger). Thank you!
