### ISSUE TITLE
[Extractor] GenerateLoggerTemplate Logger crash

### ISSUE THREAD

**Issue by ybelMekk** [Azure/azure-api-management-devops-resource-kit#192]
Im trying to extract all from an Apim instance. but the program crashes when im not adding a singelApiName. The apim has only 6 apis and a global policy for all apis to log to eventhub: "log-to-eventhub logger-id".

command:
/apimtemplate extract --name apimName--resourceGroup apimName --fileFolder /path

When it executes it prints:
Connecting to apimName API Management Service on apimName Resource Group ...
6 API's found ...
Geting loggers from service
'nameOfLogger' Logger found
Geting operations from nameOfApi API:
'nameOfLogger' Logger found

but craches with this:
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Extract.ExtractCommand.GenerateLoggerTemplate(String resourceGroup, String apimname, String fileFolder) in /Users/thiago/Desktop/code/azure-api-management-devops-example/src/APIM_ARMTemplate/apimtemplate/Commands/Extract.cs:line 401
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

Tried to find the reason i code my self, but cant find line 401 in Extract.cs...

What goes wrong here?

**Comment by ybelMekk** [comment]
It works for a single api.
But for extract all, seems it doesn’t extract the event hub logger Id completely , is where I suppose something goes wrong.

**Comment by miaojiang** [comment]
Thanks! We'll take a look.

**Comment by lucashuet93** [comment]
@ybelMekk given the error comes from line 401 in Extract.cs, have you pulled the latest changes?

**Comment by ybelMekk** [comment]
sorry, it seems that i been using the test one, and not the repo, all working fine now :) 
Will you also add support for users, and named values?

**Comment by lucashuet93** [comment]
Great, no worries. Named Values are currently supported in the extractor but we have no plans to support Users and Groups at the moment.
