### ISSUE TITLE
Parameterize named values

### ISSUE THREAD

**Issue by joeyeng** [Azure/azure-api-management-devops-resource-kit#198]
Named values are often env specific. Please allow them to be parameterized. Thanks!

**Comment by mirsaeedi** [comment]
Hi @joeyeng, I've forked this repository and created a command-line tool, [dotnet-apim](https://github.com/mirsaeedi/dotnet-apim), that allows you to define variables inside your yml and policies. please check it out. It's easier to integrate with your cicd pipeline.

**Comment by UmairSyed** [comment]
@mirsaeedi does it parameterize the named values even if we use only the extractor command?

**Comment by mirsaeedi** [comment]
@UmairSyed, dotnet-apim only provides the create functionality. Take a look at the Variables section to understand how the new templates work in dotnet-apim.

Lot's of bugs are fixed and new functionalities are added to dotnet-apim.

**Comment by joeyeng** [comment]
> Hi @joeyeng, I've forked this repository and created a command-line tool, [dotnet-apim](https://github.com/mirsaeedi/dotnet-apim), that allows you to define variables inside your yml and policies. please check it out. It's easier to integrate with your cicd pipeline.

Are you planning to make a PR for this back to the main repo or is it too far of a departure?

**Comment by mirsaeedi** [comment]
@joeyeng, it is quite diverged now and cannot be merged back to this repo. A lot has changed in the source code.

Let me know if you want help on dotnet-apim.

**Comment by joeyeng** [comment]
What's also concerning is that the tool will extract secrets and put them in the named values ARM template. We obviously don't want to store that in source control.

**Comment by mirsaeedi** [comment]
@joeyeng, have used dotnet-apim? Using that you can keep your secrets out of your source control. Then during deployment, you can pass your secret variables to dotnet-apim.

**Comment by joeyeng** [comment]
@mirsaeedi Thanks, but our team has decided to stick with the official MS tool despite its shortcomings, with the hope that is has the longest support and most frequent updates.
