### ISSUE TITLE
PolicyXMLBaseUrl isn't getting passed from Master template to APIs template

### ISSUE THREAD

**Issue by joeyeng** [Azure/azure-api-management-devops-resource-kit#199]
PolicyXMLBaseUrl isn't getting passed to the APIs template from the master template. Also, PolicyXMLBaseUrl is included as a parameter unnecessarily on other templates like named values and products.

**Comment by MalenkavanOmmen** [comment]
Same problem here. When I use the templates in the 'Azure resource group deployment' task in the pipeline, I keep getting an error 'The value for the template parameter 'PolicyXMLBaseUrl' at line '8' and column '25' is not provided.'

**Comment by UmairSyed** [comment]
my PR has the fix https://github.com/Azure/azure-api-management-devops-resource-kit/pull/245

**Comment by EdiFirst** [comment]
I'm facing the trouble even post PR:
'The value for the template parameter 'PolicyXMLBaseUrl' at line '8' and column '25' is not provided. Please see https://aka.ms/resource-manager-parameter-files for usage details.'.

**Comment by RupengLiu** [comment]
fixed
