### ISSUE TITLE
ARM template generator

### ISSUE THREAD

**Issue by solidcloudio** [Azure/azure-api-management-devops-resource-kit#20]
Have you released the ARM template generator yet ?  Or the "second ARM template generator" ?

**Comment by solidcloudio** [comment]
I can't generate a template for APIM in Azure, I get:

Export template operation completed with errors. Some resources were not exported. Please see details for more information. (Code: ExportTemplateCompletedWithErrors)
The schema of resource type 'Microsoft.OperationalInsights/workspaces' is not available. Resources of this type will not be exported to the template. (Code: ResourceTypeSchemaNotFound, Target: Microsoft.OperationalInsights/workspaces)
Could not get resources of the type 'Microsoft.Web/sites/extensions'. Resources of this type will not be exported. (Code: ExportTemplateProviderError, Target: Microsoft.Web/sites/extensions)
Could not get resources of the type 'Microsoft.Web/sites/deployments'. Resources of this type will not be exported. (Code: ExportTemplateProviderError, Target: Microsoft.Web/sites/deployments)
Could not get resources of the type 'Microsoft.Web/sites/premieraddons'. Resources of this type will not be exported. (Code: ExportTemplateProviderError, Target: Microsoft.Web/sites/premieraddons)
Could not get resources of the type 'Microsoft.Web/sites/sourcecontrols'. Resources of this type will not be exported. (Code: ExportTemplateProviderError, Target: Microsoft.Web/sites/sourcecontrols)

**Comment by alexgman** [comment]
any updates?

**Comment by thatsmybirthday** [comment]
Is this marketing article or what? Customers need a generator.

**Comment by solidcloudio** [comment]
http://mlogdberg.com/apimanagement/arm-template-creator  Best I've found so far...

**Comment by thatsmybirthday** [comment]
> Therefore, we will create and open source **an ARM template generator** to help you generate API templates based on Open API (aka., Swagger) files and policy files.

> we will also provide a **second ARM template generator** to help you generate API templates by extracting configurations from an existing APIM instance. Likewise, this generator will also be open sourced.

@vladvino any updates please?

**Comment by swalde** [comment]
Yes @vladvino , what about your two, open source "ARM template generators"?

**Comment by vladvino** [comment]
Still planned, but unfortunately we were not able to get to it yet. In the meantime to mitigate the need for generators you can reference OpenAPI and policy files directly from the templates.

**Comment by alexgman** [comment]
Can you please give an example on how to do that?

**Comment by JB4GH** [comment]
How do you extract policies into files? Via the export config to GIT feature? Or is there another way? other than copy/pasting from the portal :)

**Comment by JB4GH** [comment]
And can you reference the OpenAPI and policy files by other means than public URLs?

**Comment by miaojiang** [comment]
@JB4GH we are working on a tool that will support extract policies into an ARM templates. It's an interesting idea of using the export config to GIT feature.

You can also reference the OpenAPI and policy files by inline-ing them in ARM templates. See an example in this template: https://github.com/Azure/azure-api-management-devops-example/blob/master/example/products/product-starter.template.json

**Comment by lucashuet93** [comment]
Closing as the creation and extraction generator tools are in progress and are documented on the repo
