### ISSUE TITLE
Cant deploy products template

### ISSUE THREAD

**Issue by ybelMekk** [Azure/azure-api-management-devops-resource-kit#200]
It is a bug in the creation of products template.

I use the create tool, and set up some products. 

i set up one like this in yaml:
 - displayName: someName
    description: Some Description
    terms: https://someUrl.com
    subscriptionRequired: false
    state: Published
    policy: policies/generic/empty-policy.xml

notice that i generate this without:
subscriptionRequired: false
    approvalRequired: false
    subscriptionsLimit: 0

When i try to deploy i get this from Azure CLI:
Deployment failed. Correlation ID: 070483cd-7075-4d53-a0bb-88b5a8ab1d27. {

  "error": {

    "code": "ValidationError",

    "message": "Cannot provide values for approvalRequired and subscriptionsLimit when subscriptionRequired is set to false in the request payload",

    "details": null

  }

}

When i check the products-template.json, this values, that i left out is still provided in the template. but they should not be in there..

**Comment by ybelMekk** [comment]
this is still an issue. And when i deploy an new or old api - the key -> subscriptionRequired: false, dont have effect, its always true, still in ARM template its set to false, but the changes dont have effect

**Comment by miaojiang** [comment]
Looking..

**Comment by RupengLiu** [comment]
@ybelMekk Thanks for reporting, it seems the issue has been resolved!
