### ISSUE TITLE
Has this been implemented? Policy expressions are still showing inline

### ISSUE THREAD

**Issue by Leon-Africa** [Azure/azure-api-management-devops-resource-kit#201]
Has this been implemented? Policy expressions are still showing inline

_Originally posted by @Leon-Africa in https://github.com/Azure/azure-api-management-devops-resource-kit/issues/176#issuecomment-503589783_

**Comment by Leon-Africa** [comment]
Could a solution using and object as a parameter https://docs.microsoft.com/en-us/azure/architecture/building-blocks/extending-templates/objects-as-parameters ? And then using a Property Transformer and Collector at deployment?

What I am wondering is to reference the policy expression as a  file in the json schema and inject the values from the external file at deployment.

**Comment by lucashuet93** [comment]
Yes, policy files are now extracted into a policies folder. Each API and operation policy is extracted into it's own file. You'll need to provide the --policyXMLBaseUrl argument when running the extractor and will need to pull the latest master if you haven't recently.
