### ISSUE TITLE
Deployment of api cshtml in policy expression

### ISSUE THREAD

**Issue by Leon-Africa** [Azure/azure-api-management-devops-resource-kit#202]
Hi guys,

I have extracted the all the apis with related policies into folder and pinpointing directly to repo for the PolicyXML remote location. I am now getting the following error:

  "error": {
    "code": "ValidationError",
    "message": "One or more fields contain incorrect values:",
    "details": [
      {
        "code": "ValidationError",
        "target": "representation",
        "message": "An error occurred while parsing EntityName. Line 28, position 56."
      }
    ]
  }
}

This seems to be related to xml being parsed - does the capability already exist to read an xml policy with the scripting in it?

Please let me know if I am missing something.

**Comment by miaojiang** [comment]
@Leon-Africa  Could you upload the files you were trying to deploy?

**Comment by Leon-Africa** [comment]
@miaojiang Got the deployment to work

Truns out the issue was because I PolicyXMLBaseURL was pointing to the Azure DevOps Repo and could not get the file. (I suppose it was reading the error page coming from Azure DevOps as though it were xml). 

I place the files in blob storage instead and now the deployment works. However - that is when the I make it public. I think I will close this issue for now and open a new one for that.
