### ISSUE TITLE
PolicyXMLBase URL when using Blob Storage/Other service

### ISSUE THREAD

**Issue by Leon-Africa** [Azure/azure-api-management-devops-resource-kit#208]
I think it will be useful to allow the option of setting an tokens/service connection required to access the remote url we put into the policy base url.

**Comment by ybelMekk** [comment]
I agree,

**Comment by Leon-Africa** [comment]
As a work around currently adding the signature to the apitemplate.

For the policyxmlbaseurl:

"PolicyXMLBaseUrl": {
      "value": "https://storageaccount.blob.core.windows.net/api-name/policies"
    }

(where api-name is a container in the blob and policies is a "directory" in the container containing the policy files)

In the api template append the signature to the required policy file:

{
      "properties": {
        "value": "[concat(parameters('PolicyXMLBaseUrl'), '/policyfile.xml**?policyFileSignatureHere**",
  "format": "rawxml-link"
      },

 (got the sig (**policyFileSignatureHere**) from Azure Storage Explorer).

Do that for each policy file as referenced in your api template.

**Comment by alan0609** [comment]
I'd like to see some support for this as well. At the moment I have created an extra parameter called SasToken in the parameters.json file.  It is just set to an empty string.  I am then concatenating this in my master template...

    "uri": "[concat(concat(parameters('LinkedTemplatesBaseUrl'), '/myapi-backends.template.json'),parameters('SasToken'))]"

In my DevOps pipelines I can then override this parameter e.g.

    overrideParameters: '-SasToken $(artifactsLocationSasToken)'

This works but it would be nice not to have to edit the files manually.

**Comment by Leon-Africa** [comment]
Implemented - see PR https://github.com/Azure/azure-api-management-devops-resource-kit/pull/322 thanks @alan0609
