### ISSUE TITLE
Running version v0.2-beta in Windows is prompting for user input after ending execution

### ISSUE THREAD

**Issue by joserendal** [Azure/azure-api-management-devops-resource-kit#217]
Hi All,

Today we have switched from versión v0.1-alpha yo v0.2-beta and our Azure Devops CI has crashed when trying to execute the creator.

We were using previously this command: "apimtemplate.exe create --configFile ..." and worked perfectly, but after switching version it is crashing. I have tried locally, and after finishing .exe program execution it is asking for user prompt:

![image](https://user-images.githubusercontent.com/6493934/62699372-acd50d00-b9df-11e9-821b-4c8e6c4b72e4.png)

How can we avoid this? I think there's a .NET directive in the source code for debugging and something is wrong in this version.

Best regards,
Jose

**Comment by odaibert** [comment]
We will check, but looks like **v0.2-beta** was built as a debug not as release version. 

One workaround for now is to build the binaries on your machine. 

`dotnet build --configuration Release`

You can find more info on how to build here: https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-build
