### ISSUE TITLE
Creator tools don't take into account subscriptionKeyParameterNames properties

### ISSUE THREAD

**Issue by Brudem** [Azure/azure-api-management-devops-resource-kit#219]
Hi

The creator tool don't generate entries for "subscriptionKeyParameterNames".

The "subscriptionKeyParameterNames" allow to change the default subscription key parameter (Ocp-Apim-Subscription-Key) with a custom one, in header or query parameter.

The properties are well accepted in Microsoft.ApiManagement service/apis template reference (2019-01-01) 
   "subscriptionKeyParameterNames": {
      "header": "string",
      "query": "string"
    },

But adding theses properties in YAML config of the Creator tool don't seems to have any effect on the created template.

      subscriptionRequired: true
      **subscriptionKeyParameterNames:
        header: X-Oney-Authorization
        query: X-Oney-Authorization**

Best regards. Bruno.

**Comment by miaojiang** [comment]
Triaged.

**Comment by RupengLiu** [comment]
resolved
