### ISSUE TITLE
Error - The deployment parameters are using case sensitive names. The error parameter name(s): apimservicename. Please see https://aka.ms/arm-keyvault for usage details. Task failed while creating or updating the template deployment.

### ISSUE THREAD

**Issue by flyingUnderTheRadar** [Azure/azure-api-management-devops-resource-kit#224]
Following the youtube video - I used the extractor tool to extract an API and am trying to deploy using azure resource group deployment task as show in the video however I get the following error.

<img width="1323" alt="Screen Shot 2019-08-27 at 4 13 29 PM" src="https://user-images.githubusercontent.com/45673569/63814601-52481600-c8e6-11e9-9733-06bf2cbfcb44.png">

Is this a known issue ? I feel like this might be because of the parameter name (in the params file) starting in caps (`ApimServiceName`)

**Comment by miaojiang** [comment]
Triaged.

**Comment by RupengLiu** [comment]
@flyingUnderTheRadar Thanks for reporting.  Essentially when you run extractor, the parameter file with  "ApimServiceName" is self-generated, and currently we haven't found issue deploying api with this parameters file, can I see the parameter file you generated, and I will figure out the cause.

**Comment by flyingUnderTheRadar** [comment]
Hey @RupengLiu , thanks for looking into this. I no longer have the original template / parameter file. I remember the only thing I needed to change to make it work was to change the upper case 'A' to 'a'. 

At this point it, if it works for both cases it would be fair to close this issue.
