### ISSUE TITLE
How to remove API from product?

### ISSUE THREAD

**Issue by harouny** [Azure/azure-api-management-devops-resource-kit#225]
Assuming an API is currently associated with Product1 and Product2 how in ARM template remove the API from Product2?

**Comment by miaojiang** [comment]
Please re-open if assistance is still required.

**Comment by harouny** [comment]
@miaojiang Yes assistance is still required. I haven't received an answer to my question yet.

**Comment by miaojiang** [comment]
Unfortunately this is not supported via ARM templates. The alternative is to use an imperative step in your pipeline to remove an API from a product.

**Comment by harouny** [comment]
Alright that's what we have been doing but was hoping to  see a better way. Thanks
