### ISSUE TITLE
Create a Logic App API or declare it as a Backend

### ISSUE THREAD

**Issue by joserendal** [Azure/azure-api-management-devops-resource-kit#240]
Hello,

I'm having an Azure Logic App which I would like to expose as an API in the API Manager. In order to do so, I guess we have two options if doing manually: either create the API as a Logic App API using the wizard or creating the API from an OpenAPI specification and declare the associated backend.

Do we have any of the options available when using the Resource Kit? If so, could you please provide us with an example?

Best regards,
Jose

**Comment by miaojiang** [comment]
Currently there is no ARM API support to import a Logic App directly. Please use the options you mentioned for now.
