### ISSUE TITLE
[Extractor] Cannot deploy ARM templates : New-AzResourceGroupDeployment : 17:22:49 - Error: Code=InvalidTemplate; Message=Deployment template language expression evaluation failed: 'The language expression '

### ISSUE THREAD

**Issue by BenaissaElAissaoui** [Azure/azure-api-management-devops-resource-kit#242]
The extractor extracts also the 'representations' value in  api.template.json / resources / responses/ representations.

This leads to an error in the syntax of ARM.
"responses": [
          {
            "statusCode": 200,
            "description": "Ok",
            "headers": [],
            "representations": [
              {
                "contentType": "application/json",
                "sample": "[\r\n    {\r\n        \"updated_at\": \"2018-11-28T11:32:30.526951\",\r\n        \"segments\": [\r\n            {\r\n                \"project_id\": 0000000,\r\n                \"position\": 0,\r\n                \"name\": \"Default Segment\",\r\n                \"id\": 00000,\r\n                \"created_at\": \"2018-11-28T11:32:30.529669\"\r\n            }\r\n        ],\r\n        \"name\": \"Fixed\",\r\n        \"id\": 1772804,\r\n        \"created_at\": \"2018-11-28T11:32:30.526940\",\r\n        \"color_id\": 21,\r\n        \"color\": 21,\r\n        \"archived\": false\r\n    },\r\n    {\r\n        \"updated_at\": \"2019-06-12T13:57:30.453177\",\r\n        \"segments\": [\r\n            {\r\n                \"project_id\": 00000,\r\n                \"position\": 2147483647,\r\n                \"name\": \"Default Segment\",\r\n                \"id\": 1569308,\r\n                \"created_at\": \"2019-06-12T13:57:30.454729\"\r\n            }\r\n        ],\r\n        \"name\": \"Test\",\r\n        \"id\": 00000,\r\n        \"created_at\": \"2019-06-12T13:57:30.453167\",\r\n        \"color_id\": 35,\r\n        \"color\": 35,\r\n        \"archived\": false\r\n    },\r\n    {\r\n        \"updated_at\": \"2019-06-12T11:33:39.365967\",\r\n        \"segments\": [\r\n            {\r\n                \"project_id\": 170000,\r\n                \"position\": 0,\r\n                \"name\": \"Default Segment\",\r\n                \"id\": 1369186,\r\n                \"created_at\": \"2018-11-27T09:18:34.313636\"\r\n            }\r\n        ],\r\n        \"name\": \"Holiday\",\r\n        \"id\": 1772078,\r\n        \"created_at\": \"2018-11-27T09:18:34.311563\",\r\n        \"color_id\": 5,\r\n        \"color\": 5,\r\n        \"archived\": false\r\n    },\r\n    {\r\n        \"updated_at\": \"2019-06-12T11:33:23.935740\",\r\n        \"segments\": [\r\n            {\r\n                \"project_id\": 00000,\r\n                \"position\": 2147483647,\r\n                \"name\": \"Default Segment\",\r\n                \"id\": 1569060,\r\n                \"created_at\": \"2019-06-12T11:33:23.936928\"\r\n            }\r\n        ],\r\n        \"name\": \"ServiceNow\",\r\n        \"id\": 97000037,\r\n        \"created_at\": \"2019-06-12T11:33:23.935732\",\r\n        \"color_id\": 2,\r\n        \"color\": 2,\r\n        \"archived\": false\r\n    }\r\n]",
                "schemaId": "1560300054",
                "typeName": "Projects"
              }
            ]
          }
        ],
        "displayName": "/{workspaceId}/projects",
        "method": "GET",
        "urlTemplate": "/{workspaceId}/projects"
      },
      "name": "[concat(parameters('ApimServiceName'), '/myapi/54646464')]",
      "type": "Microsoft.ApiManagement/service/apis/operations",
      "apiVersion": "2018-01-01",
      "dependsOn": [
        "[resourceId('Microsoft.ApiManagement/service/apis', parameters('ApimServiceName'), 'myapi')]",
        "[resourceId('Microsoft.ApiManagement/service/apis/schemas', parameters('ApimServiceName'), 'myapi', '546456464')]"
      ]
    }

**Comment by bremnes** [comment]
Perhaps I'm misunderstanding, but `representations` is a valid property in `request` / `responses` as per the documentation on [service/apis/operations](https://docs.microsoft.com/en-us/azure/templates/microsoft.apimanagement/2019-01-01/service/apis/operations).

Can you paste the entire ARM template? (Great if you can insert it as code as well, since that makes it at bit easier to read.)

**Comment by BenaissaElAissaoui** [comment]
Hi Bremnes, thank you for responding..

The problem is i guess in the sample -> it contains "[  something  ]" .. in ARM [ ] is used for functions.

That makes it fail on it.

**Comment by mzrzz3** [comment]
I get the same error, "**Deployment template language expression evaluation failed: 'The language expression**" when executing an an ARM template extracted from an Open API spec API that contains sample data. If I remove the sample data after extraction the template will deploy with errors.

**Comment by bremnes** [comment]
@BenaissaElAissaoui, @mzrzz3 if you have the chance, feel free to test out the fix I've pull requested in #246.
(Funny enough, we encountered this issue shortly after I left my previous comment on this issue. So it works out for us all. 🙂)

**Comment by BenaissaElAissaoui** [comment]
hi bremnes, when is this branch getting merged with the master?

**Comment by bremnes** [comment]
I'm not sure @BenaissaElAissaoui, that's up to the maintainers of this project. It seems like they've been on a hiatus for a month or so.

@miaojiang and @lucashuet93 , are you able to take a look on the pending pull requests and issues that requires feedback?

**Comment by BenaissaElAissaoui** [comment]
Hi Bremnes thank you for your reply.

I was also wondering if you could share your cicd yaml file with me?

i'm trying to do the same as our friend Abel from the video. I have a folder with a full extraction of all apis and for each api a folder with master/parameter file + the linked templates.

But now i don't know how to do the arm deployment for every new api that i merge.

**Comment by bremnes** [comment]
Sorry @BenaissaElAissaoui, I don't know which video you are referring to.

Can you explain your use case? Are you trying to deploy these api's individually or do you want to deploy them all at the same time? I'm not sure what you mean by 
> But now i don't know how to do the arm deployment for every new api that i merge.

For our case we've done things a bit different, where we have an additional application which organizes the ARM template(s) extracted by this project into our own ARM project structure, so I am not sure if that applies to your situation regarding CI/CD. 
Currently we aren't using the master templates generated by this project. (Our application works on a subset of the files from the "extractor" and merges them into our ARM template project: extracts only named values being used for the specific API being extracted by analyzing policy files; adds the new template files automatically to the arm project in the right level; synchronizes parameters back and forth through the different "layers" of master, child-masters and child-child-masters; creating parameter files; re-writing secret named values/parameters so they are fetched from key vault; +++)

**Comment by BenaissaElAissaoui** [comment]
Your project looks very cool and complex.

My use case is to go from dev to acc or eventually prod.

The api's are created in the portal and we would use this extractor to have the arm templates. 

The idea would be that if a new api has been added in dev, we should just take the exctract and push them to the repo 'dev'. When we merge them into the 'acc' repo,this would trigger a validation of the arm templates and deploy them in the acc instance of apim. As we don't want to deploy over the whole instance, we would like to organise them into directories. One api per directory like seen in the video https://youtu.be/4Sp2Qvmg6j8

But i didnt find a way to just deploy the new folder as you need to tell the arm deploy tool which template you want to deploy.
