### ISSUE TITLE
Console app waits for input before exiting

### ISSUE THREAD

**Issue by kluhman** [Azure/azure-api-management-devops-resource-kit#249]
After running `apimtemplate.exe create ...`, the app waits for any key to be pressed in order to exit. This pose a problem when using the tool in a CI/CD pipeline where input cannot be provided. Can this check either be removed or a parameter added to bypass the check?

I am currently using the exe in the 0.2-beta release

**Comment by MichalKosowski** [comment]
Have the same issue. But if you look into the code, the Console.ReadKey() is placed inside #If DEBUG directive. So if you run the tool in Release mode (and build in release mode) the problem will disappear :).

(note: that was the code like 1 month ago, but I doubt anything changed there...)

**Comment by JEvason90** [comment]
Is this the same as #217 ? Just looking through the list.

**Comment by kluhman** [comment]
@JEvason90 Yes, it does appear to be the same. Apologies for the duplicate
