### ISSUE TITLE
[Extractor] The extractor is not able to add Developer group to 'access control' if a new product is created associated with an api

### ISSUE THREAD

**Issue by UmairSyed** [Azure/azure-api-management-devops-resource-kit#250]
The new product is created without an issue but the 'Access Control' section shows the Administrator being selected where as the source APIM has Developer as well.

**Comment by bremnes** [comment]
@UmairSyed, there is currently no support for extracting access control.

Can you elaborate on your use case? If you want to control access to products through ARM templates, does that mean you wish to for instance control users and groups through source control as well?

I know that some organizations prefer to treat users and groups manually, because that gives api users the option of requesting access through the developer portal, and product owners grant/approve. But not every case is equal, so it would be great if you can specify your use case/feature request.

**Comment by UmairSyed** [comment]
My client wants to assign a custom user group to the product. This user group has few email addresses of internal testers. This group has been added to dev environment manually against which the extractor tool will be run against. However I dont want the client to add this group manually to rest of the environments. 
From your explanation, I think I will update the APIM platform template to create the group when APIM instance is created using ARM template instead of individual API templates. We have a separate pipeline for platform deployment as well. What do you think?

**Comment by bremnes** [comment]
(FYI: I didn't see your PR before commenting yesterday, but good initiative!)

I think that it's when these shared resources come in to play, it starts to be a bit more complex. Groups, products, named values are all tricky that way in that it might be a dependency or association from one or multiple APIs.

In my personal opinion groups belong to the apim instance. So like you suggest, I'd add them to the apim template - at least if hand crafting the ARM templates myself. But the dependency tree might be a bit vulnerable, ref my comment in PR #251 where the extraction of a product with group association would fail if the group doesn't exists in the target instance.

What are you thinking in regards to the users? Both for the users themselves, and the user<->group association. Manually per environment or using ARM templates as well?

**Comment by UmairSyed** [comment]
Yes indeed we need to tackle the deployment of these shared resources on case-by-case basis depending on the requirements. For now, my client has agreed to keep the creation and editing of these groups manually since they are not huge in number (only 1) and in near future they will integrate with a third party auth provider.

**Comment by miaojiang** [comment]
Fixed by #251
