### ISSUE TITLE
[extractor]How do you create one master template for every new added api?

### ISSUE THREAD

**Issue by BenaissaElAissaoui** [Azure/azure-api-management-devops-resource-kit#254]
Hi guys,

I'm trying to follow the example of the video.
When i extract one api i end up with one master template and one parameter template that is not generic. How do you work with it in azure devops? Could somebody share a yaml file of their ci/cd pipeline? I really dont see how you could use one mastere template ro validate/deploy every new api that you add.

**Comment by bremnes** [comment]
Hi again @BenaissaElAissaoui

What are you trying to accomplish in regards to the ci/cd pipeline. Do you want to deploy API's individually or all API's in a "big bang" tied together in a root master template?

And with "... that is not generic". Do you mean that for instance the webservice url is hardcoded in the api template and named values are hardcoded in the named-values template? If that's the case, then that's one of the drawbacks of the current implementation. If not, please elaborate.

I can give you an example of the CI/CD pipeline, I just need to understand your case a bit better first.

**Comment by bremnes** [comment]
From the video that you shared with me earlier, you can see that the setup is one folder pr extracted api. Inside each of those api folders is a master file for that specific api.

For connecting together all the individual api's in one deployable unit:
In the [video this is covered fairly quickly](https://youtu.be/4Sp2Qvmg6j8?t=754), but it's this point where Miao manipulates what he calls a "master template for api management service/instance". If you look at the repository image it's showing a hierarchy of templates. In the video it seems like he only have one root master template binding the API's together (although he only adds one api there in the video).

![image](https://user-images.githubusercontent.com/3669798/67163826-fcd33700-f373-11e9-918f-ab3e795c994d.png)

So it will be something like this, where you have to maintain contoso.apim.master.template.json manually (in the video he is using a vscode snippet so it goes fast, [but you can create your own snippet/template for working quicker](https://code.visualstudio.com/docs/editor/userdefinedsnippets)).

```
templates
├── conf-api/
├──── <other files for conf-api>
├── foodtrucks-api/
├────── contosoapim-dev-apiVersionSets.template.json
├────── contosoapim-dev-FoodTrucks-initial.api.template.json
├────── contosoapim-dev-FoodTrucks-subsequent.api.template.json
├────── contosoapim-dev-master.template.json # deploy this if you only want to deploy a single api, this is the master template for api foodtruck
├────── contosoapim-dev-parameters.json
├── petstore-api/
├──── <files for petstore-api>
├── contoso.apim.master.template.json # deploys if you want to deploy all api's, you edit this manually
└── contoso.apim.master.parameters.json
```

`contoso.apim.master.template.json` will look similar to the template at https://github.com/Azure/azure-api-management-devops-resource-kit/blob/master/example/master.template.json. It's entirely up to your use case if you want to add subscriptions, service sku, products, api's there or not.
Perhaps you'll even want an own template just for gathering the api's `contoso.apis.master.template.json` (which is then referred to from `contoso.apim.master.template.json` and links to `foodtrucks-api/contosoapim-dev-master.template.json`, `petstore-api/contosoapim-dev-master.template.json` and so forth).

Just remember, that currently you must maintain all the master templates "above" your api in the template hierarchy.

If you already have CI/CD for one API, it's similar for the apim service/instance master template.

**Comment by BenaissaElAissaoui** [comment]
In this use case you always redeploy the existing apis or have to remove them from that master template, right?

**Comment by bremnes** [comment]
Well, ARM templates are declarative code, so they will be "redeployed". The deploy will be quicker since it doesn't have to do anything to the ones that are already in the environment. It will just confirm that the existing api's are in the same state as they are described in the ARM template, and will add new ones. If you've made changes directly in the portal without doing the same changes in ARM template, Azure will adjust it to whatever is in the ARM template.

I'm still not sure what your trying to accomplish here. You can set up a pipeline for each individual API or you can deploy them all together in one pipeline. Or you can create deployable units for whatever you define as a bounded context.

**Comment by BenaissaElAissaoui** [comment]
What i want to accomplish is a fast way to go from dev to acceptance or production. 

Changes may be added in the portal for the ease of use.
