### ISSUE TITLE
Move arm code section for a better visibility

### ISSUE THREAD

**Issue by rokeno** [Azure/azure-api-management-devops-resource-kit#286]
It would be of great help and a good addition to move certain sections of the ARM template while they are extracted.
E.g.:
1. Move "apiVersion", "name", "type" and "dependsOn" above the properties section.

```
"apiVersion": "2019-01-01",
"type": "Microsoft.ApiManagement/service/apis",
"name": "[concat(parameters('sp-apim-name'), '/', parameters('sp-name'))]",
"dependsOn": [  ],
"properties": { }
```

2. Move the "displayName",  "method", "urlTemplate" just at the beginning of the properties section of each operation for a better visibility.

```
"apiVersion": "2019-01-01",
"type": "Microsoft.ApiManagement/service/apis/operations",
"name": "[concat(parameters('sp-apim-name'), '/', parameters('sp-name'), '/name-og-operation')]",
"dependsOn": [
        "[resourceId('Microsoft.ApiManagement/service/apis', parameters('sp-apim-name'), parameters('sp-name'))]",
        "[resourceId('Microsoft.ApiManagement/service/apis/schemas', parameters('sp-apim-name'), parameters('sp-name'), 'name-of-schema')]"
      ],
      "properties": {
        "displayName": "find",
        "method": "POST",
        "urlTemplate": "/?soapAction=find",
     
  "templateParameters": [  ],
``` 

The first point can be applied to all types within the ARM templates (whichever they are: API, namedValues, versionSets etc).

This way the first point will be aligned with Microsoft templates.

As you can see from the inserted code above, you can easily identify which one is an API and which one is API's operation and its method.

Thanks.

**Comment by rokeno** [comment]
well, my 'insert code' didn't work as i had hoped. maybe you can arrange it better, it doesn't allow me to.

**Comment by miaojiang** [comment]
Thanks for the feedback. We will take a look.

**Comment by DeagleGross** [comment]
Marking this as closed. Will be available with new release of global refactoring of repo (check [major-repo-refactoring](https://github.com/Azure/azure-api-management-devops-resource-kit/tree/major-repo-refactoring) for progress)
