### ISSUE TITLE
After extracting and deploying a single api with revision, the current revision is not correct

### ISSUE THREAD

**Issue by RupengLiu** [Azure/azure-api-management-devops-resource-kit#288]
1. API revisions on the azure portal is managed without a unique and unchanged id, if the destination apim doesn't have the api, the newly added revision's "apiID" (revision id) will change, ex. (the current revision with blankApi;rev=3 deployed to a APIM that doesn't contains "blankApi", then the revision id will change to "blandApi;rev=1", the original revision info will be lost), and this can cause many unknow issues, we are think about solving this by giving a unique // unchanged id to each api revision

**Comment by DeagleGross** [comment]
Closing this, because it was submitted by internal developer.
If the same trouble appears to you, please, provide a detailed explanation, provide logs\example, if you can.
