### ISSUE TITLE
Question regarding other PaaS services

### ISSUE THREAD

**Issue by Robzilla** [Azure/azure-api-management-devops-resource-kit#296]
Will the tool extract and update the config for other PaaS services such as AppInsights, FrontDoor, KeyVault and so on?

**Comment by miaojiang** [comment]
The tool is for API Management only.

**Comment by Robzilla** [comment]
If I manually add other services to the generated templates, will they be overwritten during a regen?

**Comment by RupengLiu** [comment]
@Robzilla , as long as you have required credentials, generate correct templates, you can (incrementally)  deploy your changes to the corresponding services

**Comment by Robzilla** [comment]
@RupengLiu can I add additional PaaS services to the generated templates (Key Vault, Storage Account, etc.) and then regenerate the templates from the Azure Portal? I understand only API M config changes will be picked up, but will the additional PaaS services that were manually added to the templates be overwritten (and lost) when regenerating the templates?

**Comment by Robzilla** [comment]
@RupengLiu would the Shared Templates be the best place to config services like Key Vault, Storage Account, etc?

**Comment by Robzilla** [comment]
@RupengLiu can I please have a response. I am currently deciding on if we use this method of deployment for all Azure PaaS services going forward. But if the tools and processes actually wipe non API M config then this will not be possible.

**Comment by RupengLiu** [comment]
@Robzilla Sorry, have been loaded with other stuffs. In fact, we have been considering about a CICD for not just APIM, but also to other azure services, but currently it may not possible. However, I'm very happy to involve eng who is more familiar with the deployment process if you are still interested!
