### ISSUE TITLE
Extract by API management tags

### ISSUE THREAD

**Issue by Phetparisouk** [Azure/azure-api-management-devops-resource-kit#299]
Hi,

Is it possible to extract only APIs from specific tags if I mention it on the extractorparams.json file?
I did try : 
{
... tagNames : (tag's name)
}
but doesn't seems to work because it also extract the untag API.

**Comment by RupengLiu** [comment]
Currently it is not supported, but I will add this in the next sprint

**Comment by Phetparisouk** [comment]
Ok, thank you for your answer!

**Comment by miaojiang** [comment]
@Phetparisouk can you elaborate on your scenario?

**Comment by Phetparisouk** [comment]
Hello @miaojiang, each of our api is tagged by tags (which are also generated while extracting in tags.template.json ), and most of the time we only want to extract some apis that got a specific tag on it.

**Comment by adrianhall** [comment]
As part of our purge of old issues, we are closing anything that hasn't been acted upon in > 2 years.  Thank you for your suggestion.  If this is still an issue for you, please consider opening a new issue and providing all the required information.
