### ISSUE TITLE
Missing extractorparams.json from 0.3-gamma zip

### ISSUE THREAD

**Issue by rokeno** [Azure/azure-api-management-devops-resource-kit#302]
The 'extractorparams.json' file is missing from the 0.3-gamma release zip archive for Windows x64 version.
```
D:\res-kit-win64> .\apimtemplate.exe extract
Could not find file 'D:\res-kit-win64\extractorparams.json'.
```

**Comment by RupengLiu** [comment]
Hi~ you need to specify the paramter Json file to run extractor, which looks like .\apimtemplate.exe extract --extractorConfig <your-config-file>

**Comment by rokeno** [comment]
Thanks alot!
