### ISSUE TITLE
[Question] Can I automate the creation of "Named values" on the API Management Services instances?

### ISSUE THREAD

**Issue by mfgonzalez** [Azure/azure-api-management-devops-resource-kit#306]
Is there a way to automate the creation of named values on my API Management instances using the creator tool?
I´m using named values to keep the URIs of my backend services since it changes in every APIM instance (environment). Is it a good practice?
Thanks!

**Comment by RupengLiu** [comment]
@miaojiang , hi Miao, how do you think about this?

**Comment by miaojiang** [comment]
You don't necessarily need to use Named Values. We have parameterized the backendURL in the template. You can override the parameter in your release pipeline for each environment.
