### ISSUE TITLE
[Question]: API templates with more than 100 operations

### ISSUE THREAD

**Issue by rokeno** [Azure/azure-api-management-devops-resource-kit#310]
We have an API that has more than 100 operations inside it. The extractor will only extract 100 entries.      `"type": "Microsoft.ApiManagement/service/apis/operations"`

Is this a limit in the extractor tool or something we need to change in order to get the full template?

Thanks.

**Comment by RupengLiu** [comment]
@rokeno as discussed in issue #189 , this is because our rest api will return 100 records for each request, in order to get full template, we need to recursively calling the api to get all operations

**Comment by RupengLiu** [comment]
@rokeno the issue has been fixed by #318
