### ISSUE TITLE
Master template that deploys all split APIs

### ISSUE THREAD

**Issue by joeyeng** [Azure/azure-api-management-devops-resource-kit#311]
Can the extractor be updated so that when split APIs is used it still generates the master template that deploys all APIs? The main reason we want to use the split API feature is so that the templates are better organized and more human readable. This makes it easier to review pull requests. But we still want the convenience of deploying everything together.

**Comment by RupengLiu** [comment]
hey @joeyeng , to generate master template that deploys all APIs, you just need to delete the "splitApis" paramter, and the paramter file would looks like this
``
{
    "sourceApimName": "<source-apim-name>",
    "destinationApimName": "<destination-apim-name>",
    "resourceGroup": "<resource-group>",
    "fileFolder": "<destination-file-folder>",
    "linkedTemplatesBaseUrl": "<linked_templates_remote_location>",
    "policyXMLBaseUrl": "<policies_remote_location>"
}
``

**Comment by miaojiang** [comment]
Closing for now. Please reopen if the answer above does not work for you.

**Comment by miaojiang** [comment]
After second thought, we will add this functionality.

**Comment by RupengLiu** [comment]
Fixed
