### ISSUE TITLE
[Extractor] apiVersionSet is not extract for some API

### ISSUE THREAD

**Issue by Phetparisouk** [Azure/azure-api-management-devops-resource-kit#312]
Hello,

Is it normal that in some API I extract, their apiVersionSet did not get extract despite having many version ? Is there a solution to fix or extract it anyway?
Thanks in advance.

**Comment by RupengLiu** [comment]
@Phetparisouk you can use --apiVersionSetName to extract versionset, can you send me your parameter file, so that I can help check what's going on?

**Comment by miaojiang** [comment]
Closing since we didn't get a response.

**Comment by Phetparisouk** [comment]
> @Phetparisouk you can use --apiVersionSetName to extract versionset, can you send me your parameter file, so that I can help check what's going on?

thank you for your response. But the problem appears when I want to extract one specific API (with the parameter --apiName), so I cannot use the parameters --apiVersionSetName since we are not allowed to use both parameters at the same time.
This problem only happens to some API, not all of them.

Here is my parameter file :
{ 
    "sourceApimName": "my_apim_source",
    "destinationApimName": "my_destination_apim",
    "resourceGroup": "apim_resource_group",
    "apiName": "target_api",
    "fileFolder": "path_to_my_extracted_api",
    "policyXMLBaseURL" : "url_policy"
}

**Comment by cayodiebe** [comment]
I stay with the same problem, someone fixed it?
