### ISSUE TITLE
Extractor - Policy XML file naming conflict when APIs have operations w/same name

### ISSUE THREAD

**Issue by joeyeng** [Azure/azure-api-management-devops-resource-kit#314]
Repro:
- Create two different APIs 
- Add an operation to both APIs with the same name
- Run the extractor tool to extract all APIs with policies extracted into separate xml files and split API turned off (all policy files should go to the policies folder)

Expected result: The tool creates separate operation policy xml files despite having same operation name.

Actual result: The tool will overwrite the operation policy xml file if it already exists for another API. Then one of the APIs will have the wrong operation policy.

**Comment by RupengLiu** [comment]
@joeyeng thanks for reporting, will check this~
