### ISSUE TITLE
Allow user to specify base name of the template files

### ISSUE THREAD

**Issue by BethSo** [Azure/azure-api-management-devops-resource-kit#315]
This is an enhancement request.  Please revise the template to allow the user to specify the base name of the templates, as an argument,  instead of using the the API Manager source name.  The API Manager name is specific to environment  that is the source,  and is confusing as a name for the template files, it should be able to be more generic.

**Comment by RupengLiu** [comment]
@BethSo will check!

**Comment by miaojiang** [comment]
Triaged. Thanks for the feedback.
