### ISSUE TITLE
[Creator]Revisions with subsequent api arm template gives error

### ISSUE THREAD

**Issue by kbulte** [Azure/azure-api-management-devops-resource-kit#316]
When using the Creator tool it generates an initial.api.template.json and a subsequent.api.template.json arm template. First deploy of these templates works but when we try to deploy a revision via arm by changing the api name to from 'My-Api-v1' to 'My-Api-v1;rev=2' like is done in the samples with http-bin api.  We receive the following error: 
`"code": "BadRequest",
            "message": "{\r\n  \"error\": {\r\n    \"code\": \"ValidationError\",\r\n    \"message\": \"Can't change property Name for non-current revision \
",\r\n    \"details\": null\r\n  }\r\n}"`

When I try to set it as current revision I receive:
`"code": "BadRequest",
            "message": "{\r\n  \"error\": {\r\n    \"code\": \"ValidationError\",\r\n    \"message\": \"One or more fields contain incorrect values:\",\r\n    \"details\": [\r\n      {\r\n
       \"code\": \"ValidationError\",\r\n        \"target\": \"IsCurrent\",\r\n        \"message\": \"Can't set new revision as current.\"\r\n`

Via the portal directly, revisions can be created without any issues for the same api.
Any idea what is the problem here?

**Comment by miaojiang** [comment]
@kbulte  is it possible to provide your templates for us to take a look?

**Comment by kbulte** [comment]
[myapi-backends.template-V1-Rev1.txt](https://github.com/Azure/azure-api-management-devops-resource-kit/files/4090841/myapi-backends.template-V1-Rev1.txt)
[myapi-master.template-V1-Rev1.txt](https://github.com/Azure/azure-api-management-devops-resource-kit/files/4090849/myapi-master.template-V1-Rev1.txt)
[myapi-parameters-V1-Rev1.txt](https://github.com/Azure/azure-api-management-devops-resource-kit/files/4090850/myapi-parameters-V1-Rev1.txt)
[myapi-pets-apiVersionSets.template-V1-Rev1.txt](https://github.com/Azure/azure-api-management-devops-resource-kit/files/4090851/myapi-pets-apiVersionSets.template-V1-Rev1.txt)
[myapi-pets-initial.api.template-V1-Rev1.txt](https://github.com/Azure/azure-api-management-devops-resource-kit/files/4090852/myapi-pets-initial.api.template-V1-Rev1.txt)
[myapi-pets-subsequent.api.template-V1-Rev1.txt](https://github.com/Azure/azure-api-management-devops-resource-kit/files/4090853/myapi-pets-subsequent.api.template-V1-Rev1.txt)
[myapi-master.template-V1-Rev2.txt](https://github.com/Azure/azure-api-management-devops-resource-kit/files/4090858/myapi-master.template-V1-Rev2.txt)
[myapi-parameters-V1-Rev2.txt](https://github.com/Azure/azure-api-management-devops-resource-kit/files/4090859/myapi-parameters-V1-Rev2.txt)
[myapi-pets-initial.api.template-V1-Rev2.txt](https://github.com/Azure/azure-api-management-devops-resource-kit/files/4090860/myapi-pets-initial.api.template-V1-Rev2.txt)
[myapi-pets-subsequent.api.template-V1-Rev2.txt](https://github.com/Azure/azure-api-management-devops-resource-kit/files/4090861/myapi-pets-subsequent.api.template-V1-Rev2.txt)

The first deploy is the master with V1-Rev1 in the filename. Afterwards I try to deploy the master with V1-Rev2 in the filename. Basically the same as in the [(httpbin sample)](https://github.com/Azure/azure-api-management-devops-resource-kit/tree/master/example/api-httpbin). The only difference I see is the httpbin sample does not use an OpenApi based description.

**Comment by miaojiang** [comment]
Thanks. We will take a look.

**Comment by RupengLiu** [comment]
@kbulte Hi, by checking your templates, the issue is that when you want to deploy a revision to an existing api, you can't **"deploy a revision via arm by changing the api name to from 'My-Api-v1' to 'My-Api-v1;rev=2'"**, since this only work when the API doesn't exist and you want to use swagger file / openApi file to create the api. At your second deployment, you can refer this template, https://github.com/Azure/azure-api-management-devops-resource-kit/blob/master/example/api-httpbin/v2-rev2/api-httpbin.v2-rev2.template.json which adds a revision to an existing API.

**Comment by Ben-Duf** [comment]
I have the same issue for a revision using the Creator tool from my valid.yml file and a generated swagger file.
I understand that swagger file can only be pushed to APIM for API creation.
Is there an option in the Creator tool generate api/operations instead of pushing the swagger file?

**Comment by rawrspace** [comment]
I would also be interested in a feature to allow the creator to extract the operations so that as a developer I can simply maintain the openapi spec and the the build pipelines can use the creator to extract the operations for deployment.

When I tested using the creator with a new revision I was getting failed deployments as stated in the original post. When I switched to using the creator for a new version I was able to successfully deploy but it essentially overwrote the first version and that was no longer available.

Is there a place to suggest and vote on desired functionality for these tools?

**Comment by charlievpaul** [comment]
I am trying to deploy and everytime the new deployment happens it replaces the exisiting version. For example current version is 4.x and i am deploying a new version 5.x. What happens is 4.x gets removed and 5.x get deployed

**Comment by leszekkoc** [comment]
Sorry but I am confused. 
I deploy api v1, that is current:
```
  "name": ".../v1"
  "apiRevision": "1",
  "apiVersion": "v1",
  "isCurrent": true,
```

Then I want to deploy new revision toogether with the current one:

```
  "name": ".../v1"
  "apiRevision": "1",
  "apiVersion": "v1",
  "isCurrent": true,
```
and 
```
  "name": ".../v1;rev=2"
  "apiRevision": "2",
  "apiVersion": "v1",
  "isCurrent": false
  "dependsOn":[ /v1 ]
```
With error:
```
 "error": {
    "code": "ValidationError",
   "message": "Can't change property Name for non-current revision ",
    "details": null
  }
```

**Comment by clouddna-au** [comment]
Any update on this one? Is there a way to handle revisions with the creator yaml file currently?

**Comment by levimatheri** [comment]
@kbulte How does your creator config yaml file look like with the revisions?

**Comment by shawnmurtagh** [comment]
@miaojiang any updates? I've tried to chase down the answer to this or see if this is going to be supported in the future, but I can't find an answer or prospective date for a fix.

Is this the suggested workaround? I don't understand how we could revise a publicly exposed API this way. The clients would have to change their version every time they wanted to pick up any change, right?

> As a workaround I currently change the name and suffix to represent the version (I am using segmented versioning) and this allows me to deploy a new API each time. This is not ideal but it is functional. It also requires changing the API name in the open api spec.

**Comment by adrianhall** [comment]
We are cleaning up old issues.  If this problem occurs on the most recent builds, please open a new issue with all the required information.  Thanks,
