### ISSUE TITLE
Is it possible to add the developer portal content to the ARM templates?

### ISSUE THREAD

**Issue by cunhasb** [Azure/azure-api-management-devops-resource-kit#317]
Using pipelines to deploy ARM templates to different environments and as a DR, but lack of developer portal content makes deployments incomplete. Is there a way to include it to the templates?

**Comment by miaojiang** [comment]
It's not possible today. We are still working on it. Thanks for the feedback.

**Comment by mikebudzynski** [comment]
For now you would need to use the REST APIs: https://github.com/Azure/api-management-developer-portal/wiki/Migrate-portal-between-services

**Comment by nosvalds** [comment]
@mikebudzynski that link is dead now and I can't find it on the [apim docs](https://docs.microsoft.com/en-gb/azure/api-management/) or [REST docs](https://docs.microsoft.com/en-gb/azure/api-management/). Do you know where that ended up?

**Comment by mikebudzynski** [comment]
@nosvalds, the documentation has been moved to Azure Docs: https://docs.microsoft.com/en-us/azure/api-management/automate-portal-deployments
