### ISSUE TITLE
Hardcoded Logger resourceId and loggerId

### ISSUE THREAD

**Issue by joeyeng** [Azure/azure-api-management-devops-resource-kit#320]
The resourceId for loggers is hardcoded in the Loggers template and the loggerId is hardcoded in the API template for the Diagnostics resource. These values should be parameterized, since they're environment specific.

**Comment by alan0609** [comment]
We seem to be working through the same issues today!  I'd love to see this as well.  Currently trying to come up with my own hack to get around this issue,

**Comment by joeyeng** [comment]
Yea, we're pretty much manually maintaining all the global templates at this point due to the tools limitations.

**Comment by miaojiang** [comment]
Triaged.

**Comment by RupengLiu** [comment]
@joeyeng @alan0609 Hi, by "loggerId", did you guys mean the name of the logger?

**Comment by joeyeng** [comment]
loggerId is a property on the Microsoft.ApiManagement/service/apis/diagnostics
resource in the API template.

We updated our value so it's parameterized like this:
"[resourceId(parameters('AppInsightsResourceGroupName'),
'Microsoft.ApiManagement/service/loggers',
parameters('ApimServiceName'), parameters('AppInsightsName'))]"
,
