### ISSUE TITLE
Add support for securing linked templates w/SAS token

### ISSUE THREAD

**Issue by joeyeng** [Azure/azure-api-management-devops-resource-kit#321]
Please add support for securing linked templates as shown in this documentation: https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/linked-templates#securing-an-external-template

The containerSasToken parameter should be optional with an empty defaultValue, so not everyone is forced to use it.

**Comment by alan0609** [comment]
I'd like to see this as well.  I've actually cloned the repo and implemented it for myself but it would be nice to have it in the official release.  

In my build I have two parameters defined, linkedTemplatesSasToken and policyXMLSasToken.  If they are excluded from the config file (e.g. extractorparams.json) then the templates are created as normal with no reference to them.  If I include them in the config file then they are used during extraction.  In my config file I don't actually assign them a value (though I could) i.e. I just have

"linkedTemplatesSasToken": "",
"policyXMLSasToken": ""

This causes the parameters to appear in the parameters.json file and be referenced by the api template file and just gives me a parameter I can easily override in the ARM Template Deployment task I have running in Azure DevOps.

**Comment by miaojiang** [comment]
Thank you, we will triage. 

@alan0609  feel free to submit a PR with your improvements :)
