### ISSUE TITLE
[Extractor] Performance issues

### ISSUE THREAD

**Issue by bremnes** [Azure/azure-api-management-devops-resource-kit#323]
As the Extractor has gotten more and more functionality, the performance has taken a dive. This is more noticeable when exporting all apis, and especially when for instance turning on flags such as `splitApis` which leads to all products and named values being fetched for each single api.
(Just as an example: it took two hours exporting 80 apis.)

Performance improvements suggestions:
* Parallelize. For instance apis, operations and policies can be fetched in parallel instead of one by one.
* Cache. There's is no need to retrieve the full list of products (with policies) and named values more than once for the entire extraction process.

**Comment by bremnes** [comment]
I'll try to contribute with some code here. I did some quick testing and was able to reduce the time by ~80% by adding a simple cache in the `CallApiManagementAsync` method.

**Comment by RupengLiu** [comment]
Viewed your fix, it's so nice, thanks @bremnes
