### ISSUE TITLE
Deployment Step Fails

### ISSUE THREAD

**Issue by TravisLRiffle** [Azure/azure-api-management-devops-resource-kit#346]
We have made some modifications to an API that had previously been deployed from DEV to STAGE successfully.  However, this most recent extraction causes an error during the deployment.  I've tried both incramental and complete deployments.  
If it helps, I'm glad to email the templates we are generating.  
`2020-02-04T20:16:33.0585368Z ##[error]At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.
2020-02-04T20:16:33.0586940Z ##[error]Details:
2020-02-04T20:16:33.0588775Z ##[error]Conflict: {
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
        "details": [
          {
            "code": "BadRequest",
            "message": "{\r\n  \"error\": {\r\n    \"code\": \"ValidationError\",\r\n    \"message\": \"One or more fields contain incorrect values:\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"ValidationError\",\r\n        \"target\": \"urlTemplate\",\r\n        \"message\": \"Operation with the same method and URL template already exists\"\r\n      },\r\n      {\r\n        \"code\": \"ValidationError\",\r\n        \"target\": \"method\",\r\n        \"message\": \"Operation with the same method and URL template already exists\"\r\n      }\r\n    ]\r\n  }\r\n}"
          }
        ]
      }
    ]
  }
}
2020-02-04T20:16:33.0594873Z ##[error]Task failed while creating or updating the template deployment.`

**Comment by RupengLiu** [comment]
yep, please email us your templates, it would be helpful! (rupliu@microsoft.com)

**Comment by miaojiang** [comment]
Closing for now, please reopen if you need further assistance.
