### ISSUE TITLE
Issue with quotes in choose in an api policy

### ISSUE THREAD

**Issue by kcprogrammer** [Azure/azure-api-management-devops-resource-kit#350]
We create a backup of our API w/ the extract app. when we attempt to import the created development-fsp-apis.template.json file, we get this error 
`2020-02-06T15:55:41.4962620Z ##[error]3:55:41 PM - Resource Microsoft.ApiManagement/service/apis/policies 'fsp-test/global-api/policy' failed with message '{
  "error": {
    "code": "ValidationError",
    "message": "One or more fields contain incorrect values:",
    "details": [
      {
        "code": "ValidationError",
        "target": "choose",
        "message": "Error in element 'choose' on line 15, column 4: Unterminated string literal.  Strings that start with a quotation mark (\") must be terminated before the end of the line.  However, strings that start with @ and a quotation mark (@\") can span multiple lines."
      }
    ]
  }
}'`
Line 15 looks like
`<when condition=\"@(!string.Equals(\"{{isproductionapi}}\", \"true\"))\">` in the policy value.  Is there an error with how the extractor is persisting the items to the file?

**Comment by kcprogrammer** [comment]
[development-fsp-apis.template.json.txt](https://github.com/Azure/azure-api-management-devops-resource-kit/files/4167070/development-fsp-apis.template.json.txt)

**Comment by miaojiang** [comment]
We will take a look.

**Comment by kcprogrammer** [comment]
This is not a problem w/ the app extracting the ARM template correctly.
The extract values worked properly today, into azure apim, when working with azure support.  Potentially I didn't have the isprodutionapi named value setup in the destination apim instance and it gave the error above, today it errored saying named value missing then imported w/ the named value created.

**Comment by adrianhall** [comment]
We've fixed the named values export in recent versions, so closing this.  If it's still a problem, please re-open.
