### ISSUE TITLE
[extractor]policyXMLSasToken/policyXMLBaseUrl

### ISSUE THREAD

**Issue by spaelling** [Azure/azure-api-management-devops-resource-kit#351]
If `policyXMLSasToken` is an empty string in the parameters file, then it is not included in the ARM templates. A sas token is something I am generating on the fly and is short lived, I do not want it in the parameters file and just override this parameter.

Also if `policyXMLBaseUrl` is not included in the parameters file then the master template still provides this as a parameter but it is not accepted by the linked templates.

**Comment by miaojiang** [comment]
Regarding `policyXMLSasToken`, I think you could use a placeholder in the parameter file and then override it later in your release pipeline. 

@RupengLiu to take a look at the second issue.

**Comment by spaelling** [comment]
> 
> 
> For the second one, yes, if you don't provide policyXMLBaseUrl, it won't be included in the master template's parameters section, but will be included in the resources section, also it will not be included in the parameters file.

No, the problem is if policyXMLBaseUrl is *not* included in the configuration it is still in the master ARM template and provided as a parameter to the linked templates, but the linked templates do not accept this is a parameter, hence the deployment will fail as the ARM template is invalid. Work around is to put it in the configuration with a blank value.

**Comment by spaelling** [comment]
> 
> 
> Regarding `policyXMLSasToken`, I think you could use a placeholder in the parameter file and then override it later in your release pipeline.
> 
> @RupengLiu to take a look at the second issue.

Yes, that is what I am doing. I have plenty of other blank values that work just fine, but this particular one needs a placeholder value that can be overridden later.

**Comment by RupengLiu** [comment]
@spaelling , ok got it! You are right, this is an improvement we need to make.

**Comment by adrianhall** [comment]
Update based on engineer conversation:

When the policyXMLBaseUrl and policyXMLsasToken is provided, we will emit a parameter in the .master.json file and the value in the .parameters.json file - even if they are blank.
