### ISSUE TITLE
[extractor] Ignoring/skipping files while extracting

### ISSUE THREAD

**Issue by Phetparisouk** [Azure/azure-api-management-devops-resource-kit#354]
Hello, 

I would like to know if we can extract some specific files of the API (not all of them) while using the extractor tools.
For example, is it possible if I only want to generate the api template, its versionSet and its policies while ignoring the other one ?

**Comment by adrianhall** [comment]
No, this is not possible.  You can extract a single API, which may be what you want.

Please feel free to suggest it as a feature, but try to think of how you would use it and what the expectations would be.
