### ISSUE TITLE
[Creator] "type" is missing for parameters

### ISSUE THREAD

**Issue by jjinxn** [Azure/azure-api-management-devops-resource-kit#355]
When creating the templates "type" is not included:
```
"parameters": {
    "ApimServiceName": {
      "value": "product-api"
    }
  },
```

"type", however, is required according to the spec: https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-syntax#parameters

**Comment by adrianhall** [comment]
There is not enough information to diagnose this problem.  We recently refactored the extractor and are doing the same with the creator, so this may get fixed anyhow.  If this is an issue with the extractor right now, please open an issue and be more specific about the issue.

Thank you.
