### ISSUE TITLE
The number of template resources limit exceeded

### ISSUE THREAD

**Issue by JosephJonesPHX** [Azure/azure-api-management-devops-resource-kit#360]
After using the extract tool to generate a set of templates I am unable to recreate the APIM instance in a new resource because of the following error:
##[error]Deployment template validation failed: 'The number of template resources limit exceeded. Limit: '800' and actual: '1279'

I understand that Azure has a hard limit of 800 resources per ARM template, and that includes any linked templates, but why does the tool allow you to extract more then that?  Also if I cannot recreate the APIM insistence in each stage of of the release pipeline then what is the correct work flow using this tool?

**Comment by adrianhall** [comment]
Unfortunately, this is a limitation of ARM and nothing we can do about it.

You can deploy the APIs separately as a workaround.
