### ISSUE TITLE
Create command fails to generate api if it contains another api's name

### ISSUE THREAD

**Issue by sorvis** [Azure/azure-api-management-devops-resource-kit#363]
If in the yml file you create some apis similar to this:
```
  - name: MyApi
    suffix: myapi
    apiVersion: v1
    apiRevision: 1
    apiVersionSetId: myapi
  - name: MyApi2
    suffix: myapi
    apiVersion: v2
    apiRevision: 1
    apiVersionSetId: myapi
```

When you run the create command you will only see the following files:
![image](https://user-images.githubusercontent.com/1037467/76221990-4f60a300-61f0-11ea-9fe0-1dd8967bda9b.png)

The MyApi2 template over writes the MyApi temples. Some code similar to this should resolve the issue:

```
From 0b56d0a304b2c53d22af37b3024030e84637a281 Mon Sep 17 00:00:00 2001
From: Steven Orvis
Date: Mon, 9 Mar 2020 10:17:02 -0400
Subject: [PATCH] Fix bug where wrong API name is picked

---
 tools/apimtemplate/Commands/Create.cs | 13 ++++++++++++-
 1 file changed, 12 insertions(+), 1 deletion(-)

diff --git a/tools/apimtemplate/Commands/Create.cs b/tools/apimtemplate/Commands/Create.cs
index 38fb040..8ae7261 100644
--- a/tools/apimtemplate/Commands/Create.cs
+++ b/tools/apimtemplate/Commands/Create.cs
@@ -113,7 +113,8 @@ namespace Microsoft.Azure.Management.ApiManagement.ArmTemplates.Create
                     foreach (Template apiTemplate in apiTemplates)
                     {
                         APITemplateResource apiResource = apiTemplate.resources.FirstOrDefault(resource => resource.type == ResourceTypeConstants.API) as APITemplateResource;
-                        APIConfig providedAPIConfiguration = creatorConfig.apis.FirstOrDefault(api => apiResource.name.Contains(api.name, StringComparison.Ordinal));
+                        var apiName = parseNameField(apiResource.name, 1).FirstOrDefault();
+                        APIConfig providedAPIConfiguration = creatorConfig.apis.FirstOrDefault(api => string.Equals(api.name, apiName, StringComparison.Ordinal));
                         // if the api version is not null the api is split into multiple templates. If the template is split and the content value has been set, then the template is for a subsequent api
                         string apiFileName = fileNameGenerator.GenerateCreatorAPIFileName(providedAPIConfiguration.name, apiTemplateCreator.isSplitAPI(providedAPIConfiguration), apiResource.properties.value != null, creatorConfig.apimServiceName);
                         fileWriter.WriteJSONToFile(apiTemplate, String.Concat(creatorConfig.outputLocation, apiFileName));
@@ -153,6 +154,16 @@ namespace Microsoft.Azure.Management.ApiManagement.ArmTemplates.Create
                 }
                 return 0;
             });
+        }
+
+        private static IEnumerable<string> parseNameField(string field, int offset)
+        {
+            if (field == null) return new string[] { };
+            var split = field.Split('/');
+            if (split.Length < offset) return new string[] { };
+            var skipOffset = split.Skip(offset);
+            var trimmedEnded = skipOffset.Select(x => x.Replace("')]", string.Empty));
+            return trimmedEnded;
         }
     }
 }
-- 
2.15.0.windows.1


```

So then it will create the following files:
![image](https://user-images.githubusercontent.com/1037467/76222646-3f958e80-61f1-11ea-82ac-0d348dc9f3d5.png)

**Comment by adrianhall** [comment]
Thank you for your input on the creator tool.  We are currently looking at the future of the creator tool and would like your feedback.  Please could you fill in the survey at https://forms.office.com/r/w7rQp88NwH - your input is appreciated.

**Comment by zcarroll4** [comment]
Any updates on this?

**Comment by adrianhall** [comment]
We are pretty good at ensuring that the status of all issues is updated according to our current understanding.  No comments = no update.

**Comment by adrianhall** [comment]
This project is now in "maintenance" mode. This means that no new features will be accepted and fixes will be limited to security fixes. We expect to retire the DevOps Resource Kit by the end of 2023. At that time, the DevOps Resource Kit repository will be archived and there will be no further updates.

While you are free to fork the DevOps Resource Kit yourself, we recommend that you migrate to the following products:

* If you are using creator, switch over to using [Bicep](https://learn.microsoft.com/azure/azure-resource-manager/bicep/overview) templates. Bicep is a descriptive language for describing infrastructure, fully supports all features of Azure API Management, and is covered in any support agreement that you have with Azure. You can find bicep modules and examples for handling API Management APIs at https://github.com/azure-samples/api-management-sample-apis.
* If you are using extractor, switch your pipelines to use [APIOps](https://github.com/azure/apiops). APIOps applies the concepts of GitOps to API deployments. It is faster and more flexible than the DevOps Resource Kit.
