### ISSUE TITLE
[Creator]Help me with simple Way to deply multiple api into APIM through ARM template

### ISSUE THREAD

**Issue by satheeshkv** [Azure/azure-api-management-devops-resource-kit#366]
Team,
I have referred thia artical and able to deply 1api into APIM through ADO. Since my organization has 40 Apis and want to deploy all in one template. I am not getting any document on how to segregate API's in single template or how easy to deploy. 
If you have any example config  file which deploy multiple apis , please  share

**Comment by wvaneck** [comment]
I am working on an approach which uses the ARM template output from the Extractor as-is and allows you to manage and deploy the API's one by one or all together through a yml pipeline with one PowerShell task. Working on the documentation at this time but the repo will be here: https://github.com/wvaneck/azure-api-management-devops-pipeline

**Comment by adrianhall** [comment]
There is an Azure Architecture paper on APIOps that covers this methodology.
