### ISSUE TITLE
Policy size exceeds allowed limit of 16 KB

### ISSUE THREAD

**Issue by Tyremt** [Azure/azure-api-management-devops-resource-kit#367]
Receiving a 'Policy size exceeds allowed limit of 16 KB' error for policy (consumption plan).

I cannot find any documentation that states there is a 16 KB limit on policies?

Can anyone confirm this is the case and whether its specific to a plan like consumption.

**Comment by bremnes** [comment]
Hi @Tyremt,

We encountered this error a while back in issue #159. Our solution was to configure the extractor to extract policies to their own files, which is then referenced from the ARM template. That has been working great for us so far.

Perhaps @miaojiang or @RupengLiu can weigh in on this, but my impression is that the 16KB limit of inline policy is a hard limit by either the ARM team or the APIM team.

**Comment by adrianhall** [comment]
This was the case when considering the API version.  We've recently updated the API version so that larger policies are available.  Unforutnately, if ARM or APIM doesn't allow it then we don't either.  It's not an issue with the DevOps Resource Kit at that point.
