### ISSUE TITLE
Azure DevOps Task Integration

### ISSUE THREAD

**Issue by jackj93** [Azure/azure-api-management-devops-resource-kit#368]
It would be nice if there was a Azure DevOps task that created these ARM templates from the yaml/policy files. This way we would not have keep 2 configuration files (both ARM and yaml) up to date.

Maybe the best thing to do here is to publish the tool as a NuGet package to allow us to install it as a dotnet cli tool.

Thanks,
Jack

**Comment by mm-gmbd** [comment]
Looks like there's an unofficial [ADO extension](https://marketplace.visualstudio.com/items?itemName=stephane-eyskens.apim) that is mentioned toward the bottom of the README.

Disclaimer: I haven't used it so I don't know how well it works (or how it addresses your desire to keep 1 config file - which is also my desire), but I'm planning on testing it soon :)
