### ISSUE TITLE
Is there no way to generate master template locally?

### ISSUE THREAD

**Issue by pmanthen** [Azure/azure-api-management-devops-resource-kit#369]
I am trying to use creator tool to generate ARM templates for one API, it generate a set of ARM templates. How would I import all of the together using a group deploy?

**Comment by rawrspace** [comment]
It looks like per the documentation on [Linked Templates](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/linked-templates#linked-template)

> When referencing a linked template, the value of uri must not be a local file or a file that is only available on your local network. You must provide a URI value that downloadable as http or https.

So this issue isn't with azure-api-management-devops-resource-kit not supporting it but rather with [azure-resource-management-schemas](https://github.com/Azure/azure-resource-manager-schemas) I expect.

**Comment by adrianhall** [comment]
You are correct - thanks for answering this question!
