### ISSUE TITLE
The SDK 'Microsoft.NET.Sdk' specified could not be found when "dotnet run extract..."

### ISSUE THREAD

**Issue by zhouchaoyuan** [Azure/azure-api-management-devops-resource-kit#370]
error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.

The build failed. Fix the build errors and run again.

**Comment by bremnes** [comment]
Hi @zhouchaoyuan!

This doesn't seem to be related to the extractor specifically, but instead your local environment or the build server.

I recommend you check out similar issues, like for instance microsoft/msbuild#2532. My guess would either be something with the .net core installation on the machine in question or msbuild issues.

There is not a lot of details here, so I'll close the issue and point you to the issue previously mentioned.
