### ISSUE TITLE
[Creator] Suggestion: embed all relevant information to create ARM template(s) in OpenAPI file

### ISSUE THREAD

**Issue by mm-gmbd** [Azure/azure-api-management-devops-resource-kit#373]
For an `APIConfiguration` as described in the [Creator README](https://github.com/Azure/azure-api-management-devops-resource-kit/blob/master/src/APIM_ARMTemplate/README.md#Creator), I think it makes sense to include all of the necessary information in [vendor extensions](https://swagger.io/docs/specification/openapi-extensions/) in the spec itself. (notice in the examples in the vendor extensions the fact that AWS API Gateway is already doing this...)

Developers don't want to have to manage their API spec and a bunch of other ancillary stuff if the service in question is all about hosting APIs (at least, this developer doesn't).

Thanks in advance for the consideration!

**Comment by ma499** [comment]
I think it's a good idea for those projects where it makes sense but I think it should still be possible to have the creator-config.yaml file separate. Some reasons why:

1. We may wish to have a different backend API URL based on environment and not want that sort of information polluting our Open API Specifications. See also #404.
1. I'm currently working on a project where we agree API specifications in a committee with other partners and then implement in each of our own systems. So the spec isn't ours and has a separate lifecycle to our applications.

**Comment by adrianhall** [comment]
If the APIM service allowed us to include the ancillary stuff in an OpenAPI spec, then that would be possible.  They currently don't, so we have to separate things out.  Sorry!
