### ISSUE TITLE
[Creator] Suggestion: option to output to git folder configuration

### ISSUE THREAD

**Issue by mm-gmbd** [Azure/azure-api-management-devops-resource-kit#374]
I tend toward management via Git vs. ARM templates given the option, and it turns out that APIM supports [git management](https://docs.microsoft.com/en-us/azure/api-management/api-management-configuration-repository-git). 

Feature suggestion that Creator supports ingestion of the necessary configuration files but spits out the required folder structure that can be deployed via git (instead of ARM templates).

One reason for this is that tracking changes to the git folder structure, to me, is easier to manage than changes to ARM templates.

**Comment by mm-gmbd** [comment]
Also, similar to https://github.com/Azure/azure-api-management-devops-resource-kit/issues/373, it would be great if Creator also supported vendor extensions in the OpenAPI spec(s) that represent all of the additional *things* necessary to represent an `APIConfiguration`.

**Comment by adrianhall** [comment]
Thanks for the feedback.  Since APIM is moving away from git configuration, we won't be doing this.
