### ISSUE TITLE
[Creator] Handle relative paths for config file references

### ISSUE THREAD

**Issue by xinyi-joffre** [Azure/azure-api-management-devops-resource-kit#376]
When I specify the local path for my OpenAPI yaml or policy xml file or the output folder, I currently need to provide absolute file (or relative path based on where the resource kit project is). This makes the config file hard to manage in a repo where multiple people have the resource kit "installed" in different locations.

Ideally, the Creator could handle relative paths from the location given for the config file itself. This way, I can use it in a folder structure, such as:

config.yaml
/openapis
  openapi.yaml
/output

And in my config.yaml, I can use relative paths such as ./openapis/openapi.yaml regardless of where the resource kit is on my system.

**Comment by SandGrainOne** [comment]
There is some support for relative paths, relative to the working directory when running the Creator. This should allow team members so have the tool installed in different locations.

**Comment by xinyi-joffre** [comment]
@SandGrainOne, do you mean it works for if you don't follow the current README instructions for executing the commands as dotnet run create, but rather "install" the tool by making it executable and adding it to your $PATH? In that case, all the commands would be "apimtemplate create" instead?

I was following the "dotnet run" instructions, and relative paths did not work for me. If the expected usage is to install the tool for Mac OS or windows, can we update the docs accordingly? For Mac OS, I had some issues getting the release binary to work out of the box. If there are specific instructions for getting the install to work, that would great!

**Comment by SandGrainOne** [comment]
Yes, you are correct. That is how I run the tool.

**Comment by springcomp** [comment]
I have included this #383 PR for exactly this purpose.

**Comment by springcomp** [comment]
The PR has now been merged.

**Comment by springcomp** [comment]
@RupengLiu I suggest this issue can be close.

**Comment by adrianhall** [comment]
Thanks for the PR @springcomp - closing the issue.
