### ISSUE TITLE
[Creator] Parameterize environment specific values

### ISSUE THREAD

**Issue by xinyi-joffre** [Azure/azure-api-management-devops-resource-kit#378]
Currently, the creator config file contains values which are environment specific (such as a backend url). It would make the arm templates simpler to use if the generated templates knew how to parameterize these values.

We could introduce a syntax such as [parameter('name', 'default_value')] into the config, and then set this accordingly in the templates.

This way, I can generate my templates as part of my CI process (and store the artifacts), and then my deployment can pass in the parameters in line.

**Comment by joeyeng** [comment]
Ditto for the extractor

**Comment by levimatheri** [comment]
Any updates on this?

**Comment by adrianhall** [comment]
We do parameterize a lot of things.  If there are specific things that are not handled in the 1.0.0 releases, please open an issue for each one.

Thank you.
