### ISSUE TITLE
Extractor template deployment fails with all API extraction

### ISSUE THREAD

**Issue by TravisLRiffle** [Azure/azure-api-management-devops-resource-kit#379]
First, I attempt to run a validation, the validation passes.  Then I attempt to do a resource group deployment as an incremental deploy.  When I do so (running the extractor against all APIs), I get the following error. In the past, I did not have issues with extracting and deploying individual APIs.  The only way I've found to get around this is to delete the APIM Gateway, recreate and then run the deployment.  Please advise.

`        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
        "details": [
          {
            "code": "BadRequest",
            "message": "{\r\n  \"error\": {\r\n    \"code\": \"ValidationError\",\r\n    \"message\": \"One or more fields contain incorrect values:\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"ValidationError\",\r\n        \"target\": \"name\",\r\n        \"message\": \"Property with the same name already exist.\"\r\n      }\r\n    ]\r\n  }\r\n}"
          }
        ]`

**Comment by romerve** [comment]
I've been extracting and deploying APIM templates for the last 2 weeks and have not had an issue around what you describe. Can you provide details around how you are deploying the templates?

Thanks

**Comment by TravisLRiffle** [comment]
Thanks for the follow up.  Here's what we found.  The named value pairs have problems, we think, with the unique ID that's created and moved between different APIM environments.  
We really don't need to move APIM named value pairs between environments, so we modified the code to skip Name Value pairs by adding a param to the .json file.  This fixed our issue.

**Comment by vishranti5** [comment]
@TravisLRiffle can you please elaborate the fix, currently i am also facing same issue and that too due to namedvalue template which contains some key. also, I want t create new instance of APIM using extracted values, so i updated parameter.json and assign new name to apimservice, my validation steps passes but in relese pipelines it throws same error.

**Comment by fortunkam** [comment]
I have run into the same issue on this, has the ARM type for namedValues changed?  The tool used to produce namedValues with a type of "Microsoft.ApiManagement/service/properties", if you look in the portal they are listed as "Microsoft.ApiManagement/service/namedValues"?  If I manually change the type then the deploy now works.

**Comment by fortunkam** [comment]
To add more context to the previous comment, if I create an ARM template to deploy a single named value (based on the template created by the extractor tool)

`
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "ApimServiceName": { "type": "string" }
    },
    "resources": [
        {
            "properties": {
                "tags": [],
                "secret": true,
                "displayName": "KVSecret3",
                "value": "This is a new secret"
            },
            "name": "[concat(parameters('ApimServiceName'), '/KVSecret3')]",
            "type": "Microsoft.ApiManagement/service/properties",
            "apiVersion": "2021-01-01-preview"
        }
    ]
}
`

deployed to an existing APIM using 
`
az deployment group create -n dep1 -g <resource_group> --template-file "namedvalueonly.json" --parameters ApimServiceName="apim"
`


I get 

```
Deployment failed. Correlation ID: 0107bd1a-399a-462c-bfa1-d9ad3e17c78e. {
  "error": {
    "code": "BadRequest",
    "message": ""
  }
}
```

If I change its type to  "Microsoft.ApiManagement/service/namedValues", it works.
This looks like the increased api version from fix #508 has broken named values, if I revert the api version back to 2019-01-01 then "Microsoft.ApiManagement/service/properties" works again.

**Comment by biancafrigerioMS** [comment]
Hello,

I have run into the same issue on this, has the ARM type for namedValues changed?

Do you have updates on when this issue will be resolved?

Thank you

**Comment by adrianhall** [comment]
As many of you surmised, the endpoint for named values in ARM changed.  This bug is, as a result, no longer valid.  The latest code base does extract named values correctly.
