### ISSUE TITLE
Reseting private ip and gateway configurations of APIM service

### ISSUE THREAD

**Issue by rajukumarbalibani** [Azure/azure-api-management-devops-resource-kit#380]
Hi All,

We configured a APIM service in Azure with private IP and Gateway configurations using terraform. 

We are using the templates provided in this forum to configure APIM and deploy API's using Azure Devops Pipelines. Templates taken from : .\azure-api-management-devops-resource-kit-master.zip\azure-api-management-devops-resource-kit-master\example

We categorized the templates and deploying API and APIM configuration Individually. 

API's are deploying successfully to APIM service via Azure Devops pipelines with few exceptions like revision description is not updating.

Using APIM templates I added two products, 1 user, 1 group, subscribed to 1 new product and configured AppInsights. All the changes updated to master templates, When I deploy the templates using Azure Devops pipeline, APIM changes are reflecting exactly **but it's removing the private IP and gateway settings in the APIM service.**

Can someone help me the cause of issue and solution. Let me know if you need more information.

Regards,
RajuKumar

**Comment by adrianhall** [comment]
This is a problem with the APIM ARM deployment, and not with DevOps Resource Kit.  As a result, we cannot assist in correcting this behavior.
