### ISSUE TITLE
[Extractor] serviceUrl and ApiLoggerId parameters are not added to the -apis.template when linkedTemplatesBaseUrl and includeAllRevisions are set

### ISSUE THREAD

**Issue by wvaneck** [Azure/azure-api-management-devops-resource-kit#392]
I found that when you have the following extract config settings (other settings are left out for clarity):
    "linkedTemplatesBaseUrl": "?",
    "includeAllRevisions": "true",
    "paramServiceUrl": "true",
    "paramApiLoggerId": "true"

That the *-apis.template.json file in the RevisionMasterFolder folder is missing the two parameters "serviceUrl" and "ApiLoggerId" while the template is actually referring to those two parameters.
The Master template conrectly specifies these two parameters.

The api templates in the revision folders do have these two parameters.

The api templates are also correct when you don't use the linkedTemplatesBaseURL setting but do have the includeAllRevisions set to true.

I have used the latest source code to find this issue.

**Comment by sergiopaim** [comment]
@wvaneck, does this PR fix part of it? https://github.com/Azure/azure-api-management-devops-resource-kit/pull/420

**Comment by rabrahamOpti** [comment]
@wvaneck @sergiopaim this PR fixes the `-apis.template.json` file. A separate PR will be needed to fix the `-parameters.json` file. See the comment in that PR for more info.

**Comment by rabrahamOpti** [comment]
https://github.com/Azure/azure-api-management-devops-resource-kit/pull/431 has been merged. Here's the comment about how `-parameters.json` still needs to be fixed:

Note, while this commit fixes the -`apis.template.json` file, the generated `-parameters.json` is still incorrect. To fix that, the code path starting here needs to be altered: https://github.com/Azure/azure-api-management-devops-resource-kit/blob/master/src/APIM_ARMTemplate/apimtemplate/Extractor/Utilities/ExtractorUtils.cs#L324 By passing in null for the singleApiName parameter, it creates a serviceUrl object that will have a serviceUrl field for each API in the tenant. Instead, the object needs to have a serviceUrl field for each revision of the API. 

This should be addressed in a separate PR

**Comment by adrianhall** [comment]
Sounds like this one has been fixed by #431 and #420.  If there are further issues here, please retest on the latest code base and open a new issue.  Thank you.
