### ISSUE TITLE
[Azure Build Pipeline] : Validation Step fails with Windows 2019 Agent

### ISSUE THREAD

**Issue by AvinandanPatra** [Azure/azure-api-management-devops-resource-kit#399]
Validation Step fails with Windows 2019 Agent in the Build Pipeline. 
Error : Location was not provided (even though the region being specified in the ARM Deployment).

If you switch to Windows 2017 Agent, works perfectly.

After some research it looks like Windows 2019 looks for latest 2019 (preview) schema based deployment templates.

**Comment by adrianhall** [comment]
Switched to new pipelines recently, so this is no longer valid.
