### ISSUE TITLE
Linked templates in Private Git Repo/Azure DevOps

### ISSUE THREAD

**Issue by siva-apim** [Azure/azure-api-management-devops-resource-kit#402]
Is it possible to access Linked templates from Private GIT Repo on Azure Devops, if yes - please advise on how to do the Authentication and Authorization with private GIT repo ? 

I have tried to provide Personal Access token but seems to be not working from ARM perspective but works from browser because I am already logged in to the Azure Devops Organization. 

Please provide inputs on how to achieve this and thanks in advance.

**Comment by tcukanoot** [comment]
You may have already figured this out by now, but we were not able to use the private repos. We ended up having to copy them to Azure blob storage to get it to work.
