### ISSUE TITLE
[Creator] Duplicate Operation tags across APIs 

### ISSUE THREAD

**Issue by glitchassassin** [Azure/azure-api-management-devops-resource-kit#403]
Hello!

I ran into an issue with tags on operations.

We are building two separate APIs, each with multiple operations. Some of the operations have the same tag, e.g. "documentation" for the endpoint that returns the OpenAPI reference documentation. The APIs themselves did not have tags.

When we deployed the generated template, Azure gave us an error "Tag with the same name already exists."

After some testing, I determined that the tags needed to be generated before the API was deployed. It looks like the API will automatically depend on the tags template if the API itself has tags, but not if the tags are only on operations.

Our current workaround is as follows:

1. Define all the tags in operations within our `creator.yml` config.
2. Assign a tag to each API, so it depends on the full tag template.

This may be a niche issue, but I thought I'd at least document here it in case someone else runs into it in the future!

**Comment by RupengLiu** [comment]
Triaged, we might also need to take tags on operations in the future into consideration.

**Comment by adrianhall** [comment]
Thank you for your input on the creator tool.  We are currently looking at the future of the creator tool and would like your feedback.  Please could you fill in the survey at https://forms.office.com/r/w7rQp88NwH - your input is appreciated.

**Comment by adrianhall** [comment]
This project is now in "maintenance" mode. This means that no new features will be accepted and fixes will be limited to security fixes. We expect to retire the DevOps Resource Kit by the end of 2023. At that time, the DevOps Resource Kit repository will be archived and there will be no further updates.

While you are free to fork the DevOps Resource Kit yourself, we recommend that you migrate to the following products:

* If you are using creator, switch over to using [Bicep](https://learn.microsoft.com/azure/azure-resource-manager/bicep/overview) templates. Bicep is a descriptive language for describing infrastructure, fully supports all features of Azure API Management, and is covered in any support agreement that you have with Azure. You can find bicep modules and examples for handling API Management APIs at https://github.com/azure-samples/api-management-sample-apis.
* If you are using extractor, switch your pipelines to use [APIOps](https://github.com/azure/apiops). APIOps applies the concepts of GitOps to API deployments. It is faster and more flexible than the DevOps Resource Kit.
