### ISSUE TITLE
[Creator] Suggestion: Support back-end (override) per operation

### ISSUE THREAD

**Issue by ma499** [Azure/azure-api-management-devops-resource-kit#404]
The Creator Tool at present only supports the concept of a single back-end for a given input OpenAPI specification. This means that we cannot, utilise the capability of Azure API Management to act as a router. 

In our use case we have a public API Spec that we are implementing with multiple microservices. We workaround the single back-end limitation by utilising a function app proxy as our API back-end. The proxy then performs onward routing to the actual microservice based on the path.

What I would like to see in the creator-config.yaml file is the ability to specify pattern matches for operation and path with a back-end to route to for that pattern. There should still be a default back-end. This would then mirror the routing capability that is actually available in Azure API Management.

**Comment by ma499** [comment]
No promises yet but we may be able to work on a PR to deliver this. Is it possible to have some feedback on the idea and, perhaps, some pointers on how to implement it?

**Comment by adrianhall** [comment]
The way to do this (with routing) is by editing the policy files, is it not?

In any case, this is beyond the scope of the creator tool.   Since there are other ways of doing this, I'm going to close this feature request.
