### ISSUE TITLE
API Version to 2019-12-01

### ISSUE THREAD

**Issue by seekjp** [Azure/azure-api-management-devops-resource-kit#410]
Do we need to change the below file to support the new API version in to 2019-12-01?
src/APIM_ARMTemplate/apimtemplate/Common/Constants/GlobalConstants.cs

**Comment by cayodiebe** [comment]
I dont understand, whats happening?

**Comment by hannesne** [comment]
There's a new version of the arm template schema available: https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json . The tool currently generates templates with version https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json 
When you open the template in vscode it prompts you to update the schema version of the template.

**Comment by cayodiebe** [comment]
It's works!

**Comment by RupengLiu** [comment]
@seekjp do you mean the API version for APIM team or the API version for arm templates?

**Comment by seekjp** [comment]
I am asking about using the latest version of the api of the APIM.
