### ISSUE TITLE
Support for APIM gateway configuration 

### ISSUE THREAD

**Issue by jonasnorlund** [Azure/azure-api-management-devops-resource-kit#411]
Hi, I'm missing support for APIM gateways in the creator yaml. 

I would have been nice to set the gateway tag in the yaml config.

**Comment by RupengLiu** [comment]
Sorry, if my understanding is correct, you want to make creator support setting gateway tags, right?

**Comment by jonasnorlund** [comment]
Yes that is correct, I can't find any information about it in the documentation.

**Comment by adrianhall** [comment]
@JonasNorlund - can you be more specific about the ask here?

**Comment by ayusmadi** [comment]
Hi @adrianhall, this is about making an API available and served by self-hosted gateways.

![image](https://user-images.githubusercontent.com/57968900/167343853-43cc8d53-a293-4b13-b82c-b2bf23975c16.png)

https://docs.microsoft.com/en-us/azure/api-management/self-hosted-gateway-overview

**Comment by adrianhall** [comment]
Thanks for that.  Due to the work being done on the creator, we won't get to this before the 1.0.0 release, but I've added it to the backlog.

**Comment by adrianhall** [comment]
Thank you for your input on the creator tool.  We are currently looking at the future of the creator tool and would like your feedback.  Please could you fill in the survey at https://forms.office.com/r/w7rQp88NwH - your input is appreciated.

**Comment by adrianhall** [comment]
This project is now in "maintenance" mode. This means that no new features will be accepted and fixes will be limited to security fixes. We expect to retire the DevOps Resource Kit by the end of 2023. At that time, the DevOps Resource Kit repository will be archived and there will be no further updates.

While you are free to fork the DevOps Resource Kit yourself, we recommend that you migrate to the following products:

* If you are using creator, switch over to using [Bicep](https://learn.microsoft.com/azure/azure-resource-manager/bicep/overview) templates. Bicep is a descriptive language for describing infrastructure, fully supports all features of Azure API Management, and is covered in any support agreement that you have with Azure. You can find bicep modules and examples for handling API Management APIs at https://github.com/azure-samples/api-management-sample-apis.
* If you are using extractor, switch your pipelines to use [APIOps](https://github.com/azure/apiops). APIOps applies the concepts of GitOps to API deployments. It is faster and more flexible than the DevOps Resource Kit.
