### ISSUE TITLE
Tags in API Operations not getting extracted

### ISSUE THREAD

**Issue by vibhukaushik** [Azure/azure-api-management-devops-resource-kit#412]
I am trying to extract and migrate operations tags but it is giving me error. Sometimes only few tags associated with the operations are getting extracted and some times none of them are getting extracted.

**Comment by RupengLiu** [comment]
Can you provide more details about the situation you have encountered? Ideally, we don't extract tags specially, and we get all tags that are in APIs/Operations and then generate tag template. From my understanding, you want to extract all tags and deploy them into the other apim instance, right?

**Comment by vibhukaushik** [comment]
Hi,
I am using option to extract multiple API's. In this, we get one Master folder in which templates contains info of all the API's together. And other than this, we get different folders for each API also. 

Now for the tags, we want to migrate tags which are used in that particular API only and not the tags which is coming in the Master Folder.

When  I am trying to deploy tags template, in particular API folder, I am getting errors as sometimes only few of the tags used are present in that template or in one case there was no template file for tags extracted.
