### ISSUE TITLE
While deploying new version of same API existing version is overwritten

### ISSUE THREAD

**Issue by charlievpaul** [Azure/azure-api-management-devops-resource-kit#414]
Current API version 4.x. While deploying a new version or evision, the existing version is overwritten

**Comment by SSanjeevi** [comment]
Hi @charlievpaul ,

You have to use same apiversionsetid for both apis as same, but the name value of the api version 1 and version 2 should be different. You can have display name as same for both apis and description. Just try this.

Basically the api name should be unique.

@RupengLiu please correct me if am wrong.

**Comment by charlievpaul** [comment]
It worked with different API name! Thanks Sanjeev
