### ISSUE TITLE
Extractor doesn't extract self hosted gateway APIs

### ISSUE THREAD

**Issue by davephelps** [Azure/azure-api-management-devops-resource-kit#416]
Extractor isn't extracting when an API is associated to a self hosted gateway , i.e., type:Microsoft.ApiManagement/service/gateways/apis

**Comment by RupengLiu** [comment]
this is currently not supported @miaojiang do we need to add this into our backlog

**Comment by miaojiang** [comment]
Seems to be a valid ask.

**Comment by DSpirit** [comment]
I've added the Gateways & Gateway APIs extraction here:
https://github.com/Azure/azure-api-management-devops-resource-kit/pull/586
