### ISSUE TITLE
.NET Tool name clashes with existing NuGet package

### ISSUE THREAD

**Issue by Strandfelt** [Azure/azure-api-management-devops-resource-kit#417]
In the description of how to use the Creator, it is suggested that you can use the tool as a dotnet tool by running:
```
dotnet pack -c Release
dotnet tool install -g --add-source .\bin\Release apimtemplate
```

However, one issue I just experienced with this is that the package name `apimtemplate` is [already in use on NuGet.org](https://www.nuget.org/packages/apimtemplate), meaning that unless you disable the default NuGet feed, you risk downloading this package instead of using the locally built copy, which will result in the following error, which was very misleading to me, until I finally figured out what was going on by studying the verbose logs:
```
NU1212: Invalid project-package combination for apimtemplate 1.0.0. DotnetToolReference project style can only contain references of the DotnetTool type
```

I would like to suggest that you select a new unique name for the package and release it to NuGet.org, such that the name is reserved.

**Comment by RupengLiu** [comment]
the nuget file of apimtemplate is released by the APIM team
