### ISSUE TITLE
Lot of docs missing

### ISSUE THREAD

**Issue by crgarcia12** [Azure/azure-api-management-devops-resource-kit#418]
There are a lot of docs missing about the extractor.

For example:

1. What is `destinationApimName`, why do i need it?
1 .How do I extract policies? In the video he provides some blob url. What is in there? Why is not just extracted?

It's really hard to use this just with the current docs / examples

**Comment by adrianhall** [comment]
We've beefed up the docs somewhat and have more to do.  Since this issue does not have a specific ask, I'll close it.  If you have a specific question or bug, please open a new issue with all required information.
