### ISSUE TITLE
API Display name is replacing with name from config file

### ISSUE THREAD

**Issue by saikiran-karumuri-by** [Azure/azure-api-management-devops-resource-kit#419]
While using the config file, devops kit source code is replacing API "display name" with "name". Because of this we cannot use actual OAS Spec API name as display name.

**Comment by adrianhall** [comment]
There is not enough information here to diagnose and reproduce the issue.  If this is still an issue for you, can you please open a new issue with all the requested information in the bug report.  Thank you.
