### ISSUE TITLE
Cannot revert to previous Revision 

### ISSUE THREAD

**Issue by aslesha96** [Azure/azure-api-management-devops-resource-kit#423]
I used creator tool to generate apis. I added first revision in the yaml file and deployed...Its worked. 
when I try to generate api with 2nd revision.. I cannot find the new revision in portal.azure.com. Because of that I cannot revert to previous revision also using the creator tool. 
A sample with 2 revisions will be very helpful

**Comment by leszekkoc** [comment]
Hi, any update on this?

**Comment by adrianhall** [comment]
There is not enough information on this bug report to reproduce the issue.  If this is still an issue for you, please open a new bug report and provide all the requested information.
