### ISSUE TITLE
How to mention URL scheme to both (http & https) in creator tool

### ISSUE THREAD

**Issue by SSanjeevi** [Azure/azure-api-management-devops-resource-kit#424]
How to mention URL scheme to both (http & https) in creator tool

![image](https://user-images.githubusercontent.com/24915474/89159184-ca09d080-d58c-11ea-8b0b-dd82bbe73239.png)

**Comment by RupengLiu** [comment]
you can specify the schema in the swagger file, creator tool itself doesn't support this
