### ISSUE TITLE
Checking release version of extractor tool

### ISSUE THREAD

**Issue by vibhukaushik** [Azure/azure-api-management-devops-resource-kit#425]
Hi Team,

Currently i have three project in which i am using extractor tool to extract API's from APIM.

Is there a way to check which release of Extractor tool i am using in those projects. As there are differences in features available in two projects. I tried looking for it but couldn't find it.

Thanks,
Vibhu Kaushik

**Comment by RupengLiu** [comment]
currently there is no way to check which release the extractor tool is
