### ISSUE TITLE
Extractor doesn't extract OpenID Connect Providers

### ISSUE THREAD

**Issue by gthibaud-wavestone** [Azure/azure-api-management-devops-resource-kit#426]
Hi Azure Team,

The extractor doesn't seem to extract OpenID connect providers. I looked into the source files and I didn't found anything about it. 
I temporarily fixed it by using the Service API (https://docs.microsoft.com/en-us/rest/api/apimanagement/2019-12-01/openidconnectprovider/listbyservice). Would it be possible to integrate it into the Extractor?

Thank you for your help!

Best regards,

Grégoire

**Comment by gthibaud** [comment]
Hi, could you give me an idea of when Milestone 0.7 will be implemented?

We have expectations in our company, but we can't use extraction yet because of the unsupported OpenID Connect providers.

Thank you!

Grégoire
