### ISSUE TITLE
Extractor arg 'linkedTemplatesSasToken' seems to have no effect

### ISSUE THREAD

**Issue by rabrahamOpti** [Azure/azure-api-management-devops-resource-kit#427]
I'm unable to see any difference in the output of the extractor for values I set the 'linkedTemplatesSasToken' Extractor argument to. 

It was introduced in this PR: https://github.com/Azure/azure-api-management-devops-resource-kit/pull/322/

Looking at `ExtractorUtils.cs`, it appears it's pulled into a local variable called `linkedSasToken`, but is never passed into any of the Generate* methods below: https://github.com/Azure/azure-api-management-devops-resource-kit/blob/master/src/APIM_ARMTemplate/apimtemplate/Extractor/Utilities/ExtractorUtils.cs#L61

@alan0609 @RupengLiu

**Comment by glitchassassin** [comment]
The value of that parameter seems to be correctly added to `[apim]-parameters.json` for me. See here:

https://github.com/Azure/azure-api-management-devops-resource-kit/blob/master/src/APIM_ARMTemplate/apimtemplate/Extractor/EntityExtractors/MasterTemplateExtractor.cs#L233

**Comment by glitchassassin** [comment]
Are you also passing the linkedTemplateBaseUrl argument?

**Comment by Robzilla** [comment]
Could some examples of how to create a linked template please be added to the doco? Also why is a remote URL required to generate a linked template? If API files can be generated using the local file system why can't linked templates be generated locally?

**Comment by glitchassassin** [comment]
When you deploy linked templates, they have to be hosted somewhere accessible by Azure. The base URL parameter specifies that location, so that when you run the template deployment, the links to the sub-templates are properly resolved.

If your location might vary, try putting in a placeholder value (e.g. 'TO_BE_DETERMINED'). This will be added to the generated parameters file, and you can override the parameter when you actually deploy

**Comment by Robzilla** [comment]
We don't need to do this for other ARM based resources. We can deploy linked ARM templates locally (no remote storage required) using Blueprints in json form. Any idea how I can use this strategy with ARM that in generated by the extractor tool?

**Comment by glitchassassin** [comment]
Microsoft's documentation specifies:

> When referencing a linked template, the value of uri must not be a local file or a file that is only available on your local network. You must provide a URI value that downloadable as http or https.

https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/linked-templates#linked-template

If you've found a workaround for this, I'd love to hear it, as this would greatly simplify our deployments.
