### ISSUE TITLE
How to have Policy XML for method level of an api

### ISSUE THREAD

**Issue by SSanjeevi** [Azure/azure-api-management-devops-resource-kit#437]
Is there a way to add policy at the method level of an api in this arm template generator for creator tool. Can see api level policy but not on method or Operation level.

**Comment by RupengLiu** [comment]
currently it's not supported

**Comment by outifaout** [comment]
@SSanjeevi did you find a workaround?

**Comment by SSanjeevi** [comment]
@outifaout  Yes I used api level policy with when condition with operation name filter.

**Comment by outifaout** [comment]
@SSanjeevi could you provide an example?

**Comment by SSanjeevi** [comment]
@outifaout - example is below:

```
<choose>

            <when condition="@(context.Operation.Name.Equals("myOperationName"))">

                -----Your policy here-------

            </when>

</choose>
```

Above policy i used at api level and i use the 'myOperationName' value with the operation for which i need to apply a policy.

**Comment by outifaout** [comment]
@SSanjeevi Thank you very much !
