### ISSUE TITLE
[Creator] Include Input Files used by Creator to generate api-httpbin example

### ISSUE THREAD

**Issue by tanmeijing** [Azure/azure-api-management-devops-resource-kit#439]
Hi, is it possible to include the Input files (swagger/open api file, policy xml files, and config yaml files) used to generate the different versions and revisions templates of the api-httpbin example demo?
https://github.com/Azure/azure-api-management-devops-resource-kit/tree/master/example/api-httpbin
I am able to run the api-httpbin version and revision templates successfully, but encountered issues for the ones generated from the petstore demo input via the Creator.

I referred to https://github.com/Azure/azure-api-management-devops-resource-kit/issues/179 on the steps required to create a new revision and flip it to be the current revision with the inputs from api pet store demo and and some of the issues I faced were:
- ValidationError encountered when running generated templates for revision 2.
```
ValidationError: Deployment failed. Correlation ID: 181f5f45-8d2d-4bff-9e7d-bbb1a3bc7da9. {
  "error": {
    "code": "ValidationError",
    "message": "Can't change property Description for non-current revision ",
    "details": null
  }
}
```
- `Microsoft.ApiManagement/service/apis/releases` in subsequent template is generated with wrong name `"[concat(parameters('ApimServiceName'), '/myAPI;rev=2/release-revision-')]"`. `myAPI;rev=2` should be `myAPI`, and `release-revision-` is an invalid name as it ends with a '-'

The files generated for revision 1 were successfully run.
For revision 2, I skipped the version set template and ran the initial api template and encountered ValidationError `Can't change property Description for non-current revision `.
The naming configuration for the APIConfiguration section was as followed.
```
apis:
  - name: myAPI;rev=2
    displayName: myAPI
```
The swaggerPetstore.json was not modified. The only other difference between revision 1 and 2 was adding an extra policy to one of the operations in `valid.yml`.

The main difference I see between the api-httpbin and petstore templates is that api-httpbin's template files have `Microsoft.ApiManagement/service/apis/operations` resources to generate the operations, whereas there are none in the generated petstore template file and a swagger inline value under the properties of the `Microsoft.ApiManagement/service/apis` resource is used to generate the operations instead.
This should not be a problem on its own, but I encountered the ValidationError `Can't change property Description for non-current revision ` when running the revision 2 initial api template.
I suspect it may be related to this bug https://github.com/Azure/azure-powershell/issues/9270. 
I am not sure what validation goes on for the swagger file, but it shouldn't be happening either as I did not modify swaggerPetstore.json.

Attached are the Input files used. They come from https://github.com/Azure/azure-api-management-devops-resource-kit/tree/master/example/demo/Input and only valid.yml is modified.
Are there any misconfigurations or steps that I may have missed? Thanks.
[Inputs.zip](https://github.com/Azure/azure-api-management-devops-resource-kit/files/5414210/Inputs.zip)

**Comment by lurumad** [comment]
Hi,

Same problem for me. When I try to create a new version (v2) current version (v1) disappear from API Management:

![image](https://user-images.githubusercontent.com/1729519/103086157-288b2600-45e4-11eb-87a6-ea218b3a2aea.png)

Can you share with us the api-httpbin example demo files?

Regards!

**Comment by clouddna-au** [comment]
Any update on this, as we do require the input yaml file to see how the output was generated please?

**Comment by adrianhall** [comment]
Since this is now a year old, we are closing this.  It seems there might be a bug here, but it's obscured by the ask, so if this is still an issue being encountered, please open a bug report.
