### ISSUE TITLE
Does the extractor tool extract the service templates

### ISSUE THREAD

**Issue by ahmedsza** [Azure/azure-api-management-devops-resource-kit#440]
In the video @miaojiang  makes reference to a service template that contains info like tier, instance count, domain etc. is this template created by the extractor tool. What would be the recommended guidance if I wanted to implement these kind of settings for my environment. eg let's say I want to automate the setup of domains etc

**Comment by miaojiang** [comment]
The service template was not created by the extractor. Both the extractor and the creator were designed to simplify the creation of templates for APIs.
