### ISSUE TITLE
Extractor Generating NameValue Template even when not used in an API

### ISSUE THREAD

**Issue by gaurav-p-sood** [Azure/azure-api-management-devops-resource-kit#443]
Hi 

while using the extractor , it is generating the Named value template as well under the split API folder for each API , irrespective of the fact , if a named value is used in that api or not. Below is my JSON for settings.

`
{
	"sourceApimName": "APIM-DEV",
	"destinationApimName": "APIM-TEST",
	"resourceGroup": "APIM-DEV",
	"fileFolder": "..\\..\\..\\..\\allapis",
	"linked": "true",
	"linkedTemplatesBaseUrl": "https://xxx.blob.core.windows.net/apimci/allapis",
	"policyXMLBaseUrl": "https://xxx.blob.core.windows.net/apimci/allapis/policies",
	"splitAPIs": "true",
	"storage": "true",
	"paramNamedValue": "true",
	"paramApiLoggerId": "true",
	"baseFileName": "BizTalkersAPIM-DEV",
	"paramServiceUrl": "true"
}`

And when this is deployed , it will by default deploy all the named value pairs, which seems redundant on incremental mode. 

Regards
Gaurav

**Comment by RupengLiu** [comment]
Currently, we can't make splitAPIs or so to to share one single namedvalue template, since some customers only want to deploy one API, and want the named values to be included. On the other side, we will provide a new option to not include namedValue template
