### ISSUE TITLE
Extractor tool is broken. Can't find the API even though it's on source APIM instance

### ISSUE THREAD

**Issue by surabhi-gupta-jll** [Azure/azure-api-management-devops-resource-kit#444]
Extractor tool command line and extract option in VS code is not working. No detailed message is given. I checked in fiddler and API call is getting 400 back. seems like an issue with api-version 2019-01-01. While on MS docs, the supported version is 2019-12-01. 

Can you please take a look?

**Comment by miaojiang** [comment]
Could you please provide steps to reproduce? 

cc @RupengLiu

**Comment by eiriksanderfjeld** [comment]
```
Connecting to av-services-dev API Management Service on services-dev Resource Group ...
Executing full extraction ...
Error occured: Response status code does not indicate success: 404 (Not Found).
Response status code does not indicate success: 404 (Not Found).
```
Extractor tool is failing for me as well. Just cloned it, built it, and trying to run it. I am running with these parameters: `--sourceApimName services-dev --resourceGroup services-dev --fileFolder d:\temp\apim-extract --destinationApimName apimtest-dev`

**Comment by eiriksanderfjeld** [comment]
Ah, i am sorry. It was a gross incompetence on my part, typo in resourceGroup. Perhaps the error should include the actual error message. `{"error":{"code":"ResourceGroupNotFound","message":"Resource group 'services-dev-rggg' could not be found."}}`

**Comment by RupengLiu** [comment]
@surabhi-gupta-jll, I can't repro from my side, can you provide detailed steps

**Comment by surabhi-gupta-jll** [comment]
I was able to solve the issue. Thank you.

Surabhi Gupta
T +1 630 282 8848
M +1 847 208 7674
