### ISSUE TITLE
Key Vault Secrets in plain text

### ISSUE THREAD

**Issue by leszekkoc** [Azure/azure-api-management-devops-resource-kit#449]
When downloading template from portal the secrests are in plain text:
```
{
            "type": "Microsoft.ApiManagement/service/properties",
            "apiVersion": "2019-01-01",
            "name": "[concat(parameters('apim_name'), '/sfgsdgf')]",
            "dependsOn": [
                "[resourceId('Microsoft.ApiManagement/service', parameters('apim_name'))]"
            ],
            "properties": {
                "displayName": "sfgsdgfsdgf",
                "value": "896f9234-ABCD-4321-1234-acac835667e6",
                "tags": [],
                "secret": true
            }
        },
```

**Comment by lmrisdal** [comment]
We also noticed this while trying to automate our API releases. This really needs a fix or workaround.

**Comment by RupengLiu** [comment]
Hi @leszekkoc , what would be a better a approach to make secrets not in plain text?

**Comment by leszekkoc** [comment]
Hi @RupengLiu, Do not show secrets on export.
1) do not export ```value``` property or
2) export like: ```"value": "******",```

**Comment by GRichards05** [comment]
Was able to speak to Microsoft's Mike Budzynski the other day about this, he suggested that it was due to using an out of date API, not sure if this is valid or not.

**Comment by GRichards05** [comment]
Looks like the preview version of the API has a fix for this; 
https://docs.microsoft.com/en-us/rest/api/apimanagement/2020-06-01-preview/namedvalue/get#apimanagementgetnamedvaluewithkeyvault

**Comment by miaojiang** [comment]
Switching to latest version of API might solve this issue. @RupengLiu

**Comment by miaojiang** [comment]
Also, maybe we should change the logic to not extract Named Values that are marked as secret.

**Comment by sagar-codit** [comment]
Does not create arm template for the key-vault based named-values, fix?

**Comment by fortunkam** [comment]
Could it not provide a config option to parameterise the secret named values?  (off by default and only works if paramNamedValue set to true)

**Comment by adrianhall** [comment]
Looping back - the latest 1.0.0-beta.2 release uses the 2021-08-01 API.  If this issue is still a problem, please open a new issue and provide all the required information.
