### ISSUE TITLE
Using extractor to link all API's and not one massive api template

### ISSUE THREAD

**Issue by trepps** [Azure/azure-api-management-devops-resource-kit#452]
I am using the extractor and I set splitapi's to true. Works as expected. I have a subfolder for each API. Problem is that the apis.template.json is huge and running into size limitations for deployment. Is there a way for this template to point to the master templates in each API folder?

**Comment by naylinkolin** [comment]
naylinko uhiso သည် Gmailလျှို့ဝှက်မုဒ် ဖြင့် အီးမေးလ်တစ်စောင် ပို့ထားသည်−

[image: Gmail သင်္ကေတ] <https://confidential-mail.google.com/msg/AJd0jO0D1phiQJVhtWLPEoAVHLefEj1gYGX_BGWTeO0jOAuSc1SMDCq_iNWY76NqZYZDPg6ar3GiZPHoQiG1-Spj7D0BQt_zQR7opbV7bu0bi4F5swYayz9apAzdLg8E9T5ZGfc-tQUmQdGbetH73UfoYRwA4Q5T706URwQj9un7k-8-44-Ru8HIeRAzqUwsG2JGXFx1I1Hlul5Nh-4=>

ဤမက်ဆေ့ဂျ်ကို ၂၀၂၁၊ ဖေ ၂ GMT-၈ ၀၃:၄၁:၀၄ တွင် ပို့ထားသည်
အောက်တွင်ရှိသည့် လင့်ခ်ကို နှိပ်၍ ၎င်းကို ဖွင့်နိုင်သည်။ ဤလင့်ခ်ကို reply@reply.github.com အတွက်သာ သုံးနိုင်မည်။

အီးမေးလ်ကို ကြည့်ရန် <https://confidential-mail.google.com/msg/AJd0jO0D1phiQJVhtWLPEoAVHLefEj1gYGX_BGWTeO0jOAuSc1SMDCq_iNWY76NqZYZDPg6ar3GiZPHoQiG1-Spj7D0BQt_zQR7opbV7bu0bi4F5swYayz9apAzdLg8E9T5ZGfc-tQUmQdGbetH73UfoYRwA4Q5T706URwQj9un7k-8-44-Ru8HIeRAzqUwsG2JGXFx1I1Hlul5Nh-4=>

Gmail လျှို့ဝှက်မုဒ်သည် သင်ပို့လိုက်သည့် မက်ဆေ့ဂျ်များကို ပို၍ထိန်းချုပ်ခွင့်ပေးပါသည်။ ပို့သူသည် သက်တမ်းကုန်ချိန်တစ်ခု သတ်မှတ်ရန်၊ ပုံနှိပ်ခြင်း သို့မဟုတ် ဆက်ပို့ခြင်းကို ပိတ်ထားရန် သို့မဟုတ် ဤမက်ဆေ့ဂျ်ကို အသုံးပြုမှုအား လိုက်ကြည့်ရန် ရွေးချယ်နိုင်သည်။ ပိုမိုလေ့လာရန် <https://support.google.com/mail/answer/7674059>
Gmail− Google ၏ အီးမေးလ်
အသုံးပြုမှုသည် Google ပုဂ္ဂိုလ်ရေးဆိုင်ရာ မူဝါဒ <https://myaccount.google.com/privacypolicy?hl=my> အရဖြစ်ပါသည်
Google LLC, 1600 Amphitheatre Parkway, Mountain View, CA 94043, USA
တစ်စုံတစ်ယောက်သည် Gmail လျှို့ဝှက်မုဒ် မှတစ်ဆင့် အီးမေးလ်တစ်စောင်ပို့ထားသောကြောင့် ဤမက်ဆေ့ဂျ်ကို သင်လက်ခံရရှိခြင်းဖြစ်သည်။
[image: Google သင်္ကေတ]

**Comment by adrianhall** [comment]
Not at this time.  We are looking at future work to enable "per-API" deployments in other places, so it won't be handled by the DevOps Resource Kit either
