### ISSUE TITLE
[Kit] does not support revisions

### ISSUE THREAD

**Issue by leszekkoc** [Azure/azure-api-management-devops-resource-kit#454]
[Extract]
Tool does not extract revisoin rev=2 that is online:
![image](https://user-images.githubusercontent.com/16720623/106571682-bd643600-6537-11eb-867e-76724c4370fc.png)

[Deploy]
I deploy api v1, that is current:
```
  "name": ".../v1"
  "apiRevision": "1",
  "apiVersion": "v1",
  "isCurrent": true,
```

Then I want to deploy new revision toogether with the current one:

```
  "name": ".../v1"
  "apiRevision": "1",
  "apiVersion": "v1",
  "isCurrent": true,
```
and 
```
  "name": ".../v1;rev=2"
  "apiRevision": "2",
  "apiVersion": "v1",
  "isCurrent": false
  "dependsOn":[ /v1 ]
```
With error:
```
 "error": {
    "code": "ValidationError",
   "message": "Can't change property Name for non-current revision ",
    "details": null
  }
```

**Comment by miaojiang** [comment]
I believe we only extract current revision. @RupengLiu to confirm.

**Comment by adrianhall** [comment]
For extractor, I'm going to mark this as a feature as we only support extracting the latest revision right now.  Requirement is "add an option to extract all revisions with a mechanism that allows them all to be imported again somewhere else".

**Comment by adrianhall** [comment]
@springcomp - if you wish this for creator as well, please open a new feature request as it is a different code base.

**Comment by adrianhall** [comment]
This project is now in "maintenance" mode. This means that no new features will be accepted and fixes will be limited to security fixes. We expect to retire the DevOps Resource Kit by the end of 2023. At that time, the DevOps Resource Kit repository will be archived and there will be no further updates.

While you are free to fork the DevOps Resource Kit yourself, we recommend that you migrate to the following products:

* If you are using creator, switch over to using [Bicep](https://learn.microsoft.com/azure/azure-resource-manager/bicep/overview) templates. Bicep is a descriptive language for describing infrastructure, fully supports all features of Azure API Management, and is covered in any support agreement that you have with Azure. You can find bicep modules and examples for handling API Management APIs at https://github.com/azure-samples/api-management-sample-apis.
* If you are using extractor, switch your pipelines to use [APIOps](https://github.com/azure/apiops). APIOps applies the concepts of GitOps to API deployments. It is faster and more flexible than the DevOps Resource Kit.
