### ISSUE TITLE
Allow NamedValuesExtractor to pull more than 100 named values

### ISSUE THREAD

**Issue by gthibaud** [Azure/azure-api-management-devops-resource-kit#456]
Allow NamedValuesExtractor to pull more than 100 backends.
Based on #359 and #446 

Thank you!

**Comment by DSpirit** [comment]
@RupengLiu you might have a look at my PR linked here, I've added functionality as given in the APIExtractor.

**Comment by adrianhall** [comment]
Catching up - this may already be done, so let's validate.
