### ISSUE TITLE
Allow backendURL parametrization for the backend entity

### ISSUE THREAD

**Issue by DSpirit** [Azure/azure-api-management-devops-resource-kit#460]
When deploying backends, currently it's not possible to use parameterized URLs. Usually, each environment has its own backend URL which would get overwritten by deploying the backend.

**Comment by RupengLiu** [comment]
do you mean ParamServiceUrl in extractor, or a similar one in creator tool?

**Comment by kkuchcinski** [comment]
I believe this is for backends.template.json where resourceID and url values are stored directly in the template. It should be rather parameterized per environment (dev/prod).
![backend](https://user-images.githubusercontent.com/41543565/109504783-38b7f980-7a9c-11eb-92ce-74e3a4c91a19.jpg)

**Comment by adrianhall** [comment]
Seems like this is fixed.  If it isn't, please add a new issue with the required information.
