### ISSUE TITLE
Document for product subscription has been removed by recent commit

### ISSUE THREAD

**Issue by springcomp** [Azure/azure-api-management-devops-resource-kit#461]
_Pull Request_ #453 has been completed a few weeks ago and has the `Creator` tool support product subscriptions in Azure API Management. Unfortunately, it seems the latest commit merge into master removed part of the documentation for this feature.

@SSanjeevi, @odaibert, @RupengLiu  was this a mistake ? Is there any way I can help at all ?

**Comment by springcomp** [comment]
This is the [offending commit](https://github.com/Azure/azure-api-management-devops-resource-kit/commit/470ad26fcd530f1da5b0df935c01c46286652143)

**Comment by SSanjeevi** [comment]
Apologies if my merge removed it, let me check.

**Comment by RupengLiu** [comment]
document added
