### ISSUE TITLE
Extractor tool fails if API does not contain a tag

### ISSUE THREAD

**Issue by fortunkam** [Azure/azure-api-management-devops-resource-kit#466]
Steps to reproduce: 
Create a new APIM instance
(Make sure the default Echo API is present and contains no tags on the API or Operation)
Run the extractor tool with the following optional parameters.

"linkedTemplatesBaseUrl" : "SomeValue",
"linkedTemplatesUrlQueryString" : "SomeValue",
"linkedTemplatesSasToken" : "SomeValue",
"PolicyXMLBaseUrl" : "SomeValue",
"splitAPIs": "false",
"paramNamedValue" : "true"

The tool throws..
System.InvalidOperationException
  HResult=0x80131509
  Message=Sequence contains no elements
  Source=System.Linq
  StackTrace:
   at System.Linq.ThrowHelper.ThrowNoElementsException()

tracing this back to line 158 in the TagAPIExtractor.
string[] lastTagName = templateResources.Last().name.Replace("')]", "").Split('/');

if templateResources is empty then the call to Last() will fail

**Comment by travich** [comment]
I have the same error
