### ISSUE TITLE
[ARM] Deploying Many Operations Stalls after 60 seconds and causes Status Errors

### ISSUE THREAD

**Issue by aevans-eml** [Azure/azure-api-management-devops-resource-kit#470]
I'd like to find out if this is a common problem or if I'm doing something wrong.  Searching for it turned up nothing.
I have an API that I extracted with about 85 operations.  When I deploy the ARM template it chugs along, making good progress for 60 seconds.  It gets maybe 20 operations deployed in that time. After that, progress slows to a crawl and it takes another two hours to deploy the rest of the operations. The deployment of the operations looks like the following image.  I searched for the "ServerClosedRequest" message but couldn't find anything.  It almost seems like status requests are sent off for all 85 operations simultaneously and after 60 seconds some of them time out.
![image](https://user-images.githubusercontent.com/20228298/111336118-f0bfd780-8642-11eb-965f-d527afa2ecf1.png)
And my deployment script that checks progress just shows this
![image](https://user-images.githubusercontent.com/20228298/111336215-0503d480-8643-11eb-96a6-73a5e8344cad.png)
Is this a common issue?  I don't think I'm doing anything unusual, just using the extracted template.  There seem to be people with far more operations in their APIs.
Is there any way to make my deployment faster?

EDIT
I tried running the template from the portal rather than a script.  It has the same problem but the error message is now throwing a 429.  What is the limit?
![image](https://user-images.githubusercontent.com/20228298/111351466-32577f00-8651-11eb-942d-233e3c324eb2.png)

EDIT 2
I found this
https://feedback.azure.com/forums/281804-azure-resource-manager/suggestions/41534377-option-to-throttle-deployment-rate-of-arm-template

**Comment by miaojiang** [comment]
@solankisamir could you take a look and comment?

**Comment by adrianhall** [comment]
This is an APIM + ARM issue, and not an issue with the DevOps Resource Kit.  Closing.
