### ISSUE TITLE
VSCode API Management Extension - "Extract Service/API" vs Extractor

### ISSUE THREAD

**Issue by zojovano** [Azure/azure-api-management-devops-resource-kit#477]
Could someone please comment on the "Extract Service" and "Extract API" features of the API Management VSCode extension https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-apimanagement vs "Extractor" tool? Are the features in any way comparable? 
Would you see VSExtension "Extract" features complementary to the Kit's "Extractor" tool or as an alternative?

**Comment by miaojiang** [comment]
VSCode simplify uses the resource kit.

**Comment by zojovano** [comment]
Thanks.
I believe that current version in the VSCode does extract the API Management service itself, am I right?
According to this case (https://github.com/Azure/azure-api-management-devops-resource-kit/issues/458) this is not possible in the Kit (at least not anymore). I am assuming that VSCode is then using older version (when it was supported) or they have some fork of the Kit with this feature still available?
Can you please clarify?
