### ISSUE TITLE
The 'Search-AzGraph' command was found in the module 'Az.ResourceGraph', but the module could not be loaded.

### ISSUE THREAD

**Issue by vibhukaushik** [Azure/azure-api-management-devops-resource-kit#480]
Hi,

I have a Azure Devops release pipeline which was working up until recently. But now it has started giving me below error: -

"The 'Search-AzGraph' command was found in the module 'Az.ResourceGraph', but the module could not be loaded. For more information, run 'Import-Module Az.ResourceGraph'."

My powershell is running on version 3.1.0.

My code has first line as: -
Install-Module -Name Az.ResourceGraph -Scope CurrentUser -Force

NOTE:- It was working fine.

Can someone help on this?

**Comment by vibhukaushik** [comment]
Full code which i am using is as below: -

Install-Module -Name Az.ResourceGraph -Scope CurrentUser -Force

$UserName = $env:UserName
$EmailId = $env:EmailId
$RequestId = $env:RequestId
$PublicIP = $env:PublicIP
$Hostname = $env:HostName

 

$PIPOUT = Search-AzGraph -Query "Resources | where type contains 'publicIPAddresses' and properties.ipAddress == '$PublicIP' | project subscriptionId, location, resourceGroup, name, properties.ipAddress, properties.publicIPAllocationMethod, properties.dnsSettings.fqdn | sort by subscriptionId, location, resourceGroup, name"

**Comment by miaojiang** [comment]
Doesn't look like the question is related to the resource kit in this repository.
