### ISSUE TITLE
[Creator] Parameterized serviceUrl is with Type Object

### ISSUE THREAD

**Issue by devgodman** [Azure/azure-api-management-devops-resource-kit#485]
In APITemplateCreator,  
if (String.IsNullOrEmpty(api.serviceUrl))
{
   apiTemplate.parameters.Add(ParameterNames.ServiceUrl, new TemplateParameterProperties() { type = "object" });
}
It shows that service URL can be parametized for different environments. However, the type is set object instead of string. 
What value should be passed?

**Comment by devgodman** [comment]
I change the type to "string" and the creator works fine.

**Comment by levimatheri** [comment]
Yeah, why is the `serviceUrl` an object instead of a string?

**Comment by majorvin** [comment]
Im not sure if this feature covered making serviceURL as parameters. e.g. (when using demo) initial and subsequent .json files hardcoding the serviceUrls but it can/should retrieve it from parameters('serviceUrl')

**Comment by adrianhall** [comment]
Duplicate of #577
