### ISSUE TITLE
[Creator] Can add an option to generate nested template?

### ISSUE THREAD

**Issue by devgodman** [Azure/azure-api-management-devops-resource-kit#489]
The creator now can only generate linked template or multiple templates. However, linked template relies on a publicly accessible repository, e.g. github or blob storage. 
Can a new option be provided to generate nested template too?

**Comment by adrianhall** [comment]
We'll take a look at this after the 1.0.0-GA release.  I don't have a timeline for that right now, but we are doing regular releases with that in mind.

**Comment by bjorkstromm** [comment]
@adrianhall I created support for this today in my own fork. Happy to send a PR once I tidy it up and add some tests.
https://github.com/bjorkstromm/azure-api-management-devops-resource-kit/tree/feature/improvements

**Comment by adrianhall** [comment]
We are going to be re-factoring the creator in the same way that we've done the extractor before the 1.0.0-GA.  I am sure we will love to take the PR once we have done the re-factoring, but it's likely to need re-writing if you do it now.

**Comment by adrianhall** [comment]
Thank you for your input on the creator tool.  We are currently looking at the future of the creator tool and would like your feedback.  Please could you fill in the survey at https://forms.office.com/r/w7rQp88NwH - your input is appreciated.

**Comment by adrianhall** [comment]
This project is now in "maintenance" mode. This means that no new features will be accepted and fixes will be limited to security fixes. We expect to retire the DevOps Resource Kit by the end of 2023. At that time, the DevOps Resource Kit repository will be archived and there will be no further updates.

While you are free to fork the DevOps Resource Kit yourself, we recommend that you migrate to the following products:

* If you are using creator, switch over to using [Bicep](https://learn.microsoft.com/azure/azure-resource-manager/bicep/overview) templates. Bicep is a descriptive language for describing infrastructure, fully supports all features of Azure API Management, and is covered in any support agreement that you have with Azure. You can find bicep modules and examples for handling API Management APIs at https://github.com/azure-samples/api-management-sample-apis.
* If you are using extractor, switch your pipelines to use [APIOps](https://github.com/azure/apiops). APIOps applies the concepts of GitOps to API deployments. It is faster and more flexible than the DevOps Resource Kit.
