### ISSUE TITLE
Using multipleAPIs in the extractor settings extracts all Named Value Pairs

### ISSUE THREAD

**Issue by gaurav-p-sood** [Azure/azure-api-management-devops-resource-kit#494]
Hi 

While using the setting multipleAPIs in the extractor settings.json , the extractor tool pulls all the a Named value pairs which shouldnt be the case and must extract only the Named value pairs specific to the API. 

I believe that is the also the case when one specific API is extracted. 

Please advice 

Regards
Gaurav

**Comment by adrianhall** [comment]
Duplicate of #151
