### ISSUE TITLE
Extractor output missing some resources

### ISSUE THREAD

**Issue by ppandari** [Azure/azure-api-management-devops-resource-kit#496]
Extractor output was missing
- API Instance creation resource. This would be needed for creating a new APIM instance .
-  users and groups
Are there any additional parameters that needs to be set for extracting these details ?

**Comment by adrianhall** [comment]
Hi @ppandari - we've just released a new version (in beta) that includes groups and the instance creation has been there for a while (although it may not be complete).

Can you please take a look and see if it meets your needs.  If it doesn't, please file a new bug stating what is missing.  It's preferred that you file a separate issue for each resource that is missing for you.

Thanks,
