### ISSUE TITLE
"paramServiceUrl":"true" adds serviceUrl to productAPIs.template.json but never passes it

### ISSUE THREAD

**Issue by waelkdouh** [Azure/azure-api-management-devops-resource-kit#505]
"paramServiceUrl":"true" adds serviceUrl to productAPIs.template.json but never passes it from the master template which causes the template validation to fail during deployment. This seems like a bug.

**Comment by nahojs** [comment]
I have similar issue. ServiceUrl is not created in the Api-parameter file. I manually commented out that creation-part and now it works as expected.

**Comment by esimkowitz** [comment]
I have the same issue with the new release

**Comment by adrianhall** [comment]
Dupe of #577 so closing this one.
