### ISSUE TITLE
Issue deploying APIs revisions using ARM templates

### ISSUE THREAD

**Issue by fmerinop** [Azure/azure-api-management-devops-resource-kit#506]
Hi @ll,   

There is an issue with APIM that we are experiencing for a time and that we tackling with a manual workaround.

We are performing deployments between instances using the azure APIM resource kit, extracting APIs configuration, and deploying them in the following system with the ARM templates generated with the extractor tool.

However, when started having APIs revisions we have realized there is a limitation, or we have not found the way in any of the available documentation, that only allow us deploying revisions in the target system into the active revision.

This means that for being able to deploy a new revision we need, first creating the revision in the target system, them make it current and only then deploying the new API revision configuration. The consequence of this is that while performing new API revisions deployments in the target system there is a period on which the API former active revision is not active and the new one is not yet updated, that can cause service disruptions. In addition, we do not have the possibility of publishing a new revision in inactive mode, which would be the best for avoiding this issue and to decide, after deployment of the new revision is completed, when to activate the new revision.

Many thanks

**Comment by nahojs** [comment]
Seems the Yaml parser is not working properly. Fields regarding revisions are all null when debuging (conversion from json-string to object). As result the current revision in Apim will be updated.

**Comment by adrianhall** [comment]
Unfortunately, this is a problem with ARM deployments and not with the DevOps Resource Kit.  As such, we can't correct this behavior.
