### ISSUE TITLE
Extractor does not create ARM templates allowing for both policyXMLBaseUrl  AND policyXMLSasToken

### ISSUE THREAD

**Issue by HPatArla** [Azure/azure-api-management-devops-resource-kit#510]
When the extractor has run the parameter.json, globalServicePolicy.template.json, api.template.json and mater.template.json file only contains the the policyXMLBaseUrl  but NOT the policyXMLSasToken. This means we cannot create CI/CD pipeline for the policy templates that is in a blob with SaSToken. Now the blob has to be public. 

We are using Visual Studio Code + the Azure API management extension to extract the ARM templates.

Here an example of the Parameter file:
{
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "ApimServiceName": {
      "value": ""
    },
    "LinkedTemplatesBaseUrl": {
      "value": ""
    },
    "LinkedTemplatesUrlQueryString": {
      "value": ""
    },
    "PolicyXMLBaseUrl": {
      "value": ""
    }
  },
  "resources": []
}

And here the globalServicePolicy.template.jason with PolicyXMLBaseUrl but are missing the the policyXMLSasToken parameter
{
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "ApimServiceName": {
      "type": "string"
    },
    "PolicyXMLBaseUrl": {
      "type": "string"
    }
  },
  "resources": [
    {
      "properties": {
        "value": "[concat(parameters('PolicyXMLBaseUrl'), '/globalServicePolicy.xml')]",
        "format": "rawxml-link"
      },
      "name": "[concat(parameters('ApimServiceName'), '/policy')]",
      "type": "Microsoft.ApiManagement/service/policies",
      "apiVersion": "2019-01-01"
    }
  ]
}

**Comment by HPatArla** [comment]
@miaojiang for your information - its only when the extractor tool is called from visual code the policyXMLSasToken is missing - when using the extractor from commandline it now contains the token

**Comment by seenu433** [comment]
This still seems to be the behavior for the templates extracted using the vs code extension. This is blocking the devops pipelines as the policy xmls could not be downloaded without any SAS token

**Comment by HPatArla** [comment]
@miaojiang Any news on progress?

**Comment by RupengLiu** [comment]
@HPatArla, okay I think the main reason is that VScode uses the very old version of devops reskit, I will update the version that is using this...

**Comment by HPatArla** [comment]
@RupengLiu Thanks - let me know when I can download and test again :-)

**Comment by DeagleGross** [comment]
Hello @HPatArla, we have fixed that in [vscode-apimanagement](https://github.com/microsoft/vscode-apimanagement/pull/233) repository. Thanks for cooperation and sorry for delayed fix.

We will close this issue once vscode extension will be released.

**Comment by DeagleGross** [comment]
Will be released with the vscode-apimanagement, so closing the issue due to internal agreements on issue statuses
