### ISSUE TITLE
The extractor tool needs to support both application insights and backends parametrization

### ISSUE THREAD

**Issue by waelkdouh** [Azure/azure-api-management-devops-resource-kit#513]
The extractor tool needs to support both application insights and backends parametrization. Right now I am having to write powershell scripts to override hardcoded information.

**Comment by draco961** [comment]
Would be really nice, here is the script for those who can't wait like me :-)

`$workingDirectoryPath = "C:\Repo\Temp\azure-api-management-devops\apim-extract"
$apimSourceName = "apim-dev"

$extractFolderName = "mySuperApi"
$extractFolderPath = $workingDirectoryPath + "\" + $extractFolderName
$extractParameterFilePath = $extractFolderPath + "\" + $apimSourceName + "-parameters.json"
$extractConfigFilePath = $workingDirectoryPath + "\extractSettings.json"

dotnet run extract --extractorConfig $extractConfigFilePath

$parameterFile = Get-Content $extractParameterFilePath -raw | ConvertFrom-Json
$parameterFile.parameters.BackendSettings.value.backendname.resourceId = "Resource id you can find in Azure function properties"
$parameterFile.parameters.BackendSettings.value.backendname.url = "The URL"
$parameterFile.parameters.BackendSettings.value.backendname.protocol = "http"
$parameterFile | ConvertTo-Json -depth 32| set-content $extractParameterFilePath`

**Comment by adrianhall** [comment]
Backend and Logger information is not parameterized.  Please open a new issue (filling in the bug report information) if you are still experiencing an issue with this.

Thanks!
