### ISSUE TITLE
Azure monitor keeps on populating even after disabling it

### ISSUE THREAD

**Issue by waelkdouh** [Azure/azure-api-management-devops-resource-kit#520]
I noticed if I enable azure monitor and then disable it and delete the diagnostics logger on the azure portal the tool keeps on generating the information for both in the templates. It’s as if there is some lingering settings that don’t get cleaned up on the APIM side that the tool keeps picking up and regenerating.

**Comment by adrianhall** [comment]
There is not enough information here to reproduce the problem.  Can you please provide:

1) Your repro steps
2) Command lines you are using
3) Any config files in place

**Comment by adrianhall** [comment]
Auto-close due to age.
