### ISSUE TITLE
Azure monitor information not getting properly populated

### ISSUE THREAD

**Issue by waelkdouh** [Azure/azure-api-management-devops-resource-kit#522]
I noticed that when I enable Azure monitor on the global level of the apim instance then the extractor tool generates a value of null for the azuremonitor parameter. What is interesting is that if I enable Azure monitor on a specific api level (e.g. for finer granularity) and set the “paramApiLoggerId” property to true in the extractor config file then the information gets populated correctly there.

**Comment by adrianhall** [comment]
There is not enough information here to reproduce the problem.  Can you please provide:

1) The set up of your APIM instance and Azure Monitor instance.
2) The Command line you are using for extractor
3) Any configuration files that you are using

Thanks,

**Comment by adrianhall** [comment]
Auto-close due to age.
