### ISSUE TITLE
Problems in the Extract Tool

### ISSUE THREAD

**Issue by SamPoddar** [Azure/azure-api-management-devops-resource-kit#524]
dotnet run extract --sourceApimName paas-mgmt-cin-apimsrc --destinationApimName paas-mgmt-cin-apimdest --resourceGroup paas-mgmt-cin-srcrg --fileFolder c:\temp\apim-extract --linkedTemplatesBaseUrl https://armtemplatescinstrgaccnt01.blob.core.windows.net/linkedarmtemplates --policyXMLBaseUrl https://armtemplatescinstrgaccnt01.blob.core.windows.net/linkedarmtemplates/policies --linkedTemplatesSasToken “?” --linkedTemplatesUrlQueryString “sp=r&st=2021-04-09T09:22:54Z&se=2022-04-09T17:22:54Z&spr=https&sv=2020-02-10&sr=c&sig=x2vM781PF7fswR4WCamizhpeQPDc4SoMNF7uUMOCj1s%3D”
 
Problems in Extract Tool
1.	It does not generate the linked arm template for the API Management Instance itself neither its reference in the master template.
2.	The policyBaseXML references parameters to the linked templates call from the master template are all missing. I had to make manually many changes to the policyBaseXML parameter call changes to the master template and several linked templates

**Comment by adrianhall** [comment]
I'm unable to parse this bug report.  Can you please provide split this into two issues and for each one, provide detailed information so that we can reproduce the bug.

Thank you.
