### ISSUE TITLE
[Creator] Enable option to generate SAS token using ARM template functions

### ISSUE THREAD

**Issue by levimatheri** [Azure/azure-api-management-devops-resource-kit#526]
The [listAccountSas](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-functions-resource#list-example) function along with [date functions](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-functions-date) can be used to generate SAS token for linked templates stored in a storage account. This is especially helpful when one has a complex hierarchy of linked templates and to be able to use `parametersLink` to reference a parameters file without having to worry about passing the SAS token along.
The master template could have a `variables` section with the following:
```
"variables": {
    "newDateTime": "[dateTimeAdd(parameters('currentTime'), 'PT20M')]",
    "sasProperties": {
        "signedServices": "b",
        "signedPermission": "rl",
        "signedExpiry": "[variables('newDateTime')]",
        "signedResourceTypes": "co"
    },
    "storageAccountResourceName": "[concat('Microsoft.Storage/storageAccounts/', parameters('StorageAccountName'))]"
  }
```

The linked templates would then be referenced like so:
```
"templateLink": {
          "uri": "[concat(parameters('LinkedTemplatesBaseUrl'), '/myLinkedTemplate.template.json?', listAccountSas(variables('storageAccountResourceName'), '2018-11-01', variables('sasProperties')).accountSasToken)]",
          "contentVersion": "1.0.0.0"
        },
```

**Comment by adrianhall** [comment]
Thank you for your input on the creator tool.  We are currently looking at the future of the creator tool and would like your feedback.  Please could you fill in the survey at https://forms.office.com/r/w7rQp88NwH - your input is appreciated.

**Comment by adrianhall** [comment]
This project is now in "maintenance" mode. This means that no new features will be accepted and fixes will be limited to security fixes. We expect to retire the DevOps Resource Kit by the end of 2023. At that time, the DevOps Resource Kit repository will be archived and there will be no further updates.

While you are free to fork the DevOps Resource Kit yourself, we recommend that you migrate to the following products:

* If you are using creator, switch over to using [Bicep](https://learn.microsoft.com/azure/azure-resource-manager/bicep/overview) templates. Bicep is a descriptive language for describing infrastructure, fully supports all features of Azure API Management, and is covered in any support agreement that you have with Azure. You can find bicep modules and examples for handling API Management APIs at https://github.com/azure-samples/api-management-sample-apis.
* If you are using extractor, switch your pipelines to use [APIOps](https://github.com/azure/apiops). APIOps applies the concepts of GitOps to API deployments. It is faster and more flexible than the DevOps Resource Kit.
