### ISSUE TITLE
Extract Diagnostic settings

### ISSUE THREAD

**Issue by AjaySewradj** [Azure/azure-api-management-devops-resource-kit#527]
Hi,

I've configured the Azure Monitor logger in my APIM instance. I've also setup Diagnostic Settings, which sends all my Logs and Metrics to a LogAnalytics workspace, and also to a Storage account.

It seems that the Extractor tool doesn't extract the Diagnostic Settings.
My questions are:
1. Could the Diagnostic Settings be added to the Extractor tool?
2. Could you supply the ARM template for creating the Diagnostic Settings as a workaround?

I've tried this ARM template and it works, but I can't find the documentation so I don't know which properties are supported:
```json
{
      "type": "Microsoft.ApiManagement/service/providers/diagnosticSettings",
      "apiVersion": "2017-05-01-preview",
      "name": "[concat(parameters('apiManagementServiceName'), '/Microsoft.Insights/', variables('diagnosticSettingsName'))]",
      "dependsOn": [ "[resourceId('Microsoft.ApiManagement/service', parameters('apiManagementServiceName'))]" ],
      "properties": {
        "logs": [
          {
            "category": "GatewayLogs",
            "enabled": true
          }
        ],
        "metrics": [
          {
            "category": "AllMetrics",
            "enabled": true
          }
        ],
        "workspaceId": "[resourceID('Microsoft.OperationalInsights/workspaces', 'my-loganalytics-workspace')]"
      }
```

**Comment by AjaySewradj** [comment]
Any updates or alternatives?

**Comment by adrianhall** [comment]
The loggers are defined here: https://docs.microsoft.com/en-us/rest/api/apimanagement/current-ga/logger/create-or-update

The 2017-05-01-preview API is deprecated, which is why you are not seeing any documentation for it.

We will add loggers to a future release.
