### ISSUE TITLE
ResourceID is hard coded in backends.template

### ISSUE THREAD

**Issue by debmalya1994** [Azure/azure-api-management-devops-resource-kit#533]
{
      "properties": {
        "description": "issue",
        "resourceId": "https://management.azure.com/subscriptions/1111111111111/resourceGroups/sadasdsad/providers/Microsoft.Web/sites/asdasdsadasds",
.......
}

resourceID is coming as hardcoded in the template instead parameterized

**Comment by adrianhall** [comment]
Feels like this should be fixed.  If you are still experiencing an issue with this, please open a new issue with the required information.
