### ISSUE TITLE
[Creator] API display name gets overwritten by swagger title

### ISSUE THREAD

**Issue by levimatheri** [Azure/azure-api-management-devops-resource-kit#538]
The API display name should get its value from the `displayName` property in the `Microsoft.ApiManagement/service/apis` resource. When a swagger file or contents are included in the ARM template, the display name is overwritten by the `info.title` attribute of the swagger. Our current workaround is to add a nested template within the API template that doesn't include the swagger. This works but is not ideal.

**Comment by springcomp** [comment]
@levimatheri  I used to have the same issue and tried to tackle this subject.
To my surprise, as of today, this appear to no longer be the case.

Can you test on your end ?

By the way, this is | was a limitation of the REST API for Azure API Management which is used internally by ARM templates.
https://github.com/Azure/azure-rest-api-specs/issues/13445

**Comment by levimatheri** [comment]
@springcomp I can confirm that your claim. It's working as expected now. So, no need for initial and subsequent templates, just combine into one?
