### ISSUE TITLE
[Creator] Generating APIM templates with invalid parameters file schema

### ISSUE THREAD

**Issue by syeatts** [Azure/azure-api-management-devops-resource-kit#542]
This file: https://github.com/Azure/azure-api-management-devops-resource-kit/blob/master/src/APIM_ARMTemplate/apimtemplate/Creator/TemplateCreators/TemplateCreator.cs

Was changed in this commit: https://github.com/Azure/azure-api-management-devops-resource-kit/commit/eff52d583ce70ec78b33c758b72f4308dd435219

The commit updated the schema to 2019-04-01. Unfortunately the parameters schema looks like it was the victim of a C&P error and writes itself as a deploymentTemplate and not a deploymentParameter file now.

I believe it should use `"$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#"` on line 27.

**Comment by levimatheri** [comment]
I can work on fixing this.

**Comment by adrianhall** [comment]
Looks like this was fixed, so I'll close this now.  If it is still an issue in the main branch, feel free to submit another bug report.
