### ISSUE TITLE
Error code: InvalidTemplate - single API, single revision

### ISSUE THREAD

**Issue by biancafrigerioMS** [Azure/azure-api-management-devops-resource-kit#561]
Hello,

I'm retrieving this validation ARM Template error:

_There were errors in your deployment. Error code: InvalidTemplate.
##[error]Deployment template language expression evaluation failed: 'The language expression '
  {
    "id": 0,
    "name": "string",
    "isComplete": true,
    "secret": "string"
  }
' is not valid: the string character '{' at position '4' is not expected.'. Please see https://aka.ms/arm-template-expressions for usage details._

The ARM Template is the single revision extraction template.

I found that in the ARM Template there is an error, at line 151 there are two squared brackets opened and one closed.

![image](https://user-images.githubusercontent.com/57915354/128320490-f6bc703e-1ab4-4066-9ada-a0345ea84622.png)

Can you help me in understanding why this error is generated?

Thank you

Bianca

**Comment by adrianhall** [comment]
Can you please provide some more information:

1) What version of the DevOps Resource Kit are you using?
2) What OS and dotnet version are you using?
3) What command line are you using?
4) What is the configuration file you are using?

Thanks,
