### ISSUE TITLE
[Creator] Deploying multiple versions fail

### ISSUE THREAD

**Issue by springcomp** [Azure/azure-api-management-devops-resource-kit#562]
When deploying multiple APIs attached to the same `apiVersionSet`, deployment may fail randomly due to any of the following reasons:

- Since no dependencies exist between different versions, deployment happen in parrallel.
- Failure may happen because: "An API with specified name already exists".
- Failure may happen because: "An API with the same path already exists".

To reproduce this case, please consider the following simple config file:
[https://gist.github.com/springcomp/cee9eb07720fd3633fbce42a93f49da5](https://gist.github.com/springcomp/cee9eb07720fd3633fbce42a93f49da5)

I think both issues can be solved by:

- Introducing an explicit dependency of subsequent versions to the main "original" API or to the previous version. This will make sure that each version is deployed sequentially indenpendantly to one another.

- Versions are hosted into two sequential templates "initial" and "subsequent". It happens that the "initial" template for a version fails because another version of the API has the same path. I have not found a bug in the generated templates. However, one can circumvent this by specifying a dummy path in the "initial" template. Oddly enough, once the "initial" template succeeds, the "subsequent" template will overwrite the `path` to the correct value.

**Comment by RupengLiu** [comment]
Triaged, will review and fix it

**Comment by DeagleGross** [comment]
This issue is closed + it doesn't have a good explanation to the commits provided. Nothing to do here. Moving to `to be released`
