### ISSUE TITLE
policyBaseUrl

### ISSUE THREAD

**Issue by mikegoau1** [Azure/azure-api-management-devops-resource-kit#563]
I am having issues pointing the policyBaseUrl to a location other than a blob/container.  Is it possible to retrieve the xml files from devops?

**Comment by adrianhall** [comment]
Hi Mike,

Could you be more specific in the ask.

1) What version of  DevOps Resource Kit are you using?
2) What OS and dotnet version are you using?
3) Provide enough of the configuration to isolate the issue you are seeing?
4) Provide an example or working vs. not working.

Thanks,

**Comment by adrianhall** [comment]
Closing due to lack of follow-up.  If this is still an issue, please open a new issue and provide all the information required.
