### ISSUE TITLE
APIM Extractor Tool - Destination File Folder does not automatically get created

### ISSUE THREAD

**Issue by nirupamasrivastava** [Azure/azure-api-management-devops-resource-kit#566]
Hello,

When running APIM Extractor Tool , destination file folder specified under "fileFolder" inside extractorparams.json does not get created if it does not exist already.

**extractorparams.json**
```
{
    "sourceApimName": "<source-apim-name>",
    "destinationApimName": "<destination-apim-name>",
    "resourceGroup": "<resource-group>",
    **"fileFolder": "<destination-file-folder>",**
    "apiName": "<api-name>"
}
```

Thanks and Regards

**Comment by RupengLiu** [comment]
@nirupamasrivastava , this actually is not a bug, and is expected, we wont create the folder if not exist,
