### ISSUE TITLE
Creator not generating a deployable ARM template from openapi 3.0.1 file

### ISSUE THREAD

**Issue by mradulmodi** [Azure/azure-api-management-devops-resource-kit#567]
I believe the issue solved and reported [here ](https://github.com/Azure/azure-api-management-devops-resource-kit/issues/166) has started reoccurring. 

Recently it seems `APITemplateCreator` code has been updated to check the swagger file is of open api version 3+ (`isVersionThree`) only if the api format in yml is unspecified (making `isVersionThree` = `false`). This causes files with  `OpenApi30_Json` format specified to be assumed of not open api version 3+ and this then fails in method `GetOpenApiSpecFormat` to return `swagger-json`. `swagger-json` in API templates causes ARM deployment to fail. 

![image](https://user-images.githubusercontent.com/6408025/130266974-a33f04e7-0914-4e67-b414-9b9611a349a1.png)

![image](https://user-images.githubusercontent.com/6408025/130267493-2bfd518f-8338-4711-bdc0-d752f817b0a7.png)

Can you please help address this.

**Comment by adrianhall** [comment]
Can you please reply with the version you are using for this report?  I'd like to get an idea of where the regression popped back in.

Thanks,

**Comment by springcomp** [comment]
@mradulmodi I’m the author of the offending code.

I believe your are correct, and the `isVersionThree` variable is not correctly updated if the `openApiSpecFormat` property is set to `OpenApi30_Json` or `OpenApi30_Yaml`.

This is fixed by #578.

**Comment by mradulmodi** [comment]
Just for reference the version I was using was `v0.6`

**Comment by adrianhall** [comment]
Thank you for your input on the creator tool.  We are currently looking at the future of the creator tool and would like your feedback.  Please could you fill in the survey at https://forms.office.com/r/w7rQp88NwH - your input is appreciated.

**Comment by adrianhall** [comment]
This project is now in "maintenance" mode. This means that no new features will be accepted and fixes will be limited to security fixes. We expect to retire the DevOps Resource Kit by the end of 2023. At that time, the DevOps Resource Kit repository will be archived and there will be no further updates.

While you are free to fork the DevOps Resource Kit yourself, we recommend that you migrate to the following products:

* If you are using creator, switch over to using [Bicep](https://learn.microsoft.com/azure/azure-resource-manager/bicep/overview) templates. Bicep is a descriptive language for describing infrastructure, fully supports all features of Azure API Management, and is covered in any support agreement that you have with Azure. You can find bicep modules and examples for handling API Management APIs at https://github.com/azure-samples/api-management-sample-apis.
* If you are using extractor, switch your pipelines to use [APIOps](https://github.com/azure/apiops). APIOps applies the concepts of GitOps to API deployments. It is faster and more flexible than the DevOps Resource Kit.
