### ISSUE TITLE
Group and Product errors (Extractor)

### ISSUE THREAD

**Issue by mzrzz3** [Azure/azure-api-management-devops-resource-kit#568]
## Update

When creating a service, certain products and groups are pre-created with defined names (like Administrators and Developers).  In older versions of the service, the underlying ID of these groups was a GUID.  When you try to import these groups into a newer service, it fails because the ID does not match.

Proposal:
Have a setting that merges the products/groups based on name for the system names (rather than on ID).

## Original Submission

Templates generated from the extractor still seem unable to create missing groups.

Products fail if they already exist.  - This may be related to concurrency but unable to confirm.

I wish this this tool was more stable it has such great potential!

Typical error shown below.

``` json
{
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
  "details": [
    {
      "code": "ValidationError",
      "message": "Product with the same name already exists"
    },
    {
      "code": "ValidationError",
      "message": "Group not found"
    },
    {
      "code": "ValidationError",
      "message": "Group not found"
    },
    {
      "code": "ValidationError",
      "message": "Group not found"
    },
    {
      "code": "ValidationError",
      "message": "Group not found"
    },
    {
      "code": "ValidationError",
      "message": "Group not found"
    },
    {
      "code": "ValidationError",
      "message": "Product with the same name already exists"
    }
  ]
}
```

**Comment by adrianhall** [comment]
Can you provide more details on the failure.  We don't have enough to reproduce here.

What version of the tool are you using?
What does the ARM template it generated look like? (Use gist and copy links, or reach out to send them to me)
What does the source APIM instance look like?
What does the current state of the destination APIM instance look like?

Thanks,

**Comment by mzrzz3** [comment]
@adrianhall 

So here is a weird situation. I am implementing APIM DevOps with a client that has instances in test and production that were created maybe 4 years ago. I stood up a new dev instance in which to develop the DevOps steps. My plan was to extract from production and then import into the dev instance in order to create a new baseline.

What I found was that the IDs for the system products (Starter, Unlimited) and the system groups (administrator, developers, guests, etc.) in the old test/production environments are IDs of a large random-ish integers. In the new dev instance the same products and groups simply have the name in lower case as the ID. 

I initially thought I was having a product/group problem that I had seen reported in other issues. However, in my case it is simply that the well-known groups and products have different IDs.

My workaround was to manually search and replace the IDs (from integers to names) in the extracted files that came from production before deploying them into the development instance.

Has anyone else noticed this problem in different versions of APIM? As this client is replacing the test and production environments with new instances and VNET integration this should hopefully not be a problem going forward.

Attached are some screen shots from the old and new instances.

<img width="428" alt="apim-1" src="https://user-images.githubusercontent.com/7062176/130540234-915df878-b6a9-4e16-abad-23c5d2ccddb3.png">
<img width="370" alt="apim-2" src="https://user-images.githubusercontent.com/7062176/130540236-a5aa4bcd-3d3d-43a1-a4d8-09cf17f8c84d.png">
<img width="299" alt="apim-3" src="https://user-images.githubusercontent.com/7062176/130540237-a202cc59-a2de-4375-a418-54f6b26f8724.png">
<img width="269" alt="apim-4" src="https://user-images.githubusercontent.com/7062176/130540238-1dc35a5d-8241-4c87-8b90-7a340017bf5f.png">



Thanks for reviewing this issue.

**Comment by adrianhall** [comment]
That is indeed wierd.  I wasn't around APIM 4 years ago, so I'll have to check in to this.

**Comment by adrianhall** [comment]
The problem is this.  In the dim past, we generated GUIDs for all the different default products and groups.  The problem is that if you try to create (for example) name=Unlimited id=some-guid and name=Unlimited id=unlimited already exists, it will fail because the ID is different.

Short term, you have the right answer - edit the values to put the right ID in.

Long term, we should probably implement something where you specify a switch to "merge identical names" if they exist on import (with the default being the safe option of not merging and failing).  I will edit the description accordingly.
