### ISSUE TITLE
QUESTION: AAD Groups and Extractor

### ISSUE THREAD

**Issue by mzrzz3** [Azure/azure-api-management-devops-resource-kit#569]
When securing the developer portal using AAD groups, the group names are likely to be different in each environment. For example, consider the following AAD groups to authorize developers:

Dev: MyDomain\Developers-Dev
Test: MyDomain\Developers-Test
Prod: MyDomain\Developers-Prod

Obviously, this will cause havoc with group to product assignments when extracting from development and attempting to deploy to test or production.

What is the best way to handle this situation?

Thanks

**Comment by adrianhall** [comment]
It is supported and there are no plans currently to end support of this functionality.

We are investigating alternative export formats, including Bicep.
