### ISSUE TITLE
Creator - Exception during deserialization

### ISSUE THREAD

**Issue by flyingmouse** [Azure/azure-api-management-devops-resource-kit#571]
I am getting an exception when using the creator tool. How can I debug this?
(Line: 1, Col: 1, Idx: 0) - (Line: 36, Col: 672, Idx: 13457): Exception during deserialization

**Comment by fortunkam** [comment]
Can you share the parameters you are using with the creator tool?

**Comment by adrianhall** [comment]
No update since 2021.  Since we don't have the relevant information to diagnose the problem, I am closing this issue.

If you have additional information, please open a new issue and provide all the requested information.
