### ISSUE TITLE
The value for the template parameter 'serviceUrl' at line '1' and column '210' is not provided after version update v0.5 to v0.6

### ISSUE THREAD

**Issue by jestevez** [Azure/azure-api-management-devops-resource-kit#574]
Hello, update my version and I have encountered this error:

[error]Deployment template validation failed: 'The value for the template parameter 'serviceUrl' at line '1' and column '210' is not provided. Please see https://aka.ms/resource-manager-parameter-files for usage details.'.

These are the changes that I have seen between the generated files:

![image](https://user-images.githubusercontent.com/775669/132017311-9cff21d9-e27c-4166-b1fd-5cc056a42346.png)

![image](https://user-images.githubusercontent.com/775669/132017631-00d5169e-aa8a-411a-af41-72ca5b592f37.png)

**Comment by Kumar-Ashwin-Hubert** [comment]
Same here, we thought of upgrading but while testing we are encountering this issue.
This change is not mentioned anywhere in the docs.

**Comment by springcomp** [comment]
@Kumar-Ashwin-Hubert You might be interested in using [my unofficial fork](https://github.com/springcomp/azure-api-management-devops-resource-kit/tree/1.0.5-zeta-11) that is generally current with this repository.

However, it ignores the recent `-ServiceUrl` parameter introduced by #490 which is a breaking change for us.
It served us well with my team so far.

Please see #577 that I raised to get more insights into this change.

**Comment by adrianhall** [comment]
You have not provided enough information to reproduce the problem.  Can you please revalidate (if you have not worked around the problem) on the latest code and open a new issue if this is still a problem with the required information needed for a reproduction.

Thanks!
