### ISSUE TITLE
Usage of new -ServiceUrl parameter

### ISSUE THREAD

**Issue by springcomp** [Azure/azure-api-management-devops-resource-kit#577]
I have been using the `Creator` tool for a long time with success in our own internal processes as follows.

We store API configurations and policies in source control in separate folders to promote sharing and concurrent contributions. The configurations use the Helm templating syntax to allow for some customization.

The continuous integration process uses Helm to merge all the source code configurations to a single YAML configuration file that the `Creator` tool can use to produce the resulting ARM templates.

Those ARM templates are then deployed using continuous deployment. At no time in the process are the ARM templates, nor the YAML configuration file stored in source control. They are just interim generated artifacts.

A few months ago, a breaking change happened introducing a new `-ServiceUrl`  parameter in each of the generated ARM template file associated with an API. However, I have no idea how to use this new parameter which is not surfaced in the main `-master` template. As a result, I have been using a fork of this repository and made every effort to contribute my changes to this upstream repository, but I fear that over time my team will not be able to keep up.

Can you clarify how these new parameters are supposed to be used ?

**Comment by springcomp** [comment]
@RupengLiu

**Comment by springcomp** [comment]
Here is a sample configuration file:

https://gist.github.com/springcomp/22c96c216a361befa289dd1e0b01aa6f#file-apim-config-yaml

The generated ARM template file `HttpBin.Org.api.template.json` used to look like:

```json
{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "ApimServiceName": {
      "type": "string"
    }
  },
  "resources": [
    {
      "properties": {
        "description": "int-httpbin-org",
        "isCurrent": false,
        "subscriptionRequired": false,
        "displayName": "HttpBin.Org",
        "serviceUrl": "https://httpbin.org",
        "path": "/int/httpbin-org",
        "protocols": [
          "https"
        ],
        "value": "{}",
        "format": "swagger-json"
      },
      "name": "[concat(parameters('ApimServiceName'), '/HttpBin.Org')]",
      "type": "Microsoft.ApiManagement/service/apis",
      "apiVersion": "2019-01-01",
      "dependsOn": []
    }
  ]
}
```

After applying #490, the generated ARM template looks like so:

```json
{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "ApimServiceName": {
      "type": "string"
    },
    "HttpBin.Org-ServiceUrl": {
      "type": "string"
    }
  },
  "resources": [
    {
      "properties": {
        "description": "int-httpbin-org",
        "isCurrent": false,
        "subscriptionRequired": false,
        "displayName": "HttpBin.Org",
        "serviceUrl": "[parameters('HttpBin.Org-ServiceUrl')]",
        "path": "/int/httpbin-org",
        "protocols": [
          "https"
        ],
        "value": "{}",
        "format": "swagger-json"
      },
      "name": "[concat(parameters('ApimServiceName'), '/HttpBin.Org')]",
      "type": "Microsoft.ApiManagement/service/apis",
      "apiVersion": "2021-01-01-preview",
      "dependsOn": []
    }
  ]
}
```

**Comment by springcomp** [comment]
Maybe related to 

- #545
- #574

**Comment by adrianhall** [comment]
Thank you for your input on the creator tool.  We are currently looking at the future of the creator tool and would like your feedback.  Please could you fill in the survey at https://forms.office.com/r/w7rQp88NwH - your input is appreciated.

**Comment by adrianhall** [comment]
This project is now in "maintenance" mode. This means that no new features will be accepted and fixes will be limited to security fixes. We expect to retire the DevOps Resource Kit by the end of 2023. At that time, the DevOps Resource Kit repository will be archived and there will be no further updates.

While you are free to fork the DevOps Resource Kit yourself, we recommend that you migrate to the following products:

* If you are using creator, switch over to using [Bicep](https://learn.microsoft.com/azure/azure-resource-manager/bicep/overview) templates. Bicep is a descriptive language for describing infrastructure, fully supports all features of Azure API Management, and is covered in any support agreement that you have with Azure. You can find bicep modules and examples for handling API Management APIs at https://github.com/azure-samples/api-management-sample-apis.
* If you are using extractor, switch your pipelines to use [APIOps](https://github.com/azure/apiops). APIOps applies the concepts of GitOps to API deployments. It is faster and more flexible than the DevOps Resource Kit.
