### ISSUE TITLE
Creator - generates tags with invalid name

### ISSUE THREAD

**Issue by TWolverson** [Azure/azure-api-management-devops-resource-kit#584]
When the displayName of a tag declared at the service level contains spaces or punctuation, this generates an invalid tags template:

config file:
```
tags: 
  - displayName: Internal Payroll - International
```

produced template:

```
    {
      "properties": {
        "displayName": "Internal Payroll - International"
      },
      "name": "[concat(parameters('ApimServiceName'), '/Internal Payroll - International')]",
      "type": "Microsoft.ApiManagement/service/tags",
      "apiVersion": "2021-01-01-preview",
      "dependsOn": []
    }

```
This yields an error message on deploying:

`2021-10-14T12:03:51.9706948Z ##[error]ValidationError: Invalid identifier Internal Payroll - International specified.  Entity Identifier can contain only letters, numbers, and hyphens. The first and last character must be a letter or a number `

There is no documented way to specify any properties of tags other than their displayName, which appears to be carried through into the internal resource name as though it is a valid name, which it may not be. When created in a live APIM instance, the displayname is as stated but the internal resource name is internal-payroll-international. There does not appear to be a way to make the Creator do this conversion.

**Comment by f-alizada** [comment]
Hello @TWolverson. Thank you for raising the issue.
The bug is closed since the PR resolving the problem is merged into main branch and will be released in 1.0.0-beta.6
Please feel free to reopen the issue if the behaviour will be the same in main branch or upcoming releases.
