### ISSUE TITLE
[Creator] Open API specification | master/linked template does not generate

### ISSUE THREAD

**Issue by architect-tarun-narang** [Azure/azure-api-management-devops-resource-kit#593]
I am trying to learn the usage of the Creator template to work on CI/CD for my project. I generated the ARM templates using the Creator command for Open API specification. However, it did not generate the master/linked template but generated the initial and subsequent templates. And the azure DevOps requires one single template to deploy the changes I believe.

Please confirm if I'm missing something, below are the steps I took to configure:-

**Config.xml**

![image](https://user-images.githubusercontent.com/59596411/139702084-6cbd9619-f90e-4c57-a562-3c5066409b9b.png)

**Swagger.json**
```
{
  "openapi": "3.0.1",
  "info": {
    "title": "My API",
    "version": "v1"
  },
  "paths": {
    "/WeatherForecast": {
      "get": {
        "tags": [
          "WeatherForecast"
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/WeatherForecast"
                  }
                }
              },
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/WeatherForecast"
                  }
                }
              },
              "text/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/WeatherForecast"
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "WeatherForecast": {
        "type": "object",
        "properties": {
          "date": {
            "type": "string",
            "format": "date-time"
          },
          "temperatureC": {
            "type": "integer",
            "format": "int32"
          },
          "temperatureF": {
            "type": "integer",
            "format": "int32",
            "readOnly": true
          },
          "summary": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      }
    }
  }
}
```

**Used the below command to generate the files**
dotnet run create --confiFile .\config.xml

**which generated the below files but not the master template.**
![image](https://user-images.githubusercontent.com/59596411/139702984-1b7f10e2-5337-4bcc-a075-ac4fd22b3e19.png)

**Comment by architect-tarun-narang** [comment]
Any update on this would be appreciated. Thanks

**Comment by AL1041989** [comment]
Hello,

You are missing the 2 lines 

linked: true   # Optional
linkedTemplatesBaseUrl : ./Output  # Required if 'linked' property is set to true

at the end of your config.xml

**Comment by adrianhall** [comment]
This feels like it has been answered.  If you feel there is a bug to be reported here, please open a new issue with all required information.

Thanks!
