### ISSUE TITLE
ARM Template Deployment Task error - Error code: RequestContentTooLarge.

### ISSUE THREAD

**Issue by nirupamasrivastava** [Azure/azure-api-management-devops-resource-kit#594]
We ran Extractor Tool on a small SOAP Policy to extract ARM Template Json. The Template Json fails on the ARM Template Deployment Task - Validation step with below error:

      There were errors in your deployment. Error code: RequestContentTooLarge.
      ##[error]The request content size exceeds the maximum size of 4 MB.

Please advise how we can resolve this issue.

Thanks !!

**Comment by adrianhall** [comment]
There is no way we can resolve this as it is an ARM limitation.  My suggestion here would be to switch over to Terraform and hand-craft the request.  Terraform uses the ARM API rather than ARM deployment.
