### ISSUE TITLE
Extractor - Does not extract namedvalues and backend templates for some apis

### ISSUE THREAD

**Issue by trishank87** [Azure/azure-api-management-devops-resource-kit#597]
We are using extractor tool to extract arm templates for single api. It used to work fine earlier where its used to extract all the named values and backends for single api and we used to remove all the unwanted ones.

But after downloading the latest code we observed that the arm templates extraction for named values and backend is not working as expected for some apis.

It worked for one of the api properly where it just extracted the arm template properly and those templates had only the required resources and not all which was good. 

But for some of the api its not extracting this two templates.

we are basically trying to extract the templates using the master template approach where we pass the policyXMLBaseUrl and linkedTemplatesBaseUrl as config parameters.

Please let us know if there is any workaround for this issue

This is what we see in output window
![image](https://user-images.githubusercontent.com/16982837/143002060-9beb0a62-3421-4231-a891-fd2672a6bf83.png)

**Comment by mlewisbuku** [comment]
I reproduced this issue when the extract fileFolder parameter was an absolute path.

GetPolicyContent() in ExtractorUtils.cs builds up a filepath to search for variable usages, and prepends the current working directory to the front of the fileFolder's policies directory:

```
var policyFolder = $@"{exc.fileFolder}/policies";
var filepath = $@"{Directory.GetCurrentDirectory()}/{policyFolder}/{filename}";

```

So if fileFolder was specified as "c:\results" and the current working directory is "c:\dev", GetPolicyContent() would search for the variables in files in "c:\dev\c:\results\policies" and not find any.

**Comment by DeagleGross** [comment]
Hello @mlewisbuku and @trishank87.
Thanks for submitting an issue.

We have been working on resource-kit a lot in the last time, and it is brand new. Can you, please, check out new version? Probably, it is already working correctly - especially because I have fixed absolute-path extract folder (appeared in #583) in a #654 pull request.

I will close issue now, but feel free to open a new one, if you have any issues.
