### ISSUE TITLE
[Creator] Support for deleting child resources through Complete deployment mode

### ISSUE THREAD

**Issue by kevinsylee** [Azure/azure-api-management-devops-resource-kit#602]
When deploying APIM API changes in Complete mode using ARM templates, we noticed that child resources did not get deleted.  

We have a resource group with only the APIM instance and an ARM template that captures this resource as well as its child resources.  Removing a child resource (an API) from this template and redeploy in Complete mode didn’t delete the corresponding resource from APIM.

Per my understanding, Complete mode should delete child resources?  If not, please update the documentation to make this clear.
https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/deployment-complete-mode-deletion#microsoftapimanagement
 
Steps to reproduce the issue:

Deploy the template (template-2apis.json) with an APIM that contains 2 APIs:
az deployment group create --mode Complete --resource-group rg-apim-develop --parameters parameters.json --template-file template-2apis.json
Deploy the other template (template-1api.json) with only 1 API:
az deployment group create --mode Complete --resource-group rg-apim-develop --parameters parameters.json --template-file template-1api.json
 

Expected result: Only 1 API left after running Step 2.

Actual result: There are still 2 APIs in the APIM instance after running Step 2.

**Comment by adrianhall** [comment]
This is a function of the ARM deployment scheme and not something we can correct in the DevOps Resource Kit.
