### ISSUE TITLE
Cloning this repo from command line results in warning

### ISSUE THREAD

**Issue by nilvon9wo** [Azure/azure-api-management-devops-resource-kit#604]
When I cloned this repo from the command line, it resulted in the following surprising warning:

```
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

'docs/images/Architecture.png'
'docs/images/architecture.png'
```

While `git status` confirms "nothing to commit, working tree clean", if I look at Windows Explorer (for which I have [TortoiseGit](https://tortoisegit.org/)), there is a red circle with an exclamation point indicating this folder is out of sync.

![image](https://user-images.githubusercontent.com/357660/152511412-ba378d15-9d54-45de-a8dd-39d39f28ca47.png)

And if I look in "/docs/images/", the "Architecture.png" is missing.

Browsing the files here, I can see "Architecture.png" and "architecture.png" are identical.

I expect "Architecture.png" should be deleted unless this is needed for legacy reasons.

**Comment by adrianhall** [comment]
Thanks for the report - fixed.  Let me know if you still have problems cloning.
