### ISSUE TITLE
Rename master to main branch

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/azure-api-management-devops-resource-kit#614]
Rename master to main branch to align with the new standard and be more inclusive.

**Comment by DeagleGross** [comment]
Done it - https://github.com/Azure/azure-api-management-devops-resource-kit/tree/main

**Comment by tomkerkhove** [comment]
Can you update our pipeline please? https://github.com/Azure/azure-api-management-devops-resource-kit/blob/main/.azure-pipelines/scheduled-build.yml#L15

**Comment by DeagleGross** [comment]
Here is the [pull request](https://github.com/Azure/azure-api-management-devops-resource-kit/pull/619)
