### ISSUE TITLE
Parameterize Logic Apps backends when extracting

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-api-management-devops-resource-kit#622]
Customer has 500 logic apps that they are exposing behind APIM - they are looking for a mechanism to make sure that backends are extracted as parameters using the extractor tool.  Different environments use different logic apps backends, so this will allow them to extract once and deploy to multiple APIM instances.

Ref: UAT 65888

**Comment by DeagleGross** [comment]
Add `proxy` and `credentials` as parameters when extracting backends
https://docs.microsoft.com/en-us/rest/api/apimanagement/current-ga/backend/create-or-update#backendproxycontract

**Comment by akshatgupta02** [comment]
Hi,

Is it possible to parametrize the Backend URL. For eg, while moving from Dev to Test env, the Backend URL in parameter.json file reflect Dev URLs. And we have 50 operations (Logic app and function app) in a single API. So, it would be helpful if on basis of resource id the Backend URL could also be parametrized.
