### ISSUE TITLE
Plan Refactor Creator code flow

### ISSUE THREAD

**Issue by DeagleGross** [Azure/azure-api-management-devops-resource-kit#623]
There are two options for the ARMTemplates project and they are `Extractor` and `Creator`.

`Extractor` code is already refactored to have an entry point as a console application and an entrypoint like a class with exposed API for any templates extraction and generation (explore [ExtractorExecutor](https://github.com/Azure/azure-api-management-devops-resource-kit/blob/main/src/ArmTemplates/Commands/Executors/ExtractorExecutor.cs)). Such logic separation is better for testing and code readability, following SOLID (single responsibility for a single class).

The same thing is needed to be done for `Creator` flow.

# Plan of refactoring (in order)
- [x] Move `CreatorParameters` parsing and creation to `CreateApplicationCommand`. All execution logic leave in [CreatorExecutor](https://github.com/Azure/azure-api-management-devops-resource-kit/blob/main/src/ArmTemplates/Commands/Executors/CreatorExecutor.cs). Remove all `Utilities` from Creator and make proper overriding of parameters using console-arguments as done in extractor. Also take a look at validator - it seems to be very complicated. #698 
- [x] Create bunch of interfaces for [each different typed creator](https://github.com/Azure/azure-api-management-devops-resource-kit/blob/265a2bf0762d2e8cf2c9fe6b59170ec53dbce685/src/ArmTemplates/Commands/Applications/CreateApplicationCommand.cs#L113-L128). Locate them in `Creator.TemplateCreators.Abstractions` namespace. add them to DI registration and write a test on properly resolving `CreatorExecutor` from `ServiceProvider`  #698 
- [ ] **!Important!** Carefully think about all the template-models existing for extractor and how to reuse them in creator. There are a lot of duplicates I've messed with during initial creator refactoring code dive. In example look at [CreatorConfiguration](https://github.com/Azure/azure-api-management-devops-resource-kit/blob/main/src/ArmTemplates/Creator/Models/CreatorConfiguration.cs), that contains a lot of close likely models as in `Extractor`

*// below there are tasks for each creator separate refactoring. Please, pay attention that code has to have tests*
- [ ] refactor `ApiVersionSetCreator`
- [ ] refactor `LoggerCreator`
- [ ] refactor `BackendCreator`
- [ ] refactor `AuthorizationServerCreator`
- [ ] refactor `ProductApiCreator`
- [ ] refactor `TagApiCreator`
- [ ] refactor `PolicyCreator`
- [ ] refactor `ProductGroupCreator`
- [ ] refactor `SubscriptionCreator`
- [ ] refactor `DiagnosticCreator`
- [ ] refactor `ReleaseCreator`
- [ ] refactor `ProductCreator`
- [ ] refactor `PropertyCreator`
- [x] #730
- [ ] refactor `ApiCreator`
- [ ] refactor `MasterCreator`

**Comment by DeagleGross** [comment]
Moving this to Backlog, because we decided to leave it for the next iteration.

**Comment by DeagleGross** [comment]
@adrianhall - this is a main issue for creator refactoring :)

**Comment by adrianhall** [comment]
This project is now in "maintenance" mode. This means that no new features will be accepted and fixes will be limited to security fixes. We expect to retire the DevOps Resource Kit by the end of 2023. At that time, the DevOps Resource Kit repository will be archived and there will be no further updates.

While you are free to fork the DevOps Resource Kit yourself, we recommend that you migrate to the following products:

* If you are using creator, switch over to using [Bicep](https://learn.microsoft.com/azure/azure-resource-manager/bicep/overview) templates. Bicep is a descriptive language for describing infrastructure, fully supports all features of Azure API Management, and is covered in any support agreement that you have with Azure. You can find bicep modules and examples for handling API Management APIs at https://github.com/azure-samples/api-management-sample-apis.
* If you are using extractor, switch your pipelines to use [APIOps](https://github.com/azure/apiops). APIOps applies the concepts of GitOps to API deployments. It is faster and more flexible than the DevOps Resource Kit.
