### ISSUE TITLE
Multiple bugs in Extractor - looks to be caused by refactor

### ISSUE THREAD

**Issue by shannonvince** [Azure/azure-api-management-devops-resource-kit#627]
I'm new to using these tools, but it looks like the refactor of the Extractor introduced a few errors:
1. Extractor no longer takes the --extractorConfig param successfully, but it is now required. Whether I try to use the extractor config file or the separate params, I see this error:
	

> Error occured: Object reference not set to an instance of an object.
> 	System.NullReferenceException: Object reference not set to an instance of an object.
> 	   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Commands.Applications.ExtractApplicationCommand.ExecuteCommand() in C:\Users\shannon.vince\source\repos\azure-api-management-devops-resource-kit\src\ArmTemplates\Commands\Applications\ExtractApplicationCommand.cs:line 44
> 	[11:22:21 ERR] Azure API Management DevOps Resource toolkit finished with an error...
> 	System.NullReferenceException: Object reference not set to an instance of an object.
> 	   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Commands.Applications.ExtractApplicationCommand.ExecuteCommand() in C:\Users\shannon.vince\source\repos\azure-api-management-devops-resource-kit\src\ArmTemplates\Commands\Applications\ExtractApplicationCommand.cs:line 44
> 	   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Commands.Abstractions.CommandLineApplicationBase.<.ctor>b__0_0() in C:\Users\shannon.vince\source\repos\azure-api-management-devops-resource-kit\src\ArmTemplates\Commands\Abstractions\CommandLineApplicationBase.cs:line 14
> 	   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass126_0.<OnExecute>b__0() in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.cs:line 505
> 	   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args) in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.cs:line 611
> 	   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Program.Main(String[] args) in C:\Users\shannon.vince\source\repos\azure-api-management-devops-resource-kit\src\ArmTemplates\Program.cs:line 44

I worked around this by just going in and hard coding my config file name, just to see if that would fix my errors, but immediately hit another:
	- It is no longer successfully creating the template - it just throws an error every time
	

> Extracting global service policy from service
> 	[11:34:02 ERR] Error occured: The method or operation is not implemented.
> 	System.NotImplementedException: The method or operation is not implemented.
> 	   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Extractor.EntityExtractors.Abstractions.TemplateCreator.CreateEmptyTemplate() in C:\Users\shannon.vince\source\repos\azure-api-management-devops-resource-kit\src\ArmTemplates\Extractor\EntityExtractors\Abstractions\TemplateCreator.cs:line 14
> 	   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Extractor.EntityExtractors.Abstractions.EntityExtractorBase.GenerateEmptyTemplate() in C:\Users\shannon.vince\source\repos\azure-api-management-devops-resource-kit\src\ArmTemplates\Extractor\EntityExtractors\Abstractions\EntityExtractorBase.cs:line 45
> 	   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Extractor.EntityExtractors.Abstractions.EntityExtractorBase.GenerateEmptyPropertyTemplateWithParameters() in C:\Users\shannon.vince\source\repos\azure-api-management-devops-resource-kit\src\ArmTemplates\Extractor\EntityExtractors\Abstractions\EntityExtractorBase.cs:line 50
> 	   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Extractor.EntityExtractors.PolicyExtractor.GenerateGlobalServicePolicyTemplateAsync(String apimname, String resourceGroup, String policyXMLBaseUrl, String policyXMLSasToken, String fileFolder) in C:\Users\shannon.vince\source\repos\azure-api-management-devops-resource-kit\src\ArmTemplates\Extractor\EntityExtractors\PolicyExtractor.cs:line 30
> 	   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Commands.Executors.ExtractorExecutor.GenerateTemplates(ExtractorParameters extractorParameters, String singleApiName, List`1 multipleApiNames, FileNames fileNames, Template apiTemplate) in C:\Users\shannon.vince\source\repos\azure-api-management-devops-resource-kit\src\ArmTemplates\Commands\Executors\ExtractorExecutor.cs:line 226
> 	   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Commands.Executors.ExtractorExecutor.ExecuteGenerationBasedOnExtractorConfiguration() in C:\Users\shannon.vince\source\repos\azure-api-management-devops-resource-kit\src\ArmTemplates\Commands\Executors\ExtractorExecutor.cs:line 123
> 	   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Commands.Applications.ExtractApplicationCommand.ExecuteCommand() in C:\Users\shannon.vince\source\repos\azure-api-management-devops-resource-kit\src\ArmTemplates\Commands\Applications\ExtractApplicationCommand.cs:line 46
> 	[11:34:02 ERR] Azure API Management DevOps Resource toolkit finished with an error...
> 	System.NotImplementedException: The method or operation is not implemented.
> 	   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Extractor.EntityExtractors.Abstractions.TemplateCreator.CreateEmptyTemplate() in C:\Users\shannon.vince\source\repos\azure-api-management-devops-resource-kit\src\ArmTemplates\Extractor\EntityExtractors\Abstractions\TemplateCreator.cs:line 14
> 	   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Extractor.EntityExtractors.Abstractions.EntityExtractorBase.GenerateEmptyTemplate() in C:\Users\shannon.vince\source\repos\azure-api-management-devops-resource-kit\src\ArmTemplates\Extractor\EntityExtractors\Abstractions\EntityExtractorBase.cs:line 45
> 	   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Extractor.EntityExtractors.Abstractions.EntityExtractorBase.GenerateEmptyPropertyTemplateWithParameters() in C:\Users\shannon.vince\source\repos\azure-api-management-devops-resource-kit\src\ArmTemplates\Extractor\EntityExtractors\Abstractions\EntityExtractorBase.cs:line 50
> 	   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Extractor.EntityExtractors.PolicyExtractor.GenerateGlobalServicePolicyTemplateAsync(String apimname, String resourceGroup, String policyXMLBaseUrl, String policyXMLSasToken, String fileFolder) in C:\Users\shannon.vince\source\repos\azure-api-management-devops-resource-kit\src\ArmTemplates\Extractor\EntityExtractors\PolicyExtractor.cs:line 30
> 	   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Commands.Executors.ExtractorExecutor.GenerateTemplates(ExtractorParameters extractorParameters, String singleApiName, List`1 multipleApiNames, FileNames fileNames, Template apiTemplate) in C:\Users\shannon.vince\source\repos\azure-api-management-devops-resource-kit\src\ArmTemplates\Commands\Executors\ExtractorExecutor.cs:line 226
> 	   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Commands.Executors.ExtractorExecutor.ExecuteGenerationBasedOnExtractorConfiguration() in C:\Users\shannon.vince\source\repos\azure-api-management-devops-resource-kit\src\ArmTemplates\Commands\Executors\ExtractorExecutor.cs:line 123
> 	   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Commands.Applications.ExtractApplicationCommand.ExecuteCommand() in C:\Users\shannon.vince\source\repos\azure-api-management-devops-resource-kit\src\ArmTemplates\Commands\Applications\ExtractApplicationCommand.cs:line 46
> 	   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Commands.Abstractions.CommandLineApplicationBase.<.ctor>b__0_0() in C:\Users\shannon.vince\source\repos\azure-api-management-devops-resource-kit\src\ArmTemplates\Commands\Abstractions\CommandLineApplicationBase.cs:line 14
> 	   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass126_0.<OnExecute>b__0() in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.cs:line 505
> 	   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args) in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.cs:line 611
> 	   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Program.Main(String[] args) in C:\Users\shannon.vince\source\repos\azure-api-management-devops-resource-kit\src\ArmTemplates\Program.cs:line 44

	Looks like this was intended to actually initialize the template?

	That was enough errors for me so I just went back to the commit before the refactor ([a562e88](https://github.com/Azure/azure-api-management-devops-resource-kit/commit/a562e8891cad77df8ed0eebc272e85cefd9b4488)), and everything worked great.

**Comment by DeagleGross** [comment]
Hello @shannonvince. Thanks for opening an issue. Sorry for confusing you - we are making a major repo refactoring to get rid of legacy code. Hope it will be released soon.

In order not to confuse end-users we decided to rollback main to the working state (thanks for providing the latest working commit):
- #628 
- #629

I will close this issue for now. If you still have any troubles with using resource-kit, feel free to reopen it.

**Comment by shannonvince** [comment]
Thanks for the quick reply and the fix!
