### ISSUE TITLE
[Creator] missing reference in config file for product groups

### ISSUE THREAD

**Issue by krzysztofwajda** [Azure/azure-api-management-devops-resource-kit#630]
How can I assign existing group for a product in config file ?

**Comment by adrianhall** [comment]
I'm not sure I understand the question.  Without further details on what you are trying to do, I can't answer.

**Comment by krzysztofwajda** [comment]
I can't find the way to configure "Access control" for each APIM Product. I want to assigne existing group to product like in example below, but it looks that is impossible now in creator to do it in any way.

products:
  - name: some-api
    displayName: Some API
    subscriptionRequired: true
    approvalRequired: true
    state: published
    groups:
      - name: "developers"
      - name: "othergroups"

**Comment by adrianhall** [comment]
This is correct.  We currently do not support groups (although groups is on the list of features to be added).  Right now, neither extractor nor creator supports groups.
