### ISSUE TITLE
Improve console user-experience

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/azure-api-management-devops-resource-kit#632]
We should consider providing a nicer UX by using something like [spectre.console](https://github.com/spectreconsole/spectre.console#features) to display nice overviews of the things that we have found and use a progress bar.

![](https://github.com/spectreconsole/spectre.console/raw/main/docs/input/assets/images/example.png)

We should consider using an opt-out/opt-in to simpler logging, though, so that customers can choose to keep it simple if it runs in a CI (for example)

**Comment by tomkerkhove** [comment]
Thoughts on this @adrianhall ?

**Comment by adrianhall** [comment]
This project is now in "maintenance" mode. This means that no new features will be accepted and fixes will be limited to security fixes. We expect to retire the DevOps Resource Kit by the end of 2023. At that time, the DevOps Resource Kit repository will be archived and there will be no further updates.

While you are free to fork the DevOps Resource Kit yourself, we recommend that you migrate to the following products:

* If you are using creator, switch over to using [Bicep](https://learn.microsoft.com/azure/azure-resource-manager/bicep/overview) templates. Bicep is a descriptive language for describing infrastructure, fully supports all features of Azure API Management, and is covered in any support agreement that you have with Azure. You can find bicep modules and examples for handling API Management APIs at https://github.com/azure-samples/api-management-sample-apis.
* If you are using extractor, switch your pipelines to use [APIOps](https://github.com/azure/apiops). APIOps applies the concepts of GitOps to API deployments. It is faster and more flexible than the DevOps Resource Kit.
