### ISSUE TITLE
CREATOR Question - How to do I configure backends as Azure Resource type?

### ISSUE THREAD

**Issue by jeffpriz-3c** [Azure/azure-api-management-devops-resource-kit#633]
When setting up a  config file for the Backends, I can specify a URL and some other pieces, but the Backend that gets generated comes out as Custom URL Type...   The APIs are hosted through App Services on the backend and when we manually configre an APIM to point to those we create them as Azure Resource types.. Curious if/how I need to specify things in the config file to make these match.

**Comment by adrianhall** [comment]
Extractor does not extract backends properly for all API types.  There is an issue for this already.

If you have a specific scenario that doesn't work as is, then please submit that as an issue and we'll take a look and make it work.

**Comment by jeffpriz** [comment]
> Extractor does not extract backends properly for all API types.  There is an issue for this already.
> 
> 
> 
> If you have a specific scenario that doesn't work as is, then please submit that as an issue and we'll take a look and make it work.

@adrianhall My question isn't about the extractor tool.. it's about the creator.  Are you suggesting that this tool isn't appropriate to use for backend template generation?

**Comment by adrianhall** [comment]
If you are writing the configuration files yourself, I would just write the appropriate ARM/Bicep template and use that.  It's not that the tool is inappropriate (I can't say that since you didn't provide any details).  It's just that fine tuning the templates would be better by editing the ARM/bicep files.

**Comment by jeffpriz-3c** [comment]
@adrianhall   Okay, I guess I can't automate the process fully then.  
I guess what more details do you need? 

I want to create a backend that is Azure Resource backend and not a Custom URL backend.  How do I configure the config file to tell the creator tool that the backend that I am specifying should generate the ARM template necessary to generate a Azure Resource type backend?
