### ISSUE TITLE
Creator Not creating endpoints in arm template

### ISSUE THREAD

**Issue by zbarker2** [Azure/azure-api-management-devops-resource-kit#659]
I might be interpreting this wrong, but providing the creator with an openapi spec should have it create endpoints in the api.template.json correct? Right now it is just adding it as a value and one giant string. The policies are being created but the endpoints themselves are not. I am supplying it with a local OAS3 .yaml file

**Comment by adrianhall** [comment]
Can you please provide additional information:

1. Version of the DevOps Resource Kit you are using
2. Command line you executed
3. Any configuration files associated with the request

We currently do not have enough information to proceed with a diagnosis.

**Comment by adrianhall** [comment]
Lack of information for two weeks - closing.
