### ISSUE TITLE
Extractor - namedValues & loggers name template issue

### ISSUE THREAD

**Issue by sakowiczm** [Azure/azure-api-management-devops-resource-kit#661]
Got latest repo content - used Extractor to get master template - namedValues & loggers contain `\\` before template name:

![image](https://user-images.githubusercontent.com/721228/159969816-316c7d2e-d456-4e20-beb9-babf10faffd0.png)

![image](https://user-images.githubusercontent.com/721228/159969770-01255e45-a940-46c2-bb6b-525a222b354c.png)

Also when specifying the `linkedTemplatesBaseUrl` parameter from the command line - a URL now needs to end with '/' otherwise deployment is going to fail.

**Comment by DeagleGross** [comment]
Hello @sakowiczm,
Will try to look at it in a few days.

**Comment by DeagleGross** [comment]
@sakowiczm sorry for such a delay.
I have refactored master-template-extractor in #677, so the issue disappeared by iteself.
![image](https://user-images.githubusercontent.com/31598696/163601667-93e81dad-24f3-4057-a264-239e51028624.png)

Regarding the `linkedTemplatesBaseUrl` - I didn't get your questions\bug-report. Is it happening at ARM-deployment or during resource-kit execution? In any case I would be happy, if you could create a separate issue for that trouble - it will be easier for us to fix things one by one (take advantage of github template to fill in all important information).

Thanks!
