### ISSUE TITLE
API artifact not deploying in APIM Instance

### ISSUE THREAD

**Issue by tagoreanand** [Azure/azure-api-management-devops-resource-kit#664]
Hi,

I'm using APIM resource toolkit software to deploy the API into APIM instance. The pipeline is running successfully(generated ARM templates and make it an artifact then deploying into APIM) but API not appearing on the API Management service.
Please help me to solve this issue.

**Comment by tagoreanand** [comment]
Hi, Can you please let me know the support email id - so that we can schedule a call and discuss it. Please make this as priority. thank you.

**Comment by adrianhall** [comment]
Thank you for your report.  Can you please include the following information:

1. What version of the DevOps Resource Toolkit are you using?
2. What configuration file were you using?  Include the contents (minus any secrets)
3. What did you actually run?
4. What logs were produced when you ran the tooling?

**Comment by adrianhall** [comment]
Closed due to lack of information for 2 weeks with no update from OP
