### ISSUE TITLE
[creator] Generated master.template.json contains dependsOn to non-existing *-subsequent.api.template.json

### ISSUE THREAD

**Issue by kboro** [Azure/azure-api-management-devops-resource-kit#673]
## Describe the bug

'Creator' tool generates initial and subsequent api.template.json files for all APIs except one where only "TranslationsAPI.api.template.json" is created. So TranslationsAPI is only API which doenst have initial and subsequent files generated.

However in base-master.template.json file there is dependsOn for non exisitng : "TranslationsAPI-SubsequentAPITemplate":

`"dependsOn": [
        "[resourceId('Microsoft.Resources/deployments', 'globalServicePolicyTemplate')]",
        "[resourceId('Microsoft.Resources/deployments', 'productsTemplate')]",
        "[resourceId('Microsoft.Resources/deployments', 'backendsTemplate')]",
        "[resourceId('Microsoft.Resources/deployments', 'authorizationServersTemplate')]",
        "[resourceId('Microsoft.Resources/deployments', 'tagTemplate')]",
        "[resourceId('Microsoft.Resources/deployments', 'TranslationsAPI-SubsequentAPITemplate')]"
      ]`

## What version of the DevOps Resource Kit is being used?

* V0.7

## What version of dotnet are you running?

* 6.0.101

## What platform (OS and version) are you running on?

MacOS, Ubuntu

## The command line you are running?

dotnet ./src/apimtemplate.dll create --configFile ./apim.yml --apimNameValue destination-apim

## The configuration file being used?

[apim.yml.txt](https://github.com/Azure/azure-api-management-devops-resource-kit/files/8459623/apim.yml.txt)

## Expected behavior

base-master.template.json doesnt create dependency "dependsOn": for non exisitng 'TranslationsAPI-SubsequentAPITemplate'

## Screenshots

<img width="1256" alt="image" src="https://user-images.githubusercontent.com/28050787/162633186-970d925e-abc0-4618-ac57-ab7f66a1ba0f.png">

## Error Log from CD Pipeline

During ARM deployment of "base-master.template.json" following error appears:

<img width="1209" alt="image" src="https://user-images.githubusercontent.com/28050787/162633913-24fdf79f-6e7c-49c8-b172-386ea2cc3a64.png">

**Comment by adrianhall** [comment]
Thank you for your input on the creator tool.  We are currently looking at the future of the creator tool and would like your feedback.  Please could you fill in the survey at https://forms.office.com/r/w7rQp88NwH - your input is appreciated.

**Comment by zcarroll4** [comment]
Any updates on this?

Having similar issue.

**Comment by adrianhall** [comment]
No update, and no timeline for a fix either.

**Comment by adrianhall** [comment]
This project is now in "maintenance" mode. This means that no new features will be accepted and fixes will be limited to security fixes. We expect to retire the DevOps Resource Kit by the end of 2023. At that time, the DevOps Resource Kit repository will be archived and there will be no further updates.

While you are free to fork the DevOps Resource Kit yourself, we recommend that you migrate to the following products:

* If you are using creator, switch over to using [Bicep](https://learn.microsoft.com/azure/azure-resource-manager/bicep/overview) templates. Bicep is a descriptive language for describing infrastructure, fully supports all features of Azure API Management, and is covered in any support agreement that you have with Azure. You can find bicep modules and examples for handling API Management APIs at https://github.com/azure-samples/api-management-sample-apis.
* If you are using extractor, switch your pipelines to use [APIOps](https://github.com/azure/apiops). APIOps applies the concepts of GitOps to API deployments. It is faster and more flexible than the DevOps Resource Kit.
