### ISSUE TITLE
Make it possible to set custom APIM-apiversion and ARM-apiversion

### ISSUE THREAD

**Issue by DeagleGross** [Azure/azure-api-management-devops-resource-kit#678]
In issue #665 there was a trouble with arm-api-version. Even if we mess it with the versions, it would be cool to allows users pick the version they want to use.

# Implementation
I would do it with injectable `ApplicationSettingsStorage` class, that contains all versions. From that moment every ApiClient could get that settings.

**Comment by adrianhall** [comment]
This project is now in "maintenance" mode. This means that no new features will be accepted and fixes will be limited to security fixes. We expect to retire the DevOps Resource Kit by the end of 2023. At that time, the DevOps Resource Kit repository will be archived and there will be no further updates.

While you are free to fork the DevOps Resource Kit yourself, we recommend that you migrate to the following products:

* If you are using creator, switch over to using [Bicep](https://learn.microsoft.com/azure/azure-resource-manager/bicep/overview) templates. Bicep is a descriptive language for describing infrastructure, fully supports all features of Azure API Management, and is covered in any support agreement that you have with Azure. You can find bicep modules and examples for handling API Management APIs at https://github.com/azure-samples/api-management-sample-apis.
* If you are using extractor, switch your pipelines to use [APIOps](https://github.com/azure/apiops). APIOps applies the concepts of GitOps to API deployments. It is faster and more flexible than the DevOps Resource Kit.
