### ISSUE TITLE
Multiple versions of API not reflecting

### ISSUE THREAD

**Issue by tagoreanand** [Azure/azure-api-management-devops-resource-kit#685]
Hi,

We are using APIM resource toolkit(0.7) software to deploy an API and created multiple config files for different versions of same api.
We are using storage account to store the ARM templates. As well, at a time we ran the code to store multiple versions of ARM templates in a single container.
When we execute v1, the api is getting deployed under v1
when we execute v2, the api is getting deployed as v2 and removing v1 but in storage account I can see both v1 and v2 ARM templates

Kindly help me on it exactly what I'm missing(snippet code/something else) here to deploy same api in different versions. Thank You.

**Comment by adrianhall** [comment]
How did you generate the templates?
What do the templates look like?
How are you attempting to deploy them?

**Comment by tagoreanand** [comment]
1. I'll generate the templates using Creator pipeline
2. Templates will generate in JSON format and each parameter creates dedicated template along with master and parameter templates
3. The Generated templates will be pushed to Storage account than it makes the artifact and deploy into an APIM

**Comment by adrianhall** [comment]
We actually need the command lines you are using and the configuration files you are using.  Right now, I'm guessing as to what you are doing, which means I am guessing at potential solutions.

**Comment by adrianhall** [comment]
Closing due to lack of information.
