### ISSUE TITLE
Service and some shared templates not generated by extract tool

### ISSUE THREAD

**Issue by JCallico** [Azure/azure-api-management-devops-resource-kit#686]
**Summary**
The following resources are configured but do not produce templates:

* `Microsoft.ApiManagement/service`
* `Microsoft.ApiManagement/service/identityProviders`

**Description:**
When trying to extract the ARM templates, the service template and some shared templates, like the identity providers for example, are not generated resulting in not been able to provision new APIM instances or deploy important features.

I have verified that release 0.7 presents the same problem but I am not sure when this problem started to appear since some ARM templates previously generated (not sure what version was used) do not present this problem.

**DevOps Resource Kit version:**
1.0.0-beta.2 release binaries

**dotnet version:**
6.0.100-rc.2.21505.57

**OS and version:**
Windows 11 Pro, build 22000.651

**Command:**
`.\ArmTemplates.exe extract --sourceApimName "my-apim-instance-dev" --destinationApimName "my-apim-instance-ci" --resourceGroup "my-apim-instance-dev-rg" --fileFolder "C:\Temp\my-apim-instance-ci" --splitAPIs true --linkedTemplatesBaseUrl "https://somewhere.blob.core.windows.net/apim-templates" --linkedTemplatesSasToken "token-here" --policyXMLBaseUrl "https://somewhere.blob.core.windows.net/apim-templates/policies" --policyXMLSasToken "token-here" --baseFileName "apim" --paramServiceUrl true --paramNamedValue true --paramApiLoggerId true --paramLogResourceId true --paramNamedValuesKeyVaultSecrets true --paramBackend true`

**API Management Instance set up:**
SKU: Developer
Full admin rights to the service: yes
Service in a VNET: issue occurs with and without Vnet.

**Comment by JCallico** [comment]
**Description:**
When trying to extract the ARM templates, the service template and some shared templates, like the identity providers for example, are not generated resulting in not been able to provision new APIM instances or deploy important features.

I have verified that release 0.7 presents the same problem but I am not sure when this problem started to appear since some ARM templates previously generated (not sure what version was used) do not present this problem.

**DevOps Resource Kit version:**
1.0.0-beta.2 release binaries

**dotnet version:**
6.0.100-rc.2.21505.57

**OS and version:**
Windows 11 Pro, build 22000.651

**Command:**
`.\ArmTemplates.exe extract --sourceApimName "my-apim-instance-dev" --destinationApimName "my-apim-instance-ci" --resourceGroup "my-apim-instance-dev-rg" --fileFolder "C:\Temp\my-apim-instance-ci" --splitAPIs true --linkedTemplatesBaseUrl "https://somewhere.blob.core.windows.net/apim-templates" --linkedTemplatesSasToken "token-here" --policyXMLBaseUrl "https://somewhere.blob.core.windows.net/apim-templates/policies" --policyXMLSasToken "token-here" --baseFileName "apim" --paramServiceUrl true --paramNamedValue true --paramApiLoggerId true --paramLogResourceId true --paramNamedValuesKeyVaultSecrets true --paramBackend true`

**API Management Instance set up:**
SKU: Developer
Full admin rights to the service: yes
Service in a VNET: issue occurs with and without Vnet.

**Comment by adrianhall** [comment]
Do you have a canonical list of things that are not extracted?  

We can, of course, just extract the identity providers, but we'll bump into the next thing and the next thing.  It would be better to get a list of what's not working for you.

**Comment by JCallico** [comment]
So far I am missing the service ("type": "Microsoft.ApiManagement/service") and identity providers ("type": "Microsoft.ApiManagement/service/identityProviders") templates.

Also on release 0.7 the top level groups were missing as well ("type": "Microsoft.ApiManagement/service/groups") but I noticed that beta 2 now generates the groups template (but doesn't link this template). I was going to open a new bug for this issue.

**Comment by JCallico** [comment]
> Do you have a canonical list of things that are not extracted?
> 
> We can, of course, just extract the identity providers, but we'll bump into the next thing and the next thing. It would be better to get a list of what's not working for you.

See below, so far missing service and identity providers.

**Comment by adrianhall** [comment]
Please open a new issue for the service/groups not being linked.  We can handle that one separately.

**Comment by f-alizada** [comment]
Hello @JCallico.
Two PRs were merged recently which introduced extraction of 

- Microsoft.ApiManagement/service [PR](https://github.com/Azure/azure-api-management-devops-resource-kit/pull/760)
- Microsoft.ApiManagement/service/identityProviders [PR](https://github.com/Azure/azure-api-management-devops-resource-kit/pull/747)

Please feel free to open a new bug in case you will face problems with those two extracted services/resources, or feature request. 

Identity providers resources are available in [1.0.0-beta.7](https://github.com/Azure/azure-api-management-devops-resource-kit/releases/tag/1.0.0-beta.7)
Microsoft.ApiManagement/service is available in main branch and will be available in future releases. 

Closing the issue, since two resources are covered and merged. 
Best regards
