### ISSUE TITLE
[Creator] parameter file generated outside of outputLocation

### ISSUE THREAD

**Issue by nbarrasson** [Azure/azure-api-management-devops-resource-kit#690]
## Describe the bug

The parameter file is generated outside of the output directory with a name composed of outputLocation+apimServiceName+-parameters.json
Only the template file is filed in the correct directory.

## What version of the DevOps Resource Kit is being used?

Compiled from source as of 04/20

## What version of dotnet are you running?

3.1.418

## What platform (OS and version) are you running on?
WSL 2

## The command line you are running?

apim-templates create --configFile expense.yml

## The configuration file being used?

version: 0.0.1
apimServiceName: xxxxxxxx
apis:
    - name: expense-apiops
      displayName: "Expense APIOps"
      type: https
      suffix: expense-apiops
      expense-apiops-serviceUrl: https://xxxxxxxxxxxx/expenses
      openApiSpec: swagger.json
      subscriptionRequired: false
      products: starter, unlimited
outputLocation: templates

## How is your API Management Instance set up?

Dev sku
External vnet integration

## What logs (if any) were produced?

* Feel free to provide a link to a gist if needed.

**Comment by nbarrasson** [comment]
![Capture d’écran 2022-04-20 203845](https://user-images.githubusercontent.com/39596042/164300078-b67f4fd0-580c-4467-9ff4-4b8ebfc6cc27.jpg)

**Comment by nbarrasson** [comment]
Tested with release 1.0.0-beta.2 on Windows.
Same behaviour.

**Comment by adrianhall** [comment]
... which is wierd because there were no creator changes between 1.0.0-beta.1 and 1.0.0-beta.2

**Comment by ayusmadi** [comment]
This is what I get when I set `outputLocation: templates`
```
templatesxz-98a-dev-apim-master.template.json                            
templatesxz-98a-dev-apim-parameters.json                                 
templates\myApi-getId.api.template.json
```

**Comment by f-alizada** [comment]
Hello @nbarrasson, thank you for raising the issue. 
PR #732 was merged into main branch which was resolving this issue, hence closing the bug. 
Please feel free to reopen the issue or create a new one in case you will be facing similar behaviour on main branch or in upcoming release 1.0.0-beta.6.
