### ISSUE TITLE
Create Wiki and move all documentation there

### ISSUE THREAD

**Issue by DeagleGross** [Azure/azure-api-management-devops-resource-kit#695]
I would prefer creating wiki for the repo instead of maintaining a lot of markdown files in the source control with links from one to another

**Comment by tomkerkhove** [comment]
I'd personally prefer not to do this, though, because that decreases the possibility to contributions as you cannot use PRs for the wiki.

**Comment by DeagleGross** [comment]
@tomkerkhove, @adrianhall shares the same thoughts, so I will close this issue now. Thanks for sharing your opinion!
