### ISSUE TITLE
Implement auto-upload to existing storage-account instance for further easier ARM deployment 

### ISSUE THREAD

**Issue by DeagleGross** [Azure/azure-api-management-devops-resource-kit#700]
## Is your feature request related to a problem? Please describe
It is hard to test (and probably to use) resource-kit with the linked template now. After googling I have found a tutorial to upload all the extracted files to *Azure Storage* and after that run the ARM deployment against master-linked template. The hard step is to upload all the files to the azure storage, which could be implemented easily.

## Describe the solution you'd like
After extraction there is an information about output-directory. What we have to do is to upload all output files to the azure storage (probably in a unique-named folder, or the folder name inside storaage users have specified)

## Describe alternatives you've considered
Probably there could be any other integration, but it is up to discuss

**Comment by adrianhall** [comment]
This project is now in "maintenance" mode. This means that no new features will be accepted and fixes will be limited to security fixes. We expect to retire the DevOps Resource Kit by the end of 2023. At that time, the DevOps Resource Kit repository will be archived and there will be no further updates.

While you are free to fork the DevOps Resource Kit yourself, we recommend that you migrate to the following products:

* If you are using creator, switch over to using [Bicep](https://learn.microsoft.com/azure/azure-resource-manager/bicep/overview) templates. Bicep is a descriptive language for describing infrastructure, fully supports all features of Azure API Management, and is covered in any support agreement that you have with Azure. You can find bicep modules and examples for handling API Management APIs at https://github.com/azure-samples/api-management-sample-apis.
* If you are using extractor, switch your pipelines to use [APIOps](https://github.com/azure/apiops). APIOps applies the concepts of GitOps to API deployments. It is faster and more flexible than the DevOps Resource Kit.
