### ISSUE TITLE
output for representation missing escape char for application/json-patch+json

### ISSUE THREAD

**Issue by bengimblett** [Azure/azure-api-management-devops-resource-kit#707]
## Where did you encounter this bug?

* [x] Extractor
* [] Creator

## Describe the bug

Escape char missing for the json-patch+json content type

     "properties": {
        "templateParameters": [],
        "description": "Gets a list of twins where the property of a given name equals the value given",
        "request": {
          "queryParameters": [],
          "headers": [],
          "representations": [
            {
              "contentType": "application/json-patch+json",
              "sample": "[\r\n  {\r\n    \"PropertyName\": \"string\",\r\n    \"PropertyValue\": \"string\"\r\n  }\r\n]",
              "schemaId": "627e6137217d2018f4d6cec8",
              "typeName": "AdtPropertyQueryClauseArray"
            },

## What version of the DevOps Resource Kit is being used?

Latest

## What version of dotnet are you running?

n/a

## What platform (OS and version) are you running on?

Windows

## The command line you are running?
VSCode

## How is your API Management Instance set up?

dev, admin

## What logs (if any) were produced?

n/a

## Expected behaviour

Escape char to be added

## Screenshots

![api-definition](https://user-images.githubusercontent.com/4322131/168312671-4a6fead1-8390-4de2-b1b6-b473ba296421.png)
![code](https://user-images.githubusercontent.com/4322131/168312674-22ef1ffd-eb4b-4dec-8c5f-ba48cc53776a.png)
![template-missing-escape](https://user-images.githubusercontent.com/4322131/168312676-4aa0c9d0-ef76-4f3a-96b6-e8fdab3d795e.png)

Possibly linked to 
https://github.com/Azure/azure-api-management-devops-resource-kit/pull/598

**Comment by bengimblett** [comment]
Latest from 0.7 (latest label) here https://github.com/Azure/azure-api-management-devops-resource-kit/releases

**Comment by DeagleGross** [comment]
Hey @bengimblett, can you, please, try latest **beta** version? [Releases page](https://github.com/Azure/azure-api-management-devops-resource-kit/releases); [1.0.0-beta.4](https://github.com/Azure/azure-api-management-devops-resource-kit/releases/tag/1.0.0-beta.4)
