### ISSUE TITLE
Single API extract does not create tags resource [template]

### ISSUE THREAD

**Issue by bengimblett** [Azure/azure-api-management-devops-resource-kit#711]
## Where did you encounter this bug?

* [x] Extractor
* [] Creator

## Describe the bug

The tags for a single api ,in this example tags for api operation, are not created, no template is generated for the tags, when a single API is used for extract args and that api has ops that are tagged.

## What version of the DevOps Resource Kit is being used?

https://github.com/Azure/azure-api-management-devops-resource-kit/tree/main/src

## What version of dotnet are you running?

n/a

## What platform (OS and version) are you running on?

win

## The command line you are running?

extract --sourceApimName beigmdemoapim --destinationApimName begimdemoapim-dest --resourceGroup begim-demo-rg --fileFolder .\extract --apiName petstore2 --linkedTemplatesBaseUrl https://begimdemorg864a.blob.core.windows.net/templates

## The configuration file being used?

n/a

## How is your API Management Instance set up?

n/a

## What logs (if any) were produced?

n/a

## Expected behavior

tags template is output where tags exist against single api operations

## Additional context

Probably this is the issue

TagExtractor.cs - starting L124 - the code doesnt match the comment/expectation

I think the logical operator is incorrect for the if statement and "tagOriginalName" (string) should be used on L125 not "tag" (object)

**Comment by f-alizada** [comment]
@bengimblett Hello. 
Thank you for submitting issue.
The fix is already merged into the main branch and will be available in upcoming releases. 
Please feel free to reopen the bug or create new one if you will face same issue from main branch or future releases. 
Best regards
