### ISSUE TITLE
Tags from APIs attached to product

### ISSUE THREAD

**Issue by f-alizada** [Azure/azure-api-management-devops-resource-kit#717]
## Where did you encounter this bug?

* [x] Extractor
* [ ] Creator

## Describe the bug

Generated products.template.json contains resources product tags, which are fetched from the APIs.

Example 
```
Product (productname) has three api (api1, api2, api3)
api1 has tag1
api2 has tag2
api3 has tag1
```

Resulting products template will have the resources:
```
{
      "apiVersion": "2021-08-01",
      "type": "Microsoft.ApiManagement/service/products/tags",
      "name": "[concat(parameters('apimServiceName'), '/productname/tag1')]",
      "dependsOn": [
        "[resourceId('Microsoft.ApiManagement/service/products', parameters('apimServiceName'), 'productname')]"
      ],
      "properties": {
        "displayName": "test"
      }
}
```
It will be repeated for each tag from API per product, also apart from that the product template will be invalid because of having two identical resources product tags.

## What version of the DevOps Resource Kit is being used?

1.0.0-beta.4 and main branch

**Comment by Mivaweb** [comment]
Any news on this when this will be fixed? We have currently the issue that our product template is invalid due to duplicated tags.

**Comment by adrianhall** [comment]
We are working through the bugs, pretty much in the order that they occur in the backlog (see Projects).  We are prioritizing extractor bugs before features and before the new creator.  Having said that, I can't give you a date when it will hit a release.

**Comment by f-alizada** [comment]
Hello @Mivaweb .
PR solving this issue was merged into main branch. Currently product tags will be not be populated from api tags assigned to product, but from product tags. 
Please feel free to reopen the issue if the issue is still reproducible on main branch or upcoming releases.
