### ISSUE TITLE
Deletion of API Process

### ISSUE THREAD

**Issue by tagoreanand** [Azure/azure-api-management-devops-resource-kit#719]
Hi Team,

I'm using APIM resource toolkit software(v0.7) to deploy an API and I want to know how to decommission/delete the same API

**Comment by adrianhall** [comment]
We don't believe that removing an API should be automated - it's a very destructive process with little in the way of rollback.

Thus, you use the normal API removal process:
* Go onto the Azure Portal and remove it there.
* Use the Azure CLI or Azure PowerShell cmdlets to remove the API

Both work.
