### ISSUE TITLE
Extractor not escaping square brackets in response sample

### ISSUE THREAD

**Issue by cschrammel** [Azure/azure-api-management-devops-resource-kit#721]
## Where did you encounter this bug?

* [] Extractor

## Describe the bug

The extractor is not escaping square brackets for when the response of an API produces an array type.  For example, the output for an api template contained (not valid ARM):

"sample": "[\r\n  {\r\n    \"line\": \"string\",\r\n    \"line\": true\r\n  }\r\n]",

and not

"sample": "/[\r\n  {\r\n    \"line\": \"string\",\r\n    \"line\": true\r\n  }\r\n/]",

## What version of the DevOps Resource Kit is being used?

[1.0.0-beta.4](https://github.com/Azure/azure-api-management-devops-resource-kit/releases/tag/1.0.0-beta.4)

## What version of dotnet are you running?

* Run `dotnet --version` to find out!

6.0.202

## What platform (OS and version) are you running on?

* If Windows, indicate if you are running on WSL.

Windows

## The command line you are running?

ArmTemplates.exe extract --sourceApimName replaced --destinationApimName replaced --resourceGroup replaced --fileFolder $(System.DefaultWorkingDirectory)\apis\${{ parameters.apiName }} --apiName ${{ parameters.apiName }} --paramServiceUrl true --paramNamedValue true --paramBackend true --baseFileName api

## How is your API Management Instance set up?

* What SKU is being used (as the source for extractor or destination for creator)?
* Do you have full admin rights to the service?
* Is the service in a VNET?  If so, describe how it is configured?

## What logs (if any) were produced?

* Feel free to provide a link to a gist if needed.

## Expected behavior

I'd expect square brackets to be escaped with a slash where appropriate so that the ARM template can be deployed without manually changing it first.

**Comment by f-alizada** [comment]
Hello @cschrammel.
Thank you for raising the issue. 
May I clarify what is the content type value for the response in the provided example?

**Comment by cschrammel** [comment]
The content type is "application/json". 

Thanks

**Comment by f-alizada** [comment]
Thank you for clarification @cschrammel.
Similar problem was reported recently as well. #707  
The fix was already merged into main branch and will be released in 1.0.0-beta.5.
Please see the PR: #710 

Closing the issue since it is already merged, please feel free to reopen it in case you will face the same behaviour of generated template in upcoming 1.0.0-beta.5 or main branch.

Thank you!
