### ISSUE TITLE
Cant deploy first template in example after extractor

### ISSUE THREAD

**Issue by enterpriseSoftware** [Azure/azure-api-management-devops-resource-kit#729]
## Where did you encounter this bug?

* [] Extractor

## Describe the bug

The Error.
##[error]ResourceNotFound: The Resource 'Microsoft.ApiManagement/service/APIMDEV1' under resource group 'FuncAppApiRg2' was not found

The documentation list the order in which the templates should deployed as follows.
- Products.template.json
- Tags.template.json
- namedValues.template.json
- apis.template.json
- globalServicePolicy.template.json

** Please note I have 8 files after running extractor.
** The instructions say to deploy the Products.template.json first.  My pipeline failed on this one attempt.
** is the documentatin up to date?
** example yaml pipeline anywhere?

My Yaml

- task: AzureResourceGroupDeployment@2
      displayName: 'Deploy to new RG'
      inputs:
        azureSubscription: 'TimKelleyServiceConnection'
        resourceGroupName: '${{ parameters.resourceGroup }}'
        location: '${{ parameters.location }}'
        csmFile: '$(System.ArtifactsDirectory)/APiM/build/apim_templates/APIMTimKelley-products.template.json' 
        csmParametersFileLink: '$(System.ArtifactsDirectory)/APiM/build/apim_templates/APIMTimKelley-parameters.json' 
        overrideParameters: '-apimServiceName APIMDEV1'
        deploymentMode: Incremental

 dotnet --version 6.0.202

Extract settings
{
    "sourceApimName": "APIMTimKelley",    
    "destinationApimName": "APIMTimKelleyDEV",
    "resourceGroup": "FuncAppApiRg2",
    "fileFolder": "./"
    
}

**Comment by adrianhall** [comment]
Please define "latest" for the DevOps Resource Kit.  We have a beta version and a GA version and they are very different right now.

**Comment by adrianhall** [comment]
The error indicates that the APIMDEV1 does not exist.  The current 1.0.0-betas do not create the resource for you - you need to create the resource as a target for the settings.
