### ISSUE TITLE
deploying apim arm template that have policy reference file  using powershell New-AzResourceGroupDeployment return - The provided link  is malformed. (Code:ValidationError)a  

### ISSUE THREAD

**Issue by liorklein** [Azure/azure-api-management-devops-resource-kit#734]
I am trying to deploy apim product that contains policy 
The arm template created bt the extractor tool 
create the following file 
 "properties": {
        "value": "[concat(parameters('PolicyXMLBaseUrl'), '/policy.xml')]",
        "format": "rawxml-link"
      },
Our dev-ops pipeline is on premise and i want to set the "PolicyXMLBaseUrl" param as a local folder  as created by the extractor tool 
for example : c:\somefolder\policies\tracing-sandbox-productPolicy.xml
but it doesnt seem to be  working and i always get the following error 
Status Message: One or more fields
     | contain incorrect values: (Code: ValidationError)  - The provided link  is malformed. (Code:ValidationError)   CorrelationId:
     | 91e538b9-c59a-4a9a-993c-26b16c23aedd

is it possible to use local path ?

**Comment by DeagleGross** [comment]
Hello @liorklein, thanks for your issue.

Can you, please, show the output files layout? Is there a `policies` folder created locally? What is your input configuration?
Please, take advantage of issue template and feel in all the information.

**Comment by liorklein** [comment]
I will make my question simpler
 "properties": {
        "value": "[concat(parameters('PolicyXMLBaseUrl'),
'/vessel-schedule-sandbox-productPolicy.xml')]",
        "format": "rawxml-link"
      },
the extractor create all reference to policies files from type
:"rawxml-link" .
doest this type support local path like
"C:\servicetemplate\policies\policy.xml or only url  ( which mean my all
repo need to be accessible in the internet) . currently i am using
on-premise git solution ?


______________________________
ליאור קליין
LIOR KLEIN
***@***.***

**Comment by adrianhall** [comment]
Hey @liorklein - currently, we don't support local path.  When deploying via ARM, the ARM deployment needs access to the policy file - not the PowerShell script you are using to run the deployment.  As a result, it needs to be uploaded to storage.

We do have a separate issue #700 to support auto-upload of policy files to Azure Storage for this purpose, so I'll close this one.
