### ISSUE TITLE
Feature Request: Parameterize API name in extractor

### ISSUE THREAD

**Issue by trishank87** [Azure/azure-api-management-devops-resource-kit#744]
### Scenario

Can we parameterize api name which will be a boolean parameter.
This will help us to create multiple api instances of the same api inside single api management instance

**Comment by adrianhall** [comment]
I'm not sure I understand the requirement.  How would you use this in a practical scenario?

**Comment by trishank87** [comment]
I have a scenario in which i want to create two apis using same arm templates one for prod and other for staging inside same apim instance. So the only difference here is when i deploy this templates the back-end id data will be different.
This scenario is similar to slots feature of function app.

**Comment by adrianhall** [comment]
Got it - the problem we have is that when we extract a lot of APIs, each API will be extracted with its own parameter, which will lead to a large variable pollution in the parameters.

I think this only works when extracting a single API.  Would that be your view as well?

**Comment by trishank87** [comment]
yes correct.

**Comment by adrianhall** [comment]
This project is now in "maintenance" mode. This means that no new features will be accepted and fixes will be limited to security fixes. We expect to retire the DevOps Resource Kit by the end of 2023. At that time, the DevOps Resource Kit repository will be archived and there will be no further updates.

While you are free to fork the DevOps Resource Kit yourself, we recommend that you migrate to the following products:

* If you are using creator, switch over to using [Bicep](https://learn.microsoft.com/azure/azure-resource-manager/bicep/overview) templates. Bicep is a descriptive language for describing infrastructure, fully supports all features of Azure API Management, and is covered in any support agreement that you have with Azure. You can find bicep modules and examples for handling API Management APIs at https://github.com/azure-samples/api-management-sample-apis.
* If you are using extractor, switch your pipelines to use [APIOps](https://github.com/azure/apiops). APIOps applies the concepts of GitOps to API deployments. It is faster and more flexible than the DevOps Resource Kit.
