### ISSUE TITLE
Bug: Gateway API's don't get extracted

### ISSUE THREAD

**Issue by DSpirit** [Azure/azure-api-management-devops-resource-kit#748]
### Report

When extracting a single API with a self-hosted gateway, adding the switch "--extractGateways" doesn't work as expected.

### Expected Behavior

Not only the gateway.template.json file gets created but also the gatewaysApis.template.json file.

### Actual Behavior

There are indeed App Gateways extracted, but the GatewayAPI templates are not.

### Steps to Reproduce the Problem

1. Create an API with a self-hosted gateway attached.
``` dotnet run extract --project .\src\ArmTemplates\ArmTemplates.csproj --sourceApimName *** --destinationApimName *** --resourceGroup *** --apiName null-api --extractGateways true --fileFolder .```

Outcome:
![image](https://user-images.githubusercontent.com/12340489/173616489-31860956-c490-4ba9-add2-6ac6834638e3.png)

### Component

Extractor

### DevOps Resource Kit Version

1.0.0-beta.6

### .NET Version

6.0.203

### OS

Windows 11

### Configuration

Configuration:

```yaml
version: 0.0.1
apimServiceName: example-apim-name
```

### Logs

```shell
example
```

### Contact Details

wendelin.niesl@gmail.com

**Comment by DSpirit** [comment]
Obviously, this was just forgotten in the extractor. I've created a Pull Request here: #751  
@f-alizada @adrianhall

**Comment by adrianhall** [comment]
Thanks for the PR - we'll review it as soon as we can.
