### ISSUE TITLE
Bug: Microsoft.ApiManagement/service/diagnostics is part of the service level template and not as a standalone template 

### ISSUE THREAD

**Issue by liorklein** [Azure/azure-api-management-devops-resource-kit#749]
### Report

"Microsoft.ApiManagement/service/diagnostics" type  is part of the service level template , and not as a standalone template although no diagnostic setting are in service  level , all setting are inherit from the all services diagnostics settings .

### Expected Behavior

In case no override of the diagnostic setting in a service level   but only inherit from the "all services" level ,
the "Microsoft.ApiManagement/service/diagnostics" should be a seperate template file and not as part of the service level 

### Actual Behavior

"Microsoft.ApiManagement/service/diagnostics" are part of the service template level 

### Steps to Reproduce the Problem

1.extract service 
2.
3.
...

### Component

Extractor

### DevOps Resource Kit Version

latest - not beta  

### .NET Version

6

### OS

windows 

### Configuration

Configuration:

```yaml
version: 0.0.1
apimServiceName: example-apim-name
```

### Logs

```shell
example
```

### Contact Details

liorklein@gmail.com

**Comment by adrianhall** [comment]
This project is now in "maintenance" mode. This means that no new features will be accepted and fixes will be limited to security fixes. We expect to retire the DevOps Resource Kit by the end of 2023. At that time, the DevOps Resource Kit repository will be archived and there will be no further updates.

While you are free to fork the DevOps Resource Kit yourself, we recommend that you migrate to the following products:

* If you are using creator, switch over to using [Bicep](https://learn.microsoft.com/azure/azure-resource-manager/bicep/overview) templates. Bicep is a descriptive language for describing infrastructure, fully supports all features of Azure API Management, and is covered in any support agreement that you have with Azure. You can find bicep modules and examples for handling API Management APIs at https://github.com/azure-samples/api-management-sample-apis.
* If you are using extractor, switch your pipelines to use [APIOps](https://github.com/azure/apiops). APIOps applies the concepts of GitOps to API deployments. It is faster and more flexible than the DevOps Resource Kit.
