### ISSUE TITLE
Bug: Backend Authorization Credentials are not extracting

### ISSUE THREAD

**Issue by akshatgupta02** [Azure/azure-api-management-devops-resource-kit#750]
### Report

I have an API which is pointing to Function app in Backend. The calls to Function app from APIM are authorized through a Function app key which is stored in named values and its reference is saved at Backend -> Authorization Credentials -> Headers.
While using Extractor tool, the Backend template is missing the credentials header property.

### Expected Behavior

The extractor tool should extract the headers from Backend Authorization credentials and add them in credentials header property in ARM template. Sample from Microsoft Docs:

"properties": {
        "credentials": {
          "header": {
            "x-functions-key": [
              "------------Function app GUID key------------"
            ]
          }
        }
      }

### Actual Behavior

The extractor tool does not extract the headers from Backend Authorization credentials and credentials header property is missing in ARM template

### Steps to Reproduce the Problem

1. Add API in Azure APIM having Function app as backend
2. Backend will get generate and function app key will get added new newly generated Backend under (Authorization Credentials -> Headers)
3. Run the extractor tool on the newly adding API
4. The generated ARM template for Backend do not contain the Authorization credentials header
...

### Component

Extractor

### DevOps Resource Kit Version

Latest

### .NET Version

6.0.202

### OS

Windows

### Configuration

Configuration:

```yaml
version: 0.0.1
apimServiceName: example-apim-name
```

### Logs

```shell
example
```

### Contact Details

akshatgupta02@gmail.com

**Comment by adrianhall** [comment]
Can you please state what "Latest" means in the report - it means different things depending on when you downloaded, when you look at this report, and which specific set of tools you are looking at.  Thanks!

**Comment by adrianhall** [comment]
Closing due to lack of information.
