### ISSUE TITLE
Bug: InternalServerError creating Microsoft.ApiManagement/service/apis/schemas

### ISSUE THREAD

**Issue by dannythomas13** [Azure/azure-api-management-devops-resource-kit#756]
### Report

My CD pipeline is timing out when deploying the api template, and after reviewing RG deployment logs I am seeing the following:

Note that Microsoft.ApiManagement/service/apis and Microsoft.ApiManagement/service/products/apis prior to this succeeds

{
    "status": "Failed",
    "error": {
        "code": "InternalServerError",
        "message": "Request processing failed due to internal error."
    }
}

Type:
Microsoft.ApiManagement/service/apis/schemas

{
      "apiVersion": "2021-08-01",
      "type": "Microsoft.ApiManagement/service/apis/schemas",
      "name": "[concat(parameters('apimServiceName'), '/ece-corrosion/62b31e13c840211ce4e05ca3')]",
      "dependsOn": [
        "[resourceId('Microsoft.ApiManagement/service/apis', parameters('apimServiceName'), 'ece-corrosion')]"
      ],
      "properties": {
        "contentType": "application/vnd.ms-azure-apim.swagger.definitions+json",
        "document": {
          "definitions": {
            "Pipeline-advancedPost200ApplicationJsonResponse": {
              "type": "object"
            },
            "Pipeline-sectional-advancedPost200ApplicationJsonResponse": {
              "type": "object"
            },
            "Pipeline-basicPost200ApplicationJsonResponse": {
              "type": "object"
            },
            "Pipeline-sectional-basicPost200ApplicationJsonResponse": {
              "type": "object"
            },
            "Pipeline-point-advancedPost200ApplicationJsonResponse": {
              "type": "object"
            },
            "Pipeline-point-basicPost200ApplicationJsonResponse": {
              "type": "object"
            },
            "Pipeline-section-basicPost200ApplicationJsonResponse": {
              "type": "object"
            }
          },
          "value": "{\r\n  \"Pipeline-advancedPost200ApplicationJsonResponse\": {\r\n    \"type\": \"object\"\r\n  },\r\n  \"Pipeline-sectional-advancedPost200ApplicationJsonResponse\": {\r\n    \"type\": \"object\"\r\n  },\r\n  \"Pipeline-basicPost200ApplicationJsonResponse\": {\r\n    \"type\": \"object\"\r\n  },\r\n  \"Pipeline-sectional-basicPost200ApplicationJsonResponse\": {\r\n    \"type\": \"object\"\r\n  },\r\n  \"Pipeline-point-advancedPost200ApplicationJsonResponse\": {\r\n    \"type\": \"object\"\r\n  },\r\n  \"Pipeline-point-basicPost200ApplicationJsonResponse\": {\r\n    \"type\": \"object\"\r\n  },\r\n  \"Pipeline-section-basicPost200ApplicationJsonResponse\": {\r\n    \"type\": \"object\"\r\n  }\r\n}"
        }
      }
    }

The working API in the production environment is an isolated .net6 Azure Function to which I have added OpenAPI, the function was imported through OpenAPI and specifying .../api/swagger.json - swagger version is showing as "2.0"

### Expected Behavior

Operations to be created

### Actual Behavior

No operations created due to them referencing schema that failed to be deployed

### Steps to Reproduce the Problem

1. Create v4 Azure Function Isolated Process targetting .net6.0
2. Add package Microsoft.Azure.Functions.Worker.Extensions.OpenApi
3. Add attribute OpenApiResponseWithBody, example: [OpenApiResponseWithBody(statusCode: HttpStatusCode.OK, contentType: "application/json", bodyType: typeof(GenericPart4Level1CtpResult), Description = "The fitness for service response")]
4. Deploy function to Azure
5. Create consumption APIM
6. Add API
7. Import through OpenAPI Specification, pointing to .../api/swagger.json 
8. Run extractor tool (have tried both 1.0.0-beta.6 and GA/0.7)
9. Deploy templates using Classic Azure DevOps pipeline
10. Look at deployment of RG through portal
11. Witness InternalServerError
...

### Component

Extractor

### DevOps Resource Kit Version

Both latest pre release and latest GA

### .NET Version

6

### OS

Windows 10

### Configuration

Configuration:

```yaml
version: 0.0.1
apimServiceName: example-apim-name
```

### API Management Configuration

Consumption tier is being used

### Logs

```shell
example
```

**Comment by dannythomas13** [comment]
@adrianhall This is my first usage of this toolkit, for my understanding would you mind explaining if there has been a new change within APIM/Portal that this toolkit needs to catch up on or is there something specific when returning objects from requests, why is it so many other API's and demos deploy without error? Is my API likely different to basic examples?

Also given you appear to have an idea of what it may be, assuming it is that do you know of a workaround?

**Comment by dannythomas13** [comment]
@adrianhall Just this morning I attempted to instead import API from api/openapi/v3.json prior to extracting and it now all works! I imagine this can be closed/amended to reflect the fact there may be issues with extracting v2 swagger, I'm not even sure why I pointed it to v2 when my intention was to make use of v3. Thanks for the great toolkit

**Comment by adrianhall** [comment]
Thanks @dannythomas13 for the feedback.  Will keep it open so we can properly assess impact.

In your case, I don't know that the schemas are the issue.  However, we have a work item to implement API schema export, so it's reasonable, given the error, that it's associated.  The engineer will determine if it's the same error or a different one when they get to it.  However, tagging it as "possibly associated" indicates to him that it may be a duplicate and can be handled at the same time.

**Comment by f-alizada** [comment]
Hello @dannythomas13. 
Thank you for raising the issue.  
It was possible to reproduce the bug, the fix is already merged into the main branch, hence issue was closed. 
Please feel free to reopen this issue or create new one if you will face same behaviour with deploying API schemas. 
Best regards
