### ISSUE TITLE
Invalid URIs in master template

### ISSUE THREAD

**Issue by kenty30** [Azure/azure-api-management-devops-resource-kit#759]
Creator tool is generating linked master template containing URIs with and without leading forward slash causing azure/arm-deploy@v1 to fail. 

Target azure blob storage URL would look like
https://abc123.blob.core.windows.net/mycontainermyapim-globalServicePolicy.template.json?***
https://abc123.blob.core.windows.net/mycontainer/my-api-initial.api.template.json?***

FileNameGenerator.cs
V0.7 => Including leading forward-slash => works ok
       return new FileNames()
            {
                apiVersionSets = $@"/{baseFileName}apiVersionSets.template.json",
                authorizationServers = $@"/{baseFileName}authorizationServers.template.json",
                backends = $@"/{baseFileName}backends.template.json",
                globalServicePolicy = $@"/{baseFileName}globalServicePolicy.template.json",
                loggers = $@"/{baseFileName}loggers.template.json",
                namedValues = $@"/{baseFileName}namedValues.template.json",
                tags = $@"/{baseFileName}tags.template.json",
                products = $@"/{baseFileName}products.template.json",
                productAPIs = $@"/{baseFileName}productAPIs.template.json",
                apiTags = $@"/{baseFileName}apiTags.template.json",
                parameters = $@"/{baseFileName}parameters.json",
                linkedMaster = $@"/{baseFileName}master.template.json",
                apis = "/Apis",
                splitAPIs = "/SplitAPIs",
                versionSetMasterFolder = "/VersionSetMasterFolder",
                revisionMasterFolder = "/RevisionMasterFolder",
                groupAPIsMasterFolder = "/MultipleApisMasterFolder",
                baseFileName = baseFileName
            };

Main => missing leading forward slash => generating incorrect template URL
           return new FileNames
            {
                ApiVersionSets = $@"{baseFileName}apiVersionSets.template.json",
                AuthorizationServers = $@"{baseFileName}authorizationServers.template.json",
                Backends = $@"{baseFileName}backends.template.json",
                GlobalServicePolicy = $@"{baseFileName}globalServicePolicy.template.json",
                Loggers = $@"{baseFileName}loggers.template.json",
                NamedValues = $@"{baseFileName}namedValues.template.json",
                Tags = $@"{baseFileName}tags.template.json",
                Products = $@"{baseFileName}products.template.json",
                ProductAPIs = $@"{baseFileName}productAPIs.template.json",
                Gateway = $@"{baseFileName}gateways.template.json",
                GatewayApi = $@"{baseFileName}gateways-apis.template.json",
                IdentityProviders = $@"{baseFileName}identity-providers.template.json",
                TagApi = $@"{baseFileName}apiTags.template.json",
                Parameters = $@"{baseFileName}parameters.json",
                LinkedMaster = $@"{baseFileName}master.template.json",
                Apis = "/Apis",
                SplitAPIs = "/SplitAPIs",
                VersionSetMasterFolder = "/VersionSetMasterFolder",
                RevisionMasterFolder = "/RevisionMasterFolder",
                GroupAPIsMasterFolder = "/MultipleApisMasterFolder",
                Groups = $"{baseFileName}groups.template.json",
                BaseFileName = baseFileName
            };

**Comment by jeffward01** [comment]
Is this a continuation of the URL's referenced: https://github.com/Azure/azure-api-management-devops-resource-kit/blob/main/src/README.md#APIConfiguration that are missing?

For example:

![image](https://user-images.githubusercontent.com/12589359/184787565-1b684ff9-6f36-4cd0-a583-7536fee3861f.png)

This is the Broken URL: https://docs.microsoft.com/en-us/azure/templates/microsoft.apimanagement/2019-01-01/service/apis/diagnostics#DiagnosticContractProperties

@adrianhall - I can open up a new ticket if this is not related. I did not want to needlessly open up new tickets.

**Comment by mradulmodi** [comment]
Facing the same issue. Master template generated by Creator is following different pattern for naming. This makes the template fail with a linkedTemplateUrl with or without "/"

[GenerateCreatorAPIFileName](https://github.com/Azure/azure-api-management-devops-resource-kit/blob/3b04442f95b1d3f47062e0c52dd19668e9241193/src/ArmTemplates/Common/FileHandlers/FileNameGenerator.cs#L88) is adding a forward slash before. To make the name work with this the `linkedTemplateUrl `parameter name should  not include forward slash. 

Other names generated do not include a forward slash example [GenerateFileNames](https://github.com/Azure/azure-api-management-devops-resource-kit/blob/3b04442f95b1d3f47062e0c52dd19668e9241193/src/ArmTemplates/Common/FileHandlers/FileNameGenerator.cs#L44). Such naming would required to have a forward slash at end of `linkedTemplateUrl `

Mixing both and anyway you specify `linkedTemplateUrl ` the template generated is wrong.

**Comment by albinsson1337** [comment]
> Facing the same issue. Master template generated by Creator is following different pattern for naming. This makes the template fail with a linkedTemplateUrl with or without "/"
> 
> [GenerateCreatorAPIFileName](https://github.com/Azure/azure-api-management-devops-resource-kit/blob/3b04442f95b1d3f47062e0c52dd19668e9241193/src/ArmTemplates/Common/FileHandlers/FileNameGenerator.cs#L88) is adding a forward slash before. To make the name work with this the `linkedTemplateUrl `parameter name should not include forward slash.
> 
> Other names generated do not include a forward slash example [GenerateFileNames](https://github.com/Azure/azure-api-management-devops-resource-kit/blob/3b04442f95b1d3f47062e0c52dd19668e9241193/src/ArmTemplates/Common/FileHandlers/FileNameGenerator.cs#L44). Such naming would required to have a forward slash at end of `linkedTemplateUrl `
> 
> Mixing both and anyway you specify `linkedTemplateUrl ` the template generated is wrong.

Same here. Doing some tests where i removed slash for generate a name. Feels like bad practice to add "/" [GenerateCreatorAPIFileName](https://github.com/Azure/azure-api-management-devops-resource-kit/blob/3b04442f95b1d3f47062e0c52dd19668e9241193/src/ArmTemplates/Common/FileHandlers/FileNameGenerator.cs#L88)   when generating a name.

**Comment by armando-rubiano** [comment]
Yes, we are facing the same issue, the Master template generated by Creator is following different pattern for naming. This makes the template fail with a linkedTemplateUrl with "/" as inside of the Master template it prefixes the references to the XYZ-initial.api.template.json and XYZ- subsequent.api.template.json with a “/”.

Also we noticed that if the configuration’s value in the ARM yml file entry for the outputLocation  property must end with a “/” otherwise the generated XYZ_ApimServiceName-master.template.json is created in the root folder!..

**Comment by adrianhall** [comment]
Thank you for your input on the creator tool.  We are currently looking at the future of the creator tool and would like your feedback.  Please could you fill in the survey at https://forms.office.com/r/w7rQp88NwH - your input is appreciated.

**Comment by rutgersmit** [comment]
Today I updated my local copy of this repo (main branch) and the bug seems to be fixed. The [apim-instance]-master.template.json file for your specific API is now placed inside the subdirectory of your API.

Previously that file was generated in the root as [name][apim-instance]-master.template.json where name refers to the name property in your yaml config file.

**Comment by adrianhall** [comment]
This project is now in "maintenance" mode. This means that no new features will be accepted and fixes will be limited to security fixes. We expect to retire the DevOps Resource Kit by the end of 2023. At that time, the DevOps Resource Kit repository will be archived and there will be no further updates.

While you are free to fork the DevOps Resource Kit yourself, we recommend that you migrate to the following products:

* If you are using creator, switch over to using [Bicep](https://learn.microsoft.com/azure/azure-resource-manager/bicep/overview) templates. Bicep is a descriptive language for describing infrastructure, fully supports all features of Azure API Management, and is covered in any support agreement that you have with Azure. You can find bicep modules and examples for handling API Management APIs at https://github.com/azure-samples/api-management-sample-apis.
* If you are using extractor, switch your pipelines to use [APIOps](https://github.com/azure/apiops). APIOps applies the concepts of GitOps to API deployments. It is faster and more flexible than the DevOps Resource Kit.
