### ISSUE TITLE
[Extractor] Split APIs into multiple API templates

### ISSUE THREAD

**Issue by miaojiang** [Azure/azure-api-management-devops-resource-kit#77]

**Comment by joeyeng** [comment]
@miaojiang I just confirmed the extractor doesn't split APIs into multiple templates.

**Comment by joeyeng** [comment]
@lucashuet93 @odaibert @nzthiago Any ideas why I might not be seeing this functionality working?

**Comment by miaojiang** [comment]
@joeyeng I can reproduce it. We will investigate.

**Comment by joeyeng** [comment]
@miaojiang Any update on this?

**Comment by joeyeng** [comment]
I'm surprised there's not more interest in this feature. Without this, this tool is unusable, imo...

**Comment by miaojiang** [comment]
We will revisit soon.

**Comment by RupengLiu** [comment]
Use "--splitAPIs true" to split into multiple API template, and you can deploy anyone of them separately

**Comment by miaojiang** [comment]
@joeyeng  please give it a try and let us know what you think!

**Comment by joeyeng** [comment]
@RupengLiu I'm getting: ##[error]Unrecognized option '--splitAPIs'

**Comment by joeyeng** [comment]
@RupengLiu Sorry it was a problem in my pipeline. It is working for me now. But are we forced to use extractorparams.json for passing params to the extractor now?
