### ISSUE TITLE
[Creator] Feature Request: Support policy fragments in creator

### ISSUE THREAD

**Issue by jankalteneckerhugobosscom** [Azure/azure-api-management-devops-resource-kit#774]
### Scenario

Is there already the plan to support adding policy fragments with the creator?
In best case this can be done without an additional API.

### Proposal

Deploy via creator policy fragments in an automated way (without additional API).

### Describe alternatives you've considered

-

**Comment by MichaelKoch** [comment]
would be nice ...

**Comment by adrianhall** [comment]
Agreed - I'll add it to the "next GA release" as this one is quite full as it is.

**Comment by afdaniels** [comment]
Any update on this?

**Comment by adrianhall** [comment]
We aren't doing work on the creator right now, so this will be a while.

**Comment by adrianhall** [comment]
This project is now in "maintenance" mode. This means that no new features will be accepted and fixes will be limited to security fixes. We expect to retire the DevOps Resource Kit by the end of 2023. At that time, the DevOps Resource Kit repository will be archived and there will be no further updates.

While you are free to fork the DevOps Resource Kit yourself, we recommend that you migrate to the following products:

* If you are using creator, switch over to using [Bicep](https://learn.microsoft.com/azure/azure-resource-manager/bicep/overview) templates. Bicep is a descriptive language for describing infrastructure, fully supports all features of Azure API Management, and is covered in any support agreement that you have with Azure. You can find bicep modules and examples for handling API Management APIs at https://github.com/azure-samples/api-management-sample-apis.
* If you are using extractor, switch your pipelines to use [APIOps](https://github.com/azure/apiops). APIOps applies the concepts of GitOps to API deployments. It is faster and more flexible than the DevOps Resource Kit.
