### ISSUE TITLE
Bug:  built-in groups should be removed from the group template

### ISSUE THREAD

**Issue by davidliuhca** [Azure/azure-api-management-devops-resource-kit#776]
### Report

In the group template, it contains the build-in (system) groups: administrators, developers and guests. These groups can't be updated, so it will fail when deploying to other environments ( we have Dev, Sys, Stg and Prod environments).

Below is the error I got:

At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details. (Code: DeploymentFailed)
 - {
  "error": {
    "code": "MethodNotAllowed",
    "message": "System entity cannot be modified",
    "details": null
  }
} (Code:MethodNotAllowed)

This only happens when Microsoft changes something settings in the built-in groups as New-AzResourceGroupDeployment does an update only when the resource in the destination APIM service is different from the one defined in the ARM template. Unfortunately Microsoft does change the settings in the built-in groups.

We extracted templates from Dev. The descriptions of group administrators in our Dev, Sys and Stg were the same, but different from the description in the Prod, thus we failed to deploy to the Prod. I have no idea when Microsoft changed the description. I then created a ticket to Microsoft and they updated the description.

Although now the descriptions are the same, the best solution is to remove the built-in groups from the group template in case there are some setting changes from Microsoft in the future.

### Expected Behavior

deploy successfully

### Actual Behavior

Failed with the error

### Steps to Reproduce the Problem

Change the description of group administrators in the group template to make it different from the one in the destination and deploy it.

### Component

Extractor

### DevOps Resource Kit Version

V0.7

### .NET Version

6

### OS

Windows 11

### Configuration

Configuration:

```yaml
version: 0.0.1
apimServiceName: example-apim-name
```

### Logs

```shell
example
```

**Comment by adrianhall** [comment]
Also, I'm not sure this is valid - what if you add members to one of these groups?  Surely, you would want those same members to be a part of the extracted template?

**Comment by davidliuhca** [comment]
Group template doesn't add members, this is what I expected. Actually I
don't want to add the same members to the groups in different environments.

**Comment by f-alizada** [comment]
Hello @davidliuhca.
Thank you for raising the issue. 
The issue is closed since the functionality allowing to pass a parameter to exclude built in groups from generated template is merged into the main branch and will be available in future releases. By default, built-in groups will be exported. 
Please feel free to reopen or create new issue in case you will face issues with introduced functionality. 
Best regards
