### ISSUE TITLE
Feature Request (Extractor): Global policy template should be an optional to generate

### ISSUE THREAD

**Issue by davidliuhca** [Azure/azure-api-management-devops-resource-kit#777]
### Scenario

When extracting an single API it generates global policy template. This is a high risk considering the following scenario.

We extract API A from Dev and deploy to Prod. After two month the global policy is changed and we extract API B and deploy to Prod. After half a year for some reasons we need to recover API A in prod from the release pipeline (ex, API A is accidently deleted from Prod). The recovery will bring the old global policy to the Prod.

The problem here is the repo for release pipeline A and release pipeline B contains different version of global policy. Global policy should be deployed in a separate pipeline, and release pipeline A and release pipeline B shouldn't deploy it.

### Proposal

add a switch to make it optional to generate global policy. If not generating the global policy template, the global policy resource section should be removed from the master template too.

### Contact Details

davidliuh@gmail.com

**Comment by adrianhall** [comment]
Seems like a reasonable minimal ask; although I question the validity - if you have a source system that is operating one way, then you expect it to operate the same way on deployment in the new instance.  What you are proposing would affect that.  However, we can make it a deliberate choice.

Adding to backlog for the follow-on release.

**Comment by davidliuhca** [comment]
Actually I created a tool to handle all the optional requests I added to
the GitHub. I'm wondering how many people have the same requests.

For me, I have a separate pipeline to deploy global policy only. Whenever
the global policy is changed, I run the pipeline.

**Comment by blockingHD** [comment]
> Member

CORS configuration I think is the key example for why this is needed as that will inherently be different per environment with a development environment including localhost etc.

**Comment by adrianhall** [comment]
This project is now in "maintenance" mode. This means that no new features will be accepted and fixes will be limited to security fixes. We expect to retire the DevOps Resource Kit by the end of 2023. At that time, the DevOps Resource Kit repository will be archived and there will be no further updates.

While you are free to fork the DevOps Resource Kit yourself, we recommend that you migrate to the following products:

* If you are using creator, switch over to using [Bicep](https://learn.microsoft.com/azure/azure-resource-manager/bicep/overview) templates. Bicep is a descriptive language for describing infrastructure, fully supports all features of Azure API Management, and is covered in any support agreement that you have with Azure. You can find bicep modules and examples for handling API Management APIs at https://github.com/azure-samples/api-management-sample-apis.
* If you are using extractor, switch your pipelines to use [APIOps](https://github.com/azure/apiops). APIOps applies the concepts of GitOps to API deployments. It is faster and more flexible than the DevOps Resource Kit.
