### ISSUE TITLE
Feature Request (extractor): make it an option to exlude diagnostics resource in the API template

### ISSUE THREAD

**Issue by davidliuhca** [Azure/azure-api-management-devops-resource-kit#780]
### Scenario

currently diagnostics resource is always generated in the API template. there are two issues:

1. "loggerId": "/subscriptions/**subscriptionID**/resourceGroups/**resourceGroupname**/providers/Microsoft.ApiManagement/service/**APIMService**/loggers/**AppInsightID**", all the values in bold in different environments are different. The whole loggerId should be a parameter
2. Hidden settings are not extracted (below setting is for not logging subscription-key)
        "frontend": {
       "request":{
         "dataMasking":{
            "queryParams":[{
               "mode": "Hide",
               "value": "subscription-key"
            }]
         }

### Proposal

better to have an option to not generate diagnostics resource in the API template

**Comment by davidliuhca** [comment]
I just updated the extract tools one month ago, so I think the version is
1.0.0-beta.7

**Comment by adrianhall** [comment]
This project is now in "maintenance" mode. This means that no new features will be accepted and fixes will be limited to security fixes. We expect to retire the DevOps Resource Kit by the end of 2023. At that time, the DevOps Resource Kit repository will be archived and there will be no further updates.

While you are free to fork the DevOps Resource Kit yourself, we recommend that you migrate to the following products:

* If you are using creator, switch over to using [Bicep](https://learn.microsoft.com/azure/azure-resource-manager/bicep/overview) templates. Bicep is a descriptive language for describing infrastructure, fully supports all features of Azure API Management, and is covered in any support agreement that you have with Azure. You can find bicep modules and examples for handling API Management APIs at https://github.com/azure-samples/api-management-sample-apis.
* If you are using extractor, switch your pipelines to use [APIOps](https://github.com/azure/apiops). APIOps applies the concepts of GitOps to API deployments. It is faster and more flexible than the DevOps Resource Kit.
