### ISSUE TITLE
Feature Request (extractor): make it optional to generate authorizationServers template

### ISSUE THREAD

**Issue by davidliuhca** [Azure/azure-api-management-devops-resource-kit#781]
### Scenario

There are two issues in the authorizationServers template

1. clientID should be a parameter as it is different in different environments
     "clientId": "xxxxxxx-5adf-4ba2-991f-c1c2115ec701"
2. the template doesn't contain clientSecret so it doesn't create the authorizationServer as expected. You still have to manually set it up after deployment

### Proposal

make it optional to generate authorizationServers template. of course the master template should be changed accordingly.

**Comment by adrianhall** [comment]
This is by design.  As previously stated, you are likely to have better luck with APIOps in the Azure Architecture Center and located at https://github.com/azure/apiops
