### ISSUE TITLE
Bug: Extractor not escaping square brackets in definitions

### ISSUE THREAD

**Issue by blockingHD** [Azure/azure-api-management-devops-resource-kit#785]
### Report

When extracting definitions from APIM where the content is JSON and returns an array the template fails validation. 

Granted this is an edge case and JSON responses and requests should be wrapped in an object.

### Expected Behavior

Generated definition template escapes definitions with double square brackets when the content is just a JSON array.

Should generate: 
```json
    {
      "apiVersion": "2021-08-01",
      ...
      "properties": {
        ...
        "responses": [
          {
            "description": "Success",
            "headers": [],
            "representations": [
              {
                "contentType": "application/json",
                "schemaId": "61715636fb426817341df64b",
                "typeName": "ActionsGet200ApplicationJsonResponse",
                "examples": {
                  "default": {
                    "value": "[[\r\n  {\r\n    \"id\": 0,\r\n    \"actionName\": \"string\"\r\n  }\r\n]]"
                  }
                }
              }
            ],
            "statusCode": 200
          }
          ...
        ]
      }
    }
```

### Actual Behavior

Produces unescaped JSON array causing ARM validation errors.

Generates:
```json
    {
      "apiVersion": "2021-08-01",
      ...
      "properties": {
        ...
        "responses": [
          {
            "description": "Success",
            "headers": [],
            "representations": [
              {
                "contentType": "application/json",
                "schemaId": "61715636fb426817341df64b",
                "typeName": "ActionsGet200ApplicationJsonResponse",
                "examples": {
                  "default": {
                    "value": "[\r\n  {\r\n    \"id\": 0,\r\n    \"actionName\": \"string\"\r\n  }\r\n]"
                  }
                }
              }
            ],
            "statusCode": 200
          }
          ...
        ]
      }
    }
```

### Steps to Reproduce the Problem

1. Create definition example in APIM that is an unwrapped JSON Array.
2. Use the extractor to get ARM templates
3. Deploy template

### Component

Extractor

### DevOps Resource Kit Version

1.0.0-beta.9

### .NET Version

.net6

### OS

Windows 11

### Configuration

N/A

### Logs

InvalidTemplate - Deployment template validation failed: 'The template resource '...' at line '1' and column '304923' is not valid: The language expression '
  ...
' is not valid: the string character '{' at position '4' is not expected.. Please see https://aka.ms/arm-template-expressions for usage details.'.

**Comment by f-alizada** [comment]
@blockingHD thank you for raising the issue. 
The PR (#789) addressing the issue was merged into the main branch and will be available in future releases. 
Please feel free to reopen or create a new issue in case you will face the similar behaviour with api response/request representation. 
Best regards
