### ISSUE TITLE
Feature Request: Ability to customize deployment names generated by Extractor

### ISSUE THREAD

**Issue by k-schneider** [Azure/azure-api-management-devops-resource-kit#786]
### Scenario

When extracting single API's the deployment names are always the same (eg `apisTemplate`, `productAPIsTemplate`, etc).  If you have separate pipelines deploying these templates simultaneously one of them will fail because the deployment name is already reserved.

### Proposal

Add a new option to the Extractor that allows for a suffix to be added to deployment names when running the extractor tool to ensure they are unique per extracted API.

### Contact Details

k.schneider@outlook.com

**Comment by adrianhall** [comment]
This project is now in "maintenance" mode. This means that no new features will be accepted and fixes will be limited to security fixes. We expect to retire the DevOps Resource Kit by the end of 2023. At that time, the DevOps Resource Kit repository will be archived and there will be no further updates.

While you are free to fork the DevOps Resource Kit yourself, we recommend that you migrate to the following products:

* If you are using creator, switch over to using [Bicep](https://learn.microsoft.com/azure/azure-resource-manager/bicep/overview) templates. Bicep is a descriptive language for describing infrastructure, fully supports all features of Azure API Management, and is covered in any support agreement that you have with Azure. You can find bicep modules and examples for handling API Management APIs at https://github.com/azure-samples/api-management-sample-apis.
* If you are using extractor, switch your pipelines to use [APIOps](https://github.com/azure/apiops). APIOps applies the concepts of GitOps to API deployments. It is faster and more flexible than the DevOps Resource Kit.
