### ISSUE TITLE
Bug: apiTagsTemplate dependency [extractor]

### ISSUE THREAD

**Issue by davidliuhca** [Azure/azure-api-management-devops-resource-kit#790]
### Report

In the master template it should be the apiTemplate depending on the apiTagsTemplate rather than opposite. 

I got an error complaining that the tag doesn't exist. I then manually created the api tag in APIM and the deployment succeeded. I think the apiTagstemplate should run first before running apiTemplate

### Expected Behavior

Deployment succeeds

### Actual Behavior

Deployment errors out with the error "Tag doesn't exist"

### Steps to Reproduce the Problem

1. Create an API in one APIM instance, make sure it has api tag which doesn't exist in another APIM instance
2. Extract ARM templates
3. Run the templates in PowerShell in another APIM instance
...

### Component

Extractor

### DevOps Resource Kit Version

0.7

### .NET Version

6.0

### OS

Windows

### Configuration

Configuration:

```yaml
version: 0.0.1
apimServiceName: example-apim-name
```

### Logs

```shell
example
```

**Comment by adrianhall** [comment]
Can you check to see if this is a problem with the latest 1.0.0 beta?  The 0.7 release is about to be replaced by the 1.0.0 release, and I suspect we have fixed this already.

**Comment by davidliuhca** [comment]
Sorry I was wrong about the version. I am using the latest 1.0.0 beta.

**Comment by adrianhall** [comment]
Got it - thanks for the report.  Can you please cut-and-paste the relevant pieces from the apiTemplate.json and apiTagsTemplate.json (just in case engineer needs it).

**Comment by davidliuhca** [comment]
It's about the master template. Inside the master template, resource
apiTemplate should depend on resource apiTagsTemplate. But it is not now.

Enclosed is the master template. You can see resource apiTemplate which is
in the middle of the JSON file doesn't have a dependency on resource
apiTagsTemplate.

**Comment by f-alizada** [comment]
Hello @davidliuhca. 
Thank you for raising the issue. 
the apiTags template is generated to attach tags to the api, hence both api and tags should be already existing that is why apiTags template depends on apiTemplate and tagsTemplate.
I was not able to reproduce the issue extracting whole Api Management instance. 
Could you please clarify if there was any other configuration settings for extraction apart from apimServiceName?
Best regards

**Comment by davidliuhca** [comment]
Hi,

apiTagsTemplate is for API level tags, and tagTemplate is for operation
level tags. Both should be deployed before deploying apiTemplate.

I guess the reason you couldn't reproduce it is the API level tags were
already created in another environment before you deploy the templates.

We have hundreds of APIs so I always extract templates for only one API.
Below is an example of my extraction configuration.

{
  "sourceApimName": "aa-bb-zzzz-apim",
  "destinationApimName": "cc-dd-zzzz-apim",
  "resourceGroup": "aa-bb-yyyy-RG",
  "fileFolder": "C:/APIM/APIM Extractor/ClaimOnlineWorkerProfile",
  "linkedTemplatesBaseUrl": "PlaceHolder",
  "policyXMLBaseUrl": "PlaceHolder",
  "linkedTemplatesSasToken": "PlaceHolder",
  "policyXMLSasToken": "PlaceHolder",
  "apiName": "claims-online-worker-profile"
}

**Comment by f-alizada** [comment]
Hello @davidliuhca. Thank you for clarifications. 
I was able to reproduce the issue by extracting only one Api. 
The problem was not with dependencies, but in generated templates: tags template didn't contain Api level tags while extracting the single Api. 
PR with the fix is created: #795

**Comment by f-alizada** [comment]
Hello @davidliuhca.
The issue was closed since the related PR #795 was merged into the main branch and was included in the [release](https://github.com/Azure/azure-api-management-devops-resource-kit/releases/tag/1.0.0-beta.11).
Please feel free to reopen the issue or create new one if the fix didn't solve the problem using main branch or released version, and you are experiencing the same behaviour.
Best regards
