### ISSUE TITLE
Bug: [Broken Documentation Links] The Creator configuration file definitions has broken links

### ISSUE THREAD

**Issue by jeffward01** [Azure/azure-api-management-devops-resource-kit#791]
### Expected Behavior

When a user wants to view 'Additional Properties' of the `config.yml` the links are broken.  See this page for broken links:

https://github.com/Azure/azure-api-management-devops-resource-kit/blob/main/src/README.md#APIOperationPolicyConfiguration

### Actual Behavior

The definition detail links are broken

### Steps to Reproduce the Problem

Go to: https://github.com/Azure/azure-api-management-devops-resource-kit/blob/main/src/README.md#APIOperationPolicyConfiguration

Click on some of the definition details at the bottom of the page. 

Example:

![image](https://user-images.githubusercontent.com/12589359/184787886-8c0a7824-91d7-4369-b707-ca655ea975a9.png)

[Broken Link](https://docs.microsoft.com/en-us/azure/templates/microsoft.apimanagement/2019-01-01/service/apis/diagnostics#DiagnosticContractProperties)

### Component

Creator

### DevOps Resource Kit Version

Most recent github deployment

### .NET Version

N/A

### OS

N/A

### Configuration

N/A

### API Management Configuration

N/A

### Logs

N/A

### Contact Details

jeff@aeonic-tech.com

**Comment by adrianhall** [comment]
Thank you for your input on the creator tool.  We are currently looking at the future of the creator tool and would like your feedback.  Please could you fill in the survey at https://forms.office.com/r/w7rQp88NwH - your input is appreciated.

**Comment by adrianhall** [comment]
This project is now in "maintenance" mode. This means that no new features will be accepted and fixes will be limited to security fixes. We expect to retire the DevOps Resource Kit by the end of 2023. At that time, the DevOps Resource Kit repository will be archived and there will be no further updates.

While you are free to fork the DevOps Resource Kit yourself, we recommend that you migrate to the following products:

* If you are using creator, switch over to using [Bicep](https://learn.microsoft.com/azure/azure-resource-manager/bicep/overview) templates. Bicep is a descriptive language for describing infrastructure, fully supports all features of Azure API Management, and is covered in any support agreement that you have with Azure. You can find bicep modules and examples for handling API Management APIs at https://github.com/azure-samples/api-management-sample-apis.
* If you are using extractor, switch your pipelines to use [APIOps](https://github.com/azure/apiops). APIOps applies the concepts of GitOps to API deployments. It is faster and more flexible than the DevOps Resource Kit.
