### ISSUE TITLE
Bug: Policy Fragments are not export for single API when referenced 

### ISSUE THREAD

**Issue by UniperMaster** [Azure/azure-api-management-devops-resource-kit#792]
### Report

The Policy Fragment Extractor needs to do something similar to the NamedValued Pairs and check the policy xml in the first option as the current PolicyContent check doesn't contain the XML

var isReferencedInPolicy = DoesPolicyReferenceFragment(apiTemplatePolicies, policyFragmentReferenceString,  
                                                                            policyFragment, 
                                                                            baseFilesGenerationDirectory);

var isReferencedInPolicy = apiTemplatePolicies?.Any(x => x.Properties.PolicyContent.Contains(policyFragmentReferenceString));

### Expected Behavior

Single API
Export the policy fragment based on fragment id being present in an API policy

### Actual Behavior

Single API
Export the policy fragment based on fragment id being ignored for a single API

### Steps to Reproduce the Problem

n/a

### Component

Extractor

### DevOps Resource Kit Version

V0.7

### .NET Version

6.0.107

### OS

Windows

### Configuration

{
    "sourceApimName": "apim-name",
    "destinationApimName": "?",
    "resourceGroup": "apim-rg",
    "fileFolder": "demo-openapi-v10",
    "apiName": "demo-openapi-v10",
    "linkedTemplatesBaseUrl": "?",
    "linkedTemplatesSasToken": "?",
    "policyXMLBaseUrl": "?",
    "policyXMLSasToken": "?",
    "includeAllRevisions": "false",
    "paramServiceUrl": "true",
    "paramNamedValue": "true",
    "paramApiLoggerId": "true",
    "paramLogResourceId": "true",
    "paramBackend": "true",
    "paramNamedValuesKeyVaultSecrets": "true"
}

### API Management Configuration

SKU: Developer
full admin right : yes 
VNET: Yes

### Contact Details

ian.beeson@uniper.energy

**Comment by f-alizada** [comment]
Hello @UniperMaster thank you for raising the issue. 
The PR #799 addressing the issue is now merged into the main branch and will be available in future releases. 
Please feel free to reopen this issue or create new one in case you will face same behaviour with policy fragments using latest changes. 
Best regards.
