### ISSUE TITLE
Creator tool generating parameters file which is not correct for the Version Set Template

### ISSUE THREAD

**Issue by shakhand208** [Azure/azure-api-management-devops-resource-kit#806]
Hi Folks,

We have been working on a scenario where the configuration of our creator config creates 3 templates and 1 parameter file
- Initial API Template
- Subsequent API Template
- APIVersionSets Template
- Parameter File

The Initial API and Subsequent API Templates uses 2 Parameters - APIm Service Name and API Service URL which are available in the parameter file so these ARM Temp;ates gets deployed in Azure APIM successfully.
However in the APIVersionSets Templates, there is only 1 parameter in use i.e.; APIM Service Name. Hence when the parameter file created by the kit is used to deploy APIVersion Sets, we are getting below Error
**Deployment template validation failed: 'The template parameters 'api-ServiceUrl' in the parameters file are not valid; they are not present in the original template and can therefore not be provided at deployment time. The only supported parameters for this template are 'apimServiceName'.**

Is there any solution to generate template specific parameter files to avoid such errors?</div>

**Comment by ratheeshps** [comment]
I am also facing this issue. It is not adding ServiceUrl parameter to the APIVersionSets template file.

**Comment by adrianhall** [comment]
Thank you for your input on the creator tool.  We are currently looking at the future of the creator tool and would like your feedback.  Please could you fill in the survey at https://forms.office.com/r/w7rQp88NwH - your input is appreciated.

**Comment by adrianhall** [comment]
This project is now in "maintenance" mode. This means that no new features will be accepted and fixes will be limited to security fixes. We expect to retire the DevOps Resource Kit by the end of 2023. At that time, the DevOps Resource Kit repository will be archived and there will be no further updates.

While you are free to fork the DevOps Resource Kit yourself, we recommend that you migrate to the following products:

* If you are using creator, switch over to using [Bicep](https://learn.microsoft.com/azure/azure-resource-manager/bicep/overview) templates. Bicep is a descriptive language for describing infrastructure, fully supports all features of Azure API Management, and is covered in any support agreement that you have with Azure. You can find bicep modules and examples for handling API Management APIs at https://github.com/azure-samples/api-management-sample-apis.
* If you are using extractor, switch your pipelines to use [APIOps](https://github.com/azure/apiops). APIOps applies the concepts of GitOps to API deployments. It is faster and more flexible than the DevOps Resource Kit.
