### ISSUE TITLE
Bug: [Creator] parameterizeNamedValuesAndSecrets does not add parameters to generated parameters.json file

### ISSUE THREAD

**Issue by k-schneider** [Azure/azure-api-management-devops-resource-kit#808]
### Report

When using the Creator CLI with the --parameterizeNamedValuesAndSecrets flag the generated parameters.json file does not include the named values parameters.

### Expected Behavior

The parameters file should include all parameterized values.

### Actual Behavior

Named values parameters are not present in the file.

### Steps to Reproduce the Problem

Add some named values to the yml config and execute the creator with the --parameterizeNamedValuesAndSecrets flag present.

### Component

Creator

### DevOps Resource Kit Version

Beta 11

### .NET Version

6.0

### OS

Windows 11

### Contact Details

k.schneider@outlook.com

**Comment by adrianhall** [comment]
Thank you for your input on the creator tool.  We are currently looking at the future of the creator tool and would like your feedback.  Please could you fill in the survey at https://forms.office.com/r/w7rQp88NwH - your input is appreciated.

**Comment by adrianhall** [comment]
This project is now in "maintenance" mode. This means that no new features will be accepted and fixes will be limited to security fixes. We expect to retire the DevOps Resource Kit by the end of 2023. At that time, the DevOps Resource Kit repository will be archived and there will be no further updates.

While you are free to fork the DevOps Resource Kit yourself, we recommend that you migrate to the following products:

* If you are using creator, switch over to using [Bicep](https://learn.microsoft.com/azure/azure-resource-manager/bicep/overview) templates. Bicep is a descriptive language for describing infrastructure, fully supports all features of Azure API Management, and is covered in any support agreement that you have with Azure. You can find bicep modules and examples for handling API Management APIs at https://github.com/azure-samples/api-management-sample-apis.
* If you are using extractor, switch your pipelines to use [APIOps](https://github.com/azure/apiops). APIOps applies the concepts of GitOps to API deployments. It is faster and more flexible than the DevOps Resource Kit.
