### ISSUE TITLE
Bug: [Creator] Master template not passing some parameters through to linked templates

### ISSUE THREAD

**Issue by k-schneider** [Azure/azure-api-management-devops-resource-kit#810]
### Report

The master template only seems to pass along the service name parameter to linked templates ignoring other required parameters.  The API templates require a service url parameter.  The named values template, when using the `--parameterizeNamedValuesAndSecrets` flag requires a namedValues parameter.  Neither of these forwarded by the master template rendering it useless.

### Expected Behavior

Linked templates should have all their required parameters forwarded by the master template.

### Actual Behavior

Only service name is passed to linked templates.

### Steps to Reproduce the Problem

Include `linked: true` in your config yml and generate templates for at least one API.  Observe the generated master template.

### Component

Creator

### DevOps Resource Kit Version

1.0.0

### .NET Version

6.0

### OS

Windows

### Contact Details

k.schneider@outlook.com

**Comment by adrianhall** [comment]
Thank you for your input on the creator tool.  We are currently looking at the future of the creator tool and would like your feedback.  Please could you fill in the survey at https://forms.office.com/r/w7rQp88NwH - your input is appreciated.

**Comment by adrianhall** [comment]
This project is now in "maintenance" mode. This means that no new features will be accepted and fixes will be limited to security fixes. We expect to retire the DevOps Resource Kit by the end of 2023. At that time, the DevOps Resource Kit repository will be archived and there will be no further updates.

While you are free to fork the DevOps Resource Kit yourself, we recommend that you migrate to the following products:

* If you are using creator, switch over to using [Bicep](https://learn.microsoft.com/azure/azure-resource-manager/bicep/overview) templates. Bicep is a descriptive language for describing infrastructure, fully supports all features of Azure API Management, and is covered in any support agreement that you have with Azure. You can find bicep modules and examples for handling API Management APIs at https://github.com/azure-samples/api-management-sample-apis.
* If you are using extractor, switch your pipelines to use [APIOps](https://github.com/azure/apiops). APIOps applies the concepts of GitOps to API deployments. It is faster and more flexible than the DevOps Resource Kit.
