### ISSUE TITLE
Bug: Extractor not creating gateways-apis template

### ISSUE THREAD

**Issue by eddiecarr** [Azure/azure-api-management-devops-resource-kit#811]
### Report

We are using self hosted gateways. When running the extractor for a single api (tagged to run on the hosted gateway), no gatway-apis template is being created. 

We are passing in the --extractGateways=true parameter on the command line.

This seems to occur because the Name property in the instance of ApiTemplateResource gets changed by the ProcessSingleData method in ApiDataProcessor to add the ApiRevision e.g. ;rev=1

        public void ProcessSingleData(ApiTemplateResource api)
        {
            api.OriginalName = api.Name;
            var isCurrent = api.Properties.IsCurrent;
            api.Properties.IsCurrent = null;

            if (isCurrent == true && !string.IsNullOrEmpty(api.Properties.ApiRevision))
            {
                api.ApiNameWithRevision = $"{api.Name};rev={api.Properties.ApiRevision}";
                if (!api.Name.Contains($";rev={api.Properties.ApiRevision}"))
                {
                    api.Name = $"{api.Name};rev={api.Properties.ApiRevision}";
                }
            }
        }

When the following code is reached in GatewayApiExtractor.cs the api is not returned by the linq query since it's name has been changed (to add the revision) and no longer matches the singleApiName. The apis variable is then null and no template is generated:

                    **var apis = gatewayApis.Where(x => x.Name == singleApiName);**
                    if (!apis.IsNullOrEmpty())
                    {
                        var gatewayApiResources = this.GenerateGatewayApiTemplateResources(gateway.Name, apis);
                        gatewayApiTemplate.TypedResources.GatewayApis.AddRange(gatewayApiResources);
                    }

### Expected Behavior

template gateways-api template does get created

### Actual Behavior

no gateways-api template is generated

### Steps to Reproduce the Problem

Run the extractor for a single API with 

### Component

Extractor

### DevOps Resource Kit Version

1.0

### .NET Version

dotnet 6

### OS

Windows 10 Enterprise

### Logs

```shell
example
```

### Contact Details

edward.james.carr@gmail.com

**Comment by eddiecarr** [comment]
Spotted another problem with the code in GatewayApiExtractor.cs.  In the GenerateGatewayApiTemplateResources method it's using the dependsOn variable prior to it being actually set.

![image](https://user-images.githubusercontent.com/11681444/188634432-9081426f-41b3-421f-bff5-ef5c1623d37c.png)

**Comment by f-alizada** [comment]
Hello @eddiecarr, thank you for raising the issue. 
The bug was closed and PR: #855 addressing this issue was merged into the main branch and will be available in future releases. 
Please feel free to reopen/create new issue if you will face problems with gateway-apis extraction after updating to the latest changes or in future releases.
Best Regards.
