### ISSUE TITLE
Feature Request: Extract specific arm-template type and not only  api

### ISSUE THREAD

**Issue by liorklein** [Azure/azure-api-management-devops-resource-kit#812]
### Scenario

Some time as part of the devops process we want only to deploy "products","policyFragments" , ext... and not an api .
Crrently it is not possible to extract any arm template without extract a full api with all its dependencies 

### Proposal

Give an option to extract single type only by giving as input both the type and name.
For example 
Type: "Microsoft.ApiManagement/service/products"
Name:"Myproduct"

### Contact Details

liorklein@gmail.com

**Comment by adrianhall** [comment]
While I appreciate that this is a requirement for you, it's not something that is in the charter for this tool.  I'd expect this sort of thing to easily be done with Azure PowerShell or Azure CLI scripts, however.  Most things (notable exception: Policy Fragments, which isn't in a GA ARM API version yet) can be done today with Azure PowerShell.

**Comment by KevinHale-Bentley** [comment]
I can vouch for the efficacy of @adrianhall's suggestion.  We use this tool to extract an API's definition, and we post-process the results.  Basically, we remove the non-API-specific items, such as products, global API policy, etc., that we deploy as part of our infrastructure pipeline.  This leaves the API developers to not have to worry about what to do with all of these "extras".
