### ISSUE TITLE
Bug: NamedValueExtractor sets namedValueResource.Properties.Value to null if key vault named value.

### ISSUE THREAD

**Issue by soejensen** [Azure/azure-api-management-devops-resource-kit#817]
### Report

The NamedValueExtractor sets namedValueResource.Properties.Value = null if it is a keyvault named value.

In the BackendExtractor, the method DoesBackendReferenceNamedValue then might compare a null value to backendTemplateResource.properties.title (always null when looking in Azure Resource Explorer) or .description which could also be null

### Expected Behavior

Only backends configured in the targeted API should be detected when running in single API mode

### Actual Behavior

Backends from all APIs are detected as being referenced.

### Steps to Reproduce the Problem

1. Add a certificate from Key Vault to Apim
2. Create an Api with a backend that uses the Client Certificate as Authorization Credentials
3. Run the Extractor in single API mode
4. Backends from other APIs are added to the backends arm template output

### Component

Extractor

### DevOps Resource Kit Version

1.0.0

### .NET Version

6.0.401

### OS

Windows 10 Enterprise 21H1

### Configuration

Configuration:

```yaml
version: 0.0.1
apimServiceName: example-apim-name
```

### Logs

```shell
example
```

### Contact Details

soe@jyskefinans.dk

**Comment by soejensen** [comment]
Steps to reproduce should be:

Create a named value that is of type 'key vault'
Create an Api with a backend 
Use the named value in a policy - {{NamedValue}}
Run the Extractor in single API mode
Backends from other APIs are added to the backends arm template output

**Comment by nagashreeb** [comment]
This issue occurs if the namedvalue type is set to "secret" as well.

**Comment by f-alizada** [comment]
Hello @soejensen! 
Thank you for reporting this. 
The issue was closed since the PR #852 solving this is merged into the main branch and will be available in upcoming releases. 
Feel free to reopen/create new issue in case you will face similar issue with backend templates. 
Best regards.
