### ISSUE TITLE
Feature Request: Diagnostic Names Should Be Parameters

### ISSUE THREAD

**Issue by blockingHD** [Azure/azure-api-management-devops-resource-kit#818]
### Scenario

When releasing between environments each of the App Insight instances that are linked should be named correctly. However if you have web-dev-ai in development when pushing to preprod it will create a second app insights instance (still pointing to preprod mind) but with the Development name.

### Proposal

Make the name of the app insights logger a parameter.

**Comment by adrianhall** [comment]
Which tool are you using?  What is the command line, etc. you are using?

**Comment by ratheeshps** [comment]
When using the extractor tool to create ARMs, it is not creating a logger template or moving the diagnostics (app insights, azuremonitor) to a parameter, even if the APIM has an association with app insights or azure monitor.

**Comment by blockingHD** [comment]
> Which tool are you using?  What is the command line, etc. you are using?

I missed this.

Using the extractor tool in powershell.

**Comment by adrianhall** [comment]
I need the precise command you ran and the configuration file you used.

**Comment by adrianhall** [comment]
Reading this, I don't think we have enough information to set up a repro and see what is going on.  I can't tell how you are setting up your preprod and dev environments and what you are expecting to happen that isn't.  Can we get more information about the scenario please?

**Comment by adrianhall** [comment]
Closing for lack of info.
