### ISSUE TITLE
Bug: parametersOutputDirectoryName  and excludeBuildInGroups not working in the extractor commands

### ISSUE THREAD

**Issue by ratheeshps** [Azure/azure-api-management-devops-resource-kit#822]
### Report

 parametersOutputDirectoryName  and excludeBuildInGroups not working in the extractor commands

### Expected Behavior

It should extract by reading the options

### Actual Behavior

Option 'excludeBuildInGroups' is unknown.
Option 'parametersOutputDirectoryName' is unknown.

### Steps to Reproduce the Problem

1.Run Extractor too with mentioned parameters
`
armtemplates extract --sourceApimName apim-dev --destinationApimName apim-test --resourceGroup rg-dev  --splitAPIs  true --excludeBuildInGroups  true  --fileFolder ./templates --parametersOutputDirectoryName  sd
`

### Component

Extractor

### DevOps Resource Kit Version

1.0.0

### .NET Version

6.0

### OS

Windows. No WSL

### Configuration

Configuration:

```yaml
version: 0.0.1
apimServiceName: example-apim-name
```

### Logs

```shell
example
```

**Comment by ratheeshps** [comment]
Created a PR for fixing this issue
https://github.com/Azure/azure-api-management-devops-resource-kit/pull/823

**Comment by adrianhall** [comment]
Thanks for the PR as well - we'll take a look in the next few days.

**Comment by f-alizada** [comment]
@ratheeshps thank you for reporting the issue and prepared PR! 
PR is merged into the main branch.
