### ISSUE TITLE
Dotnet Restore/ Build command fails for repo

### ISSUE THREAD

**Issue by kunalchandratre1** [Azure/azure-api-management-devops-resource-kit#824]
Hi,
I am trying to run the command as below - [with .net core 6.0]
<img width="799" alt="image" src="https://user-images.githubusercontent.com/8287325/193460469-8ea0a5e8-219f-4a38-a39c-84b81a695120.png">
And it fails with compatibility of some Nuget packages as visible in the attached diagram. Any guidance on how to resolve?

**Comment by adrianhall** [comment]
Very wierd.  We do dotnet restore / dotnet build when we build the automated builds, so it's surprising that this is not working for you.  We also have other entities that build the tools themselves and they also have not reported any issues.  

Do you have something in your environment that would cause you not to consult nuget for packages?  A nuget.config file, for example.

**Comment by adrianhall** [comment]
I cannot reproduce this.  We do dotnet restore / build as part of our build pipelines, and running it locally also works fine.  Sorry, we cannot help with dotnet environment issues.
