### ISSUE TITLE
Bug: Cannot extract based on API Versionsets

### ISSUE THREAD

**Issue by ratheeshps** [Azure/azure-api-management-devops-resource-kit#827]
### Report

Getting error when extracting using apiversionsetname parameter
Error occured: API Version Set with this name doesn't exist
Microsoft.Azure.Management.ApiManagement.ArmTemplates.Common.Exceptions.NoApiVersionSetWithSuchNameFoundException: API Version Set with this name doesn't exist

### Expected Behavior

It should extract all the apis under the given version sets

### Actual Behavior

Error occured: API Version Set with this name doesn't exist
Microsoft.Azure.Management.ApiManagement.ArmTemplates.Common.Exceptions.NoApiVersionSetWithSuchNameFoundException: API Version Set with this name doesn't exist

### Steps to Reproduce the Problem

1. Run extractor
2. Use below command
`apim-templates extract --sourceApimName apim-dev-001 --destinationApimName apim-test-001 --resourceGroup rg-dev-001 --fileFolder c:\temp\apim-01  --apiVersionSetName sample-api`

### Component

Extractor

### DevOps Resource Kit Version

1.0.0

### .NET Version

6.0

### OS

Windows, No WSL

### Configuration

Configuration:

```yaml
version: 0.0.1
apimServiceName: example-apim-name
```

### Logs

```shell
example
```

**Comment by adrianhall** [comment]
Thanks for the report.  We'll look at this when we can assign an engineer to it.

**Comment by f-alizada** [comment]
Hello @ratheeshps, thank you for raising the issue! 
Ticket was closed since PR resolving it was merged into the main branch and will be available in future releases. 
Please feel free to reopen/create new issue if you will face problems with fetching by apiVersionsetName from latest main or future releases. 
Best regards
