### ISSUE TITLE
Delete API Operations

### ISSUE THREAD

**Issue by dannythomas13** [Azure/azure-api-management-devops-resource-kit#828]
Hi I'm looking for some guidance on how best to handle the case where we wish to remove an operation from an API and have this reflected within an upstream environment via ARM Template Deployment.

I thought I had a working pipeline whereby API's were manually created/modified within a Dev environment and then Test/Prod were deployed via an Azure DevOps pipeline. Today is the first day where I wanted to remove a few operations and after the pipeline succeeded I noticed that the operations were still present. I imagined this was the case because the ARM templates were set to Incremental Mode rather than Complete - I then changed to complete and realised that I have now lost the APIM instance and its parent Resource Group :(

I have opened a support ticket to ask for it to be restored but I am not certain they will be able to help.

In future how should I go about achieving this please? It is safest to manually delete any API's and/or Operations?

**Comment by adrianhall** [comment]
It is always safest to delete APIs, Operations, Users, and Products manually.
