### ISSUE TITLE
Add clientCertificateId property for ServiceFabric cluster backend resource

### ISSUE THREAD

**Issue by levimatheri** [Azure/azure-api-management-devops-resource-kit#833]
### Scenario

In API version 2021-08-01 there's a [`clientCertificateId` property](https://learn.microsoft.com/en-us/azure/templates/microsoft.apimanagement/service/backends?pivots=deployment-language-arm-template#backendservicefabricclusterproperties-1) for servicefabric backend resource which is convenient so one doesn't have to specify the `clientCertificateThumbprint`. 

### Proposal

Add this new field to SF backend properties

**Comment by adrianhall** [comment]
Is this for Creator or Extractor?

**Comment by levimatheri** [comment]
Creator. I submitted a PR.

**Comment by adrianhall** [comment]
Reviewed and merged - will be in the next release automatically.
