### ISSUE TITLE
Bug: Policy Fragments are not exporting

### ISSUE THREAD

**Issue by LaurenceBudd** [Azure/azure-api-management-devops-resource-kit#836]
### Report

I have included a policy fragment in the inbound policy of my API operation.

I ran the extractor and can see that the policy file has updated to include: <include-fragment fragment-id="Test" />

The policy fragment code hasn't been extracted and no other files have been changed.

![image](https://user-images.githubusercontent.com/38758617/198588008-ec7b038e-e2f0-4dff-b08d-5f1921c84e72.png)

### Expected Behavior

I expected a policy fragment xml file to be generated that contains the policy fragment to be deployed to other environments.

### Actual Behavior

The policy operation xml file updated to include the line of code that references the policy fragment, but no actual policy fragment code that this represents has been extracted.

### Steps to Reproduce the Problem

1. Create policy fragment
2. Reference policy fragment in inbound policy
3. Run extractor
...

### Component

Extractor

### DevOps Resource Kit Version

Latest 1.0.0

### .NET Version

6.0.402

### OS

Windows 10

### Configuration

Configuration:
{
    "baseFileName": "digitalclaims",
    "sourceApimName": "****",
    "destinationApimName": "*****",
    "resourceGroup": "***",
    "fileFolder": "./SharedTemplates/****",
    "linkedTemplatesBaseUrl": "{{location}}{{query}}",
    "LinkedTemplatesUrlQueryString": "{{query}}",
    "policyXMLBaseUrl": "{{location}}/policies",
    "policyXMLSasToken": "{{query}}",
    "apiName": "digitalclaims",
    "paramNamedValue": "true"
}

### API Management Configuration

SKU: Developer
Full Admin: Can be obtained

### Logs

N/A

### Anything else?

N/A

### Contact Details

laurencebudd@hastingsdirect.com

**Comment by f-alizada** [comment]
Hello @LaurenceBudd, thank you for raising the issue.
I was able to reproduce the issue only in one case: the id of the policy-fragment having different letter case than in include-fragment. For example, id of the policy fragment is **test** and include-policy fragment-id="**Test**" will not extract the policy fragment at the moment. 
Could you please confirm if that is the case or there are other scenarios as well?
Best regards.

**Comment by f-alizada** [comment]
Hello @LaurenceBudd.
The issue was closed since the PR #844 was merged addressing it.
Feel free to reopen the issue/create a new one if the case is different for you.
