### ISSUE TITLE
Feature Request: Attach API to API Manager gateways (Self hosted gateway node) - Creator tool

### ISSUE THREAD

**Issue by AL1041713** [Azure/azure-api-management-devops-resource-kit#840]
### Scenario

I would like to use Gateways features of API Management services to make cross clouds API exposition over APIM.
I have deployed an infra that have a main APIM on Azure and a gateway node on AWS EKS.

I used to use the Creator tool to automatically deploy through a GitHub workflow many APIs to my API Manager instances.
In this context I would also use this tool to expose APIs hosted on AWS over the API management gateway node, but in the yaml config file that is consumed by the Creator tool that would be great to attach API to a Gateway.

### Proposal

Having the same kind of syntax to declare and use a gateways over the yaml config file used by the Creator tool as it is done for the tags:

`apis:`
`- name: myAPI`
      `type: http`
      `displayName: My API`
      `description: myFirstAPI`
      `serviceUrl: http://myApiBackendUrl.com`
      `openApiSpec: C:\Users\myUsername\Projects\azure-api-management-devops-example\src\ArmTemplates\Creator\ExampleFiles\OpenApiSpecs\swaggerPetstore.json`
      `openApiSpecFormat: swagger`
      `policy: C:\Users\myUsername\Projects\azure-api-management-devops-example\src\ArmTemplates\Creator\ExampleFiles\XMLPolicies\apiPolicyHeaders.xml`
      `suffix: conf`
      `subscriptionRequired: true`
      `isCurrent: true`
      `apiVersion: v1`
      `apiVersionDescription: My first version`
      `apiVersionSetId: myAPIVersionSetID`
      `apiRevision: 1`
      `apiRevisionDescription: My first revision `
      `products: myProduct`
      `tags: tag1, tag2`
  **`gateways: node1, node2`**
      `operations:`
        `addPet:`
          `policy: C:\Users\myUsername\Projects\azure-api-management-devops-example\src\ArmTemplates\Creator\ExampleFiles\XMLPolicies\operationRateLimit.xml`
      `products: starter, platinum`

`tags:`
    `- displayName: tag1`
    `- displayName: tag2`

**`gateways:`**
    **`- name: node1`**
          **`location: West Europe`**
          **`description: hello I'm a node in another cloud or an onpremise server`**
    **`- name: node2`**
          **`location: West Europe`**
          **`description: hello I'm a node in another cloud or an onpremise server`**

### Contact Details

valentin.malard@external.totalenergies.com

**Comment by adrianhall** [comment]
Thank you for your input on the creator tool.  We are currently looking at the future of the creator tool and would like your feedback.  Please could you fill in the survey at https://forms.office.com/r/w7rQp88NwH - your input is appreciated.

**Comment by adrianhall** [comment]
This project is now in "maintenance" mode. This means that no new features will be accepted and fixes will be limited to security fixes. We expect to retire the DevOps Resource Kit by the end of 2023. At that time, the DevOps Resource Kit repository will be archived and there will be no further updates.

While you are free to fork the DevOps Resource Kit yourself, we recommend that you migrate to the following products:

* If you are using creator, switch over to using [Bicep](https://learn.microsoft.com/azure/azure-resource-manager/bicep/overview) templates. Bicep is a descriptive language for describing infrastructure, fully supports all features of Azure API Management, and is covered in any support agreement that you have with Azure. You can find bicep modules and examples for handling API Management APIs at https://github.com/azure-samples/api-management-sample-apis.
* If you are using extractor, switch your pipelines to use [APIOps](https://github.com/azure/apiops). APIOps applies the concepts of GitOps to API deployments. It is faster and more flexible than the DevOps Resource Kit.
