### ISSUE TITLE
Bug: Loggers created in the main API file

### ISSUE THREAD

**Issue by mikaelsand** [Azure/azure-api-management-devops-resource-kit#843]
### Report

When I extract a single API the service-wide loggers are exported as well. Service wide features does not belong in the main API files. It should contain Operations, Policy Refs, Schemas etc. To me, it is an OpenAPI-file in ARM format.

### Expected Behavior

If loggers are connected to the API, they should be in a _separate_ file and use parameter values for loggerId. Currently they are hard coded to the source environment.

### Actual Behavior

Loggers are exported to the main API file and have to be removed, or updated manually before deployment to TEST or PROD.

### Steps to Reproduce the Problem

1. Use this config:
```JSON
{
    "sourceApimName": "MySourceAPImInstanceName",
    "destinationApimName": "MyDestinationAPImInstanceName",
    "resourceGroup": "MySourceAPImInstanceResourceGroup",
    "fileFolder": "/extract/apitemplates",
    "apiName": "name-of-my-api",
    "policyXMLBaseUrl": "",
    "policyXMLSasToken": ""
}
```
2.
Expect separate files for Loggers.
3.
Find the loggers in the main API file.
...

### Component

Extractor

### DevOps Resource Kit Version

1.0.0

### .NET Version

6.0.402

### OS

Win10 21H2

### Configuration

Configuration:

```JSON
{
    "sourceApimName": "MySourceAPImInstanceName",
    "destinationApimName": "MyDestinationAPImInstanceName",
    "resourceGroup": "MySourceAPImInstanceResourceGroup",
    "fileFolder": "/extract/apitemplates",
    "apiName": "name-of-my-api",
    "policyXMLBaseUrl": "",
    "policyXMLSasToken": ""
}
```

### API Management Configuration

Developer SKU.
Yes I have admin rights.
No, it is not on a VNET.

### Logs

```shell
example
```

### Anything else?

This relates to the other Bug I have reported on Product and Product API being in the main API file. External resources **do not belong** in the main API file.

I looked in old, extracted files form about 1.5 years ago and they _do not_ contain any logger information, even if the platform contained those.

### Contact Details

mikael_sand@hotmail.com

**Comment by adrianhall** [comment]
If an API definition on the source system depends on loggers, then those loggers are exported as well.  This is a feature of the system.

#as-designed.

**Comment by mikaelsand** [comment]
I get that @adrianhall but why not put those in another file and why export ALL the Loggers into a single APIs ARM file?
Wouldn't it be better if the loggers was separated into its own files, and then have the loggingsettings for the APIs be in the API file?
