### ISSUE TITLE
Bug: header properties are missing from extracted template

### ISSUE THREAD

**Issue by laurynasr** [Azure/azure-api-management-devops-resource-kit#862]
### Report

Some header properties are lost when extracting an API:
- type
- values
- required

Expected JSON and API configuration in APIM instance:
```json
          "headers": [
            {
              "defaultValue": "return=minimal",
              "description": "Indicates a level of details in the response. This operation supports 'return=representation' and 'return=minimal' preferences.",
              "name": "Prefer",
              "type": "string",
              "values": [
                "return=minimal",
                "return=representation"
              ]
            },
```

Actual extracted JSON:
```json
          "headers": [
            {
              "defaultValue": "return=minimal",
              "description": "Indicates a level of details in the response. This operation supports 'return=representation' and 'return=minimal' preferences.",
              "name": "Prefer"
            },
```

### Expected Behavior

Expected JSON:
```json
          "headers": [
            {
              "defaultValue": "return=minimal",
              "description": "Indicates a level of details in the response. This operation supports 'return=representation' and 'return=minimal' preferences.",
              "name": "Prefer",
              "type": "string",
              "values": [
                "return=minimal",
                "return=representation"
              ]
            },
```

### Actual Behavior

Actual extracted JSON:
```json
          "headers": [
            {
              "defaultValue": "return=minimal",
              "description": "Indicates a level of details in the response. This operation supports 'return=representation' and 'return=minimal' preferences.",
              "name": "Prefer"
            },
```

### Steps to Reproduce the Problem

1. Create an API in API Management instance and configure its operation to allow multiple values for a header
2. Extract the API using Extractor tool
3. The extracted API template does not contain the allowed values, header type or "required" property.

![image](https://user-images.githubusercontent.com/18733763/214256423-475ec95c-55e5-44d4-9eac-93d6c1d50176.png)

### Component

Extractor

### DevOps Resource Kit Version

1.1.0

### .NET Version

6.0.402

### OS

Windows 10

### API Management Configuration

sku: Standard
I have admin rights
Not in VNET

**Comment by adrianhall** [comment]
This project is now in "maintenance" mode. This means that no new features will be accepted and fixes will be limited to security fixes. We expect to retire the DevOps Resource Kit by the end of 2023. At that time, the DevOps Resource Kit repository will be archived and there will be no further updates.

While you are free to fork the DevOps Resource Kit yourself, we recommend that you migrate to the following products:

* If you are using creator, switch over to using [Bicep](https://learn.microsoft.com/azure/azure-resource-manager/bicep/overview) templates. Bicep is a descriptive language for describing infrastructure, fully supports all features of Azure API Management, and is covered in any support agreement that you have with Azure. You can find bicep modules and examples for handling API Management APIs at https://github.com/azure-samples/api-management-sample-apis.
* If you are using extractor, switch your pipelines to use [APIOps](https://github.com/azure/apiops). APIOps applies the concepts of GitOps to API deployments. It is faster and more flexible than the DevOps Resource Kit.
