### ISSUE TITLE
Bug: APIM ARMtemplate Validation failed when deploying extracted APIM API

### ISSUE THREAD

**Issue by DibyaRanjan1** [Azure/azure-api-management-devops-resource-kit#864]
### Report

We are using azure-api-management-devops-resource-kit to extract api and generate arm templates. We found the below issue when trying to validate the ARMtemplate files against the parameters.json file . We are using OKTA as our identity provider.

Template parameter 'secretValues' was provided an invalid value. Expected a value of type 'Object', but received a value of type 'String'

### Expected Behavior

ARM template validation should pass. What should be the default value for secretValues ? We tried all possible values but still the error persists.

  "secretValues": {
      "value": {
        "openIdConnectProviders": {
          "oktaoidc": ""
        }
      }
    }

### Actual Behavior

We are getting below error.

Deployment template validation failed: 'Template parameter 'secretValues' was provided an invalid value. Expected a value of type 'Object', but received a value of type 'String'. Please see https://aka.ms/resource-manager-parameter-files for usage details.'.

### Steps to Reproduce the Problem

1. Use extarctor dot,net command to extract any api. 
2. You can use OKTA as indentity provider in APIM or can use any extrnal identity provider
3. Rub CI/CD pipeline to Validate ARM template against parameter.json file.

### Component

Creator

### DevOps Resource Kit Version

latest

### .NET Version

6.0.307

### OS

windows

### Configuration

NA

### API Management Configuration

Developer tier in DEV
premium tier in QA and PROD

### Logs

NA

### Anything else?

NA

### Contact Details

dibyaranjantripathy1@gmail.com

**Comment by adrianhall** [comment]
I'd recommend switching over to bicep files for this.  The functionality you want is available in bicep and bicep modules are as easy to use as creator.

**Comment by adrianhall** [comment]
This project is now in "maintenance" mode. This means that no new features will be accepted and fixes will be limited to security fixes. We expect to retire the DevOps Resource Kit by the end of 2023. At that time, the DevOps Resource Kit repository will be archived and there will be no further updates.

While you are free to fork the DevOps Resource Kit yourself, we recommend that you migrate to the following products:

* If you are using creator, switch over to using [Bicep](https://learn.microsoft.com/azure/azure-resource-manager/bicep/overview) templates. Bicep is a descriptive language for describing infrastructure, fully supports all features of Azure API Management, and is covered in any support agreement that you have with Azure. You can find bicep modules and examples for handling API Management APIs at https://github.com/azure-samples/api-management-sample-apis.
* If you are using extractor, switch your pipelines to use [APIOps](https://github.com/azure/apiops). APIOps applies the concepts of GitOps to API deployments. It is faster and more flexible than the DevOps Resource Kit.
