### ISSUE TITLE
Bug: Extractor does not include examples for queryParameters and templateParameters 

### ISSUE THREAD

**Issue by Rupo** [Azure/azure-api-management-devops-resource-kit#868]
### Report

When importing an OpenAPI specification with example values on the query and/or path (template) parameters in the API Management portal, the example values are imported successfully.
The values are shown in the exported template in the portal according to the specification:
https://learn.microsoft.com/en-us/rest/api/apimanagement/current-ga/api-operation/get?tabs=HTTP#parametercontract

But when using the Extractor tool, this property is missing in the output files.

Example:
Open API specification
![bild](https://user-images.githubusercontent.com/23128358/220307378-8ba54dd2-1a8c-4dfa-adaa-35a4416ef37c.png)

Exported ARM template in the portal
![bild](https://user-images.githubusercontent.com/23128358/220308060-57dde5f4-db7b-4673-9cae-8fb0e79bba0b.png)

Exported ARM template from the Extractor tool:
![bild](https://user-images.githubusercontent.com/23128358/220311171-498eb2dd-8a82-4a10-a7d6-466b9bbb64a0.png)

### Expected Behavior

The example value(s) to be included in the generated ARM template.

### Actual Behavior

Property "examples" is missing in the ARM template.

### Steps to Reproduce the Problem

1. Import an OpenAPI specification which has an operation with query or path (template) parameters with an example value.
2. Run the Extractor tool.
3. Check the output of the operation in the generated ARM template.

### Component

Extractor

### DevOps Resource Kit Version

1.1.0

### .NET Version

7.0.101

### OS

Windows 10

### API Management Configuration

**- What SKU is being used (as the source for extractor or destination for creator)?** Developer & Consumption.
**- Do you have full admin rights to the service?** Yes.
**- Is the service in a VNET? If so, describe how it is configured?** No.

**Comment by adrianhall** [comment]
This project is now in "maintenance" mode. This means that no new features will be accepted and fixes will be limited to security fixes. We expect to retire the DevOps Resource Kit by the end of 2023. At that time, the DevOps Resource Kit repository will be archived and there will be no further updates.

While you are free to fork the DevOps Resource Kit yourself, we recommend that you migrate to the following products:

* If you are using creator, switch over to using [Bicep](https://learn.microsoft.com/azure/azure-resource-manager/bicep/overview) templates. Bicep is a descriptive language for describing infrastructure, fully supports all features of Azure API Management, and is covered in any support agreement that you have with Azure. You can find bicep modules and examples for handling API Management APIs at https://github.com/azure-samples/api-management-sample-apis.
* If you are using extractor, switch your pipelines to use [APIOps](https://github.com/azure/apiops). APIOps applies the concepts of GitOps to API deployments. It is faster and more flexible than the DevOps Resource Kit.
