### ISSUE TITLE
[Extractor] Extract Products and Products entities (global and single api)

### ISSUE THREAD

**Issue by nzthiago** [Azure/azure-api-management-devops-resource-kit#99]

**Comment by odaibert** [comment]
Also extract product policies.

**Comment by bremnes** [comment]
@lucashuet93 Why was this issue closed? I've been testing the extractor and as far as I can see it doesn't export the products related to the api regardless if I am extracting a single API or all. Which again leads error code `ResourceNotFound` with message `Product not found.` if deploying that arm template into a new api management instance.

Perhaps this is something residing in the feature branch you are working on, [lucashh-creatorextractor-features](https://github.com/Azure/azure-api-management-devops-resource-kit/tree/lucashh-creatorextractor-features)?

**Comment by lucashuet93** [comment]
@bremnes I closed the issue when I opened the PR from my branch into master, but hadn't merged it yet. Sorry for jumping the gun on that one, it's merged into master now.
